apiVersion: system.iosxe.m.upbound.io/v1alpha1
kind: License
metadata:
  annotations:
    meta.upbound.io/example-id: system/v1alpha1/license
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: crossplane-system
spec:
  forProvider:
    bootLevelNetworkAdvantage: true
    bootLevelNetworkAdvantageAddon: dna-advantage
    smartTransportType: "Off"
