// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type RADIUSInitParameters struct {

	// (Number) UDP port for RADIUS accounting server (default is 1813)
	// UDP port for RADIUS accounting server (default is 1813)
	// - Range: `0`-`65534`
	AccountingPort *float64 `json:"accountingPort,omitempty" tf:"accounting_port,omitempty"`

	// (Number) UDP port for RADIUS authentication server (default is 1812)
	// UDP port for RADIUS authentication server (default is 1812)
	// - Range: `0`-`65534`
	AuthenticationPort *float64 `json:"authenticationPort,omitempty" tf:"authentication_port,omitempty"`

	// time after which server state should be verified.
	// Minutes of idle-time after which server state should be verified.
	// - Range: `1`-`35791`
	AutomateTesterIdleTime *float64 `json:"automateTesterIdleTime,omitempty" tf:"automate_tester_idle_time,omitempty"`

	// (Boolean) Do not test accounting ports of the servers.
	// Do not test accounting ports of the servers.
	AutomateTesterIgnoreAcctPort *bool `json:"automateTesterIgnoreAcctPort,omitempty" tf:"automate_tester_ignore_acct_port,omitempty"`

	// (Boolean) Do not test authentication port of the servers.
	// Do not test authentication port of the servers.
	AutomateTesterIgnoreAuthPort *bool `json:"automateTesterIgnoreAuthPort,omitempty" tf:"automate_tester_ignore_auth_port,omitempty"`

	// (Boolean) Send a packet to verify the server status
	// Send a packet to verify the server status
	AutomateTesterProbeOnConfig *bool `json:"automateTesterProbeOnConfig,omitempty" tf:"automate_tester_probe_on_config,omitempty"`

	// (String)
	AutomateTesterUsername *string `json:"automateTesterUsername,omitempty" tf:"automate_tester_username,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// (String) IPv4 address or Hostname for radius server
	// IPv4 address or Hostname for radius server
	IPv4Address *string `json:"ipv4Address,omitempty" tf:"ipv4_address,omitempty"`

	// Choices: 0, 5, 6, 7
	//
	// - Choices: `0`, `5`, `6`, `7`
	KeyEncryption *string `json:"keyEncryption,omitempty" tf:"key_encryption,omitempty"`

	// (String, Sensitive)
	KeySecretRef *v2.SecretKeySelector `json:"keySecretRef,omitempty" tf:"-"`

	// only) The write-only value of the attribute.
	// The write-only value of the attribute.
	KeyWo *string `json:"keyWo,omitempty" tf:"key_wo,omitempty"`

	// only version of the attribute.
	// The write-only version of the attribute.
	KeyWoVersion *float64 `json:"keyWoVersion,omitempty" tf:"key_wo_version,omitempty"`

	// (String) Name for the radius server configuration
	// Name for the radius server configuration
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Specifies an UNENCRYPTED key will follow 6 - Specifies an ENCRYPTED key will follow 7 - Specifies HIDDEN key will follow
	// 0 - Specifies an UNENCRYPTED key will follow 6 - Specifies an ENCRYPTED key will follow 7 - Specifies HIDDEN key will follow
	// - Choices: `0`, `6`, `7`
	PacKeyEncryption *string `json:"pacKeyEncryption,omitempty" tf:"pac_key_encryption,omitempty"`

	// (String, Sensitive) The UNENCRYPTED (cleartext) server key
	// The UNENCRYPTED (cleartext) server key
	PacKeySecretRef *v2.SecretKeySelector `json:"pacKeySecretRef,omitempty" tf:"-"`

	// only) The write-only value of the attribute.
	// The write-only value of the attribute.
	PacKeyWo *string `json:"pacKeyWo,omitempty" tf:"pac_key_wo,omitempty"`

	// only version of the attribute.
	// The write-only version of the attribute.
	PacKeyWoVersion *float64 `json:"pacKeyWoVersion,omitempty" tf:"pac_key_wo_version,omitempty"`

	// (Number) Number of retries to active server (overrides default)
	// Number of retries to active server (overrides default)
	// - Range: `0`-`100`
	Retransmit *float64 `json:"retransmit,omitempty" tf:"retransmit,omitempty"`

	// (Number) Time to wait for a RADIUS server to reply (overrides default)
	// Time to wait for a RADIUS server to reply (overrides default)
	// - Range: `1`-`1000`
	Timeout *float64 `json:"timeout,omitempty" tf:"timeout,omitempty"`
}

type RADIUSObservation struct {

	// (Number) UDP port for RADIUS accounting server (default is 1813)
	// UDP port for RADIUS accounting server (default is 1813)
	// - Range: `0`-`65534`
	AccountingPort *float64 `json:"accountingPort,omitempty" tf:"accounting_port,omitempty"`

	// (Number) UDP port for RADIUS authentication server (default is 1812)
	// UDP port for RADIUS authentication server (default is 1812)
	// - Range: `0`-`65534`
	AuthenticationPort *float64 `json:"authenticationPort,omitempty" tf:"authentication_port,omitempty"`

	// time after which server state should be verified.
	// Minutes of idle-time after which server state should be verified.
	// - Range: `1`-`35791`
	AutomateTesterIdleTime *float64 `json:"automateTesterIdleTime,omitempty" tf:"automate_tester_idle_time,omitempty"`

	// (Boolean) Do not test accounting ports of the servers.
	// Do not test accounting ports of the servers.
	AutomateTesterIgnoreAcctPort *bool `json:"automateTesterIgnoreAcctPort,omitempty" tf:"automate_tester_ignore_acct_port,omitempty"`

	// (Boolean) Do not test authentication port of the servers.
	// Do not test authentication port of the servers.
	AutomateTesterIgnoreAuthPort *bool `json:"automateTesterIgnoreAuthPort,omitempty" tf:"automate_tester_ignore_auth_port,omitempty"`

	// (Boolean) Send a packet to verify the server status
	// Send a packet to verify the server status
	AutomateTesterProbeOnConfig *bool `json:"automateTesterProbeOnConfig,omitempty" tf:"automate_tester_probe_on_config,omitempty"`

	// (String)
	AutomateTesterUsername *string `json:"automateTesterUsername,omitempty" tf:"automate_tester_username,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// (String) The path of the object.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) IPv4 address or Hostname for radius server
	// IPv4 address or Hostname for radius server
	IPv4Address *string `json:"ipv4Address,omitempty" tf:"ipv4_address,omitempty"`

	// Choices: 0, 5, 6, 7
	//
	// - Choices: `0`, `5`, `6`, `7`
	KeyEncryption *string `json:"keyEncryption,omitempty" tf:"key_encryption,omitempty"`

	// only) The write-only value of the attribute.
	// The write-only value of the attribute.
	KeyWo *string `json:"keyWo,omitempty" tf:"key_wo,omitempty"`

	// only version of the attribute.
	// The write-only version of the attribute.
	KeyWoVersion *float64 `json:"keyWoVersion,omitempty" tf:"key_wo_version,omitempty"`

	// (String) Name for the radius server configuration
	// Name for the radius server configuration
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Specifies an UNENCRYPTED key will follow 6 - Specifies an ENCRYPTED key will follow 7 - Specifies HIDDEN key will follow
	// 0 - Specifies an UNENCRYPTED key will follow 6 - Specifies an ENCRYPTED key will follow 7 - Specifies HIDDEN key will follow
	// - Choices: `0`, `6`, `7`
	PacKeyEncryption *string `json:"pacKeyEncryption,omitempty" tf:"pac_key_encryption,omitempty"`

	// only) The write-only value of the attribute.
	// The write-only value of the attribute.
	PacKeyWo *string `json:"pacKeyWo,omitempty" tf:"pac_key_wo,omitempty"`

	// only version of the attribute.
	// The write-only version of the attribute.
	PacKeyWoVersion *float64 `json:"pacKeyWoVersion,omitempty" tf:"pac_key_wo_version,omitempty"`

	// (Number) Number of retries to active server (overrides default)
	// Number of retries to active server (overrides default)
	// - Range: `0`-`100`
	Retransmit *float64 `json:"retransmit,omitempty" tf:"retransmit,omitempty"`

	// (Number) Time to wait for a RADIUS server to reply (overrides default)
	// Time to wait for a RADIUS server to reply (overrides default)
	// - Range: `1`-`1000`
	Timeout *float64 `json:"timeout,omitempty" tf:"timeout,omitempty"`
}

type RADIUSParameters struct {

	// (Number) UDP port for RADIUS accounting server (default is 1813)
	// UDP port for RADIUS accounting server (default is 1813)
	// - Range: `0`-`65534`
	// +kubebuilder:validation:Optional
	AccountingPort *float64 `json:"accountingPort,omitempty" tf:"accounting_port,omitempty"`

	// (Number) UDP port for RADIUS authentication server (default is 1812)
	// UDP port for RADIUS authentication server (default is 1812)
	// - Range: `0`-`65534`
	// +kubebuilder:validation:Optional
	AuthenticationPort *float64 `json:"authenticationPort,omitempty" tf:"authentication_port,omitempty"`

	// time after which server state should be verified.
	// Minutes of idle-time after which server state should be verified.
	// - Range: `1`-`35791`
	// +kubebuilder:validation:Optional
	AutomateTesterIdleTime *float64 `json:"automateTesterIdleTime,omitempty" tf:"automate_tester_idle_time,omitempty"`

	// (Boolean) Do not test accounting ports of the servers.
	// Do not test accounting ports of the servers.
	// +kubebuilder:validation:Optional
	AutomateTesterIgnoreAcctPort *bool `json:"automateTesterIgnoreAcctPort,omitempty" tf:"automate_tester_ignore_acct_port,omitempty"`

	// (Boolean) Do not test authentication port of the servers.
	// Do not test authentication port of the servers.
	// +kubebuilder:validation:Optional
	AutomateTesterIgnoreAuthPort *bool `json:"automateTesterIgnoreAuthPort,omitempty" tf:"automate_tester_ignore_auth_port,omitempty"`

	// (Boolean) Send a packet to verify the server status
	// Send a packet to verify the server status
	// +kubebuilder:validation:Optional
	AutomateTesterProbeOnConfig *bool `json:"automateTesterProbeOnConfig,omitempty" tf:"automate_tester_probe_on_config,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	AutomateTesterUsername *string `json:"automateTesterUsername,omitempty" tf:"automate_tester_username,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	// +kubebuilder:validation:Optional
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// (String) IPv4 address or Hostname for radius server
	// IPv4 address or Hostname for radius server
	// +kubebuilder:validation:Optional
	IPv4Address *string `json:"ipv4Address,omitempty" tf:"ipv4_address,omitempty"`

	// Choices: 0, 5, 6, 7
	//
	// - Choices: `0`, `5`, `6`, `7`
	// +kubebuilder:validation:Optional
	KeyEncryption *string `json:"keyEncryption,omitempty" tf:"key_encryption,omitempty"`

	// (String, Sensitive)
	// +kubebuilder:validation:Optional
	KeySecretRef *v2.SecretKeySelector `json:"keySecretRef,omitempty" tf:"-"`

	// only) The write-only value of the attribute.
	// The write-only value of the attribute.
	// +kubebuilder:validation:Optional
	KeyWo *string `json:"keyWo,omitempty" tf:"key_wo,omitempty"`

	// only version of the attribute.
	// The write-only version of the attribute.
	// +kubebuilder:validation:Optional
	KeyWoVersion *float64 `json:"keyWoVersion,omitempty" tf:"key_wo_version,omitempty"`

	// (String) Name for the radius server configuration
	// Name for the radius server configuration
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Specifies an UNENCRYPTED key will follow 6 - Specifies an ENCRYPTED key will follow 7 - Specifies HIDDEN key will follow
	// 0 - Specifies an UNENCRYPTED key will follow 6 - Specifies an ENCRYPTED key will follow 7 - Specifies HIDDEN key will follow
	// - Choices: `0`, `6`, `7`
	// +kubebuilder:validation:Optional
	PacKeyEncryption *string `json:"pacKeyEncryption,omitempty" tf:"pac_key_encryption,omitempty"`

	// (String, Sensitive) The UNENCRYPTED (cleartext) server key
	// The UNENCRYPTED (cleartext) server key
	// +kubebuilder:validation:Optional
	PacKeySecretRef *v2.SecretKeySelector `json:"pacKeySecretRef,omitempty" tf:"-"`

	// only) The write-only value of the attribute.
	// The write-only value of the attribute.
	// +kubebuilder:validation:Optional
	PacKeyWo *string `json:"pacKeyWo,omitempty" tf:"pac_key_wo,omitempty"`

	// only version of the attribute.
	// The write-only version of the attribute.
	// +kubebuilder:validation:Optional
	PacKeyWoVersion *float64 `json:"pacKeyWoVersion,omitempty" tf:"pac_key_wo_version,omitempty"`

	// (Number) Number of retries to active server (overrides default)
	// Number of retries to active server (overrides default)
	// - Range: `0`-`100`
	// +kubebuilder:validation:Optional
	Retransmit *float64 `json:"retransmit,omitempty" tf:"retransmit,omitempty"`

	// (Number) Time to wait for a RADIUS server to reply (overrides default)
	// Time to wait for a RADIUS server to reply (overrides default)
	// - Range: `1`-`1000`
	// +kubebuilder:validation:Optional
	Timeout *float64 `json:"timeout,omitempty" tf:"timeout,omitempty"`
}

// RADIUSSpec defines the desired state of RADIUS
type RADIUSSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   RADIUSParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RADIUSInitParameters `json:"initProvider,omitempty"`
}

// RADIUSStatus defines the observed state of RADIUS.
type RADIUSStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               RADIUSObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// RADIUS is the Schema for the RADIUSs API. This resource can manage the Radius configuration.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,iosxe}
type RADIUS struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   RADIUSSpec   `json:"spec"`
	Status RADIUSStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RADIUSList contains a list of RADIUSs
type RADIUSList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RADIUS `json:"items"`
}

// Repository type metadata.
var (
	RADIUS_Kind             = "RADIUS"
	RADIUS_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RADIUS_Kind}.String()
	RADIUS_KindAPIVersion   = RADIUS_Kind + "." + CRDGroupVersion.String()
	RADIUS_GroupVersionKind = CRDGroupVersion.WithKind(RADIUS_Kind)
)

func init() {
	SchemeBuilder.Register(&RADIUS{}, &RADIUSList{})
}
