// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type TACACSServerInitParameters struct {

	// (Boolean) Unknown Tacacs+ attributes
	// Unknown Tacacs+ attributes
	AttributeAllowUnknown *bool `json:"attributeAllowUnknown,omitempty" tf:"attribute_allow_unknown,omitempty"`

	// is. Default value is all.
	// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is. Default value is `all`.
	// - Choices: `all`, `attributes`
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// (Boolean) Allow user to specify tacacs server to use with `@server'
	// Allow user to specify tacacs server to use with `@server'
	DirectedRequest *bool `json:"directedRequest,omitempty" tf:"directed_request,omitempty"`

	// (Boolean) Do not truncate the @hostname from username.
	// Do not truncate the @hostname from username.
	DirectedRequestNoTruncate *bool `json:"directedRequestNoTruncate,omitempty" tf:"directed_request_no_truncate,omitempty"`

	// (Boolean) restrict queries to directed request servers only
	// restrict queries to directed request servers only
	DirectedRequestRestricted *bool `json:"directedRequestRestricted,omitempty" tf:"directed_request_restricted,omitempty"`

	// Specifies an UNENCRYPTED key will follow 6 - Specifies an ENCRYPTED key will follow 7 - Specifies HIDDEN key will follow
	// 0 - Specifies an UNENCRYPTED key will follow 6 - Specifies an ENCRYPTED key will follow 7 - Specifies HIDDEN key will follow
	// - Choices: `0`, `6`, `7`
	Encryption *string `json:"encryption,omitempty" tf:"encryption,omitempty"`

	// (String, Sensitive)
	KeySecretRef *v2.SecretKeySelector `json:"keySecretRef,omitempty" tf:"-"`

	// only) The write-only value of the attribute.
	// The write-only value of the attribute.
	KeyWo *string `json:"keyWo,omitempty" tf:"key_wo,omitempty"`

	// only version of the attribute.
	// The write-only version of the attribute.
	KeyWoVersion *float64 `json:"keyWoVersion,omitempty" tf:"key_wo_version,omitempty"`

	// (Number) Time to wait for a TACACS server to reply
	// Time to wait for a TACACS server to reply
	// - Range: `1`-`1000`
	Timeout *float64 `json:"timeout,omitempty" tf:"timeout,omitempty"`
}

type TACACSServerObservation struct {

	// (Boolean) Unknown Tacacs+ attributes
	// Unknown Tacacs+ attributes
	AttributeAllowUnknown *bool `json:"attributeAllowUnknown,omitempty" tf:"attribute_allow_unknown,omitempty"`

	// is. Default value is all.
	// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is. Default value is `all`.
	// - Choices: `all`, `attributes`
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// (Boolean) Allow user to specify tacacs server to use with `@server'
	// Allow user to specify tacacs server to use with `@server'
	DirectedRequest *bool `json:"directedRequest,omitempty" tf:"directed_request,omitempty"`

	// (Boolean) Do not truncate the @hostname from username.
	// Do not truncate the @hostname from username.
	DirectedRequestNoTruncate *bool `json:"directedRequestNoTruncate,omitempty" tf:"directed_request_no_truncate,omitempty"`

	// (Boolean) restrict queries to directed request servers only
	// restrict queries to directed request servers only
	DirectedRequestRestricted *bool `json:"directedRequestRestricted,omitempty" tf:"directed_request_restricted,omitempty"`

	// Specifies an UNENCRYPTED key will follow 6 - Specifies an ENCRYPTED key will follow 7 - Specifies HIDDEN key will follow
	// 0 - Specifies an UNENCRYPTED key will follow 6 - Specifies an ENCRYPTED key will follow 7 - Specifies HIDDEN key will follow
	// - Choices: `0`, `6`, `7`
	Encryption *string `json:"encryption,omitempty" tf:"encryption,omitempty"`

	// (String) The path of the object.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// only) The write-only value of the attribute.
	// The write-only value of the attribute.
	KeyWo *string `json:"keyWo,omitempty" tf:"key_wo,omitempty"`

	// only version of the attribute.
	// The write-only version of the attribute.
	KeyWoVersion *float64 `json:"keyWoVersion,omitempty" tf:"key_wo_version,omitempty"`

	// (Number) Time to wait for a TACACS server to reply
	// Time to wait for a TACACS server to reply
	// - Range: `1`-`1000`
	Timeout *float64 `json:"timeout,omitempty" tf:"timeout,omitempty"`
}

type TACACSServerParameters struct {

	// (Boolean) Unknown Tacacs+ attributes
	// Unknown Tacacs+ attributes
	// +kubebuilder:validation:Optional
	AttributeAllowUnknown *bool `json:"attributeAllowUnknown,omitempty" tf:"attribute_allow_unknown,omitempty"`

	// is. Default value is all.
	// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is. Default value is `all`.
	// - Choices: `all`, `attributes`
	// +kubebuilder:validation:Optional
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	// +kubebuilder:validation:Optional
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// (Boolean) Allow user to specify tacacs server to use with `@server'
	// Allow user to specify tacacs server to use with `@server'
	// +kubebuilder:validation:Optional
	DirectedRequest *bool `json:"directedRequest,omitempty" tf:"directed_request,omitempty"`

	// (Boolean) Do not truncate the @hostname from username.
	// Do not truncate the @hostname from username.
	// +kubebuilder:validation:Optional
	DirectedRequestNoTruncate *bool `json:"directedRequestNoTruncate,omitempty" tf:"directed_request_no_truncate,omitempty"`

	// (Boolean) restrict queries to directed request servers only
	// restrict queries to directed request servers only
	// +kubebuilder:validation:Optional
	DirectedRequestRestricted *bool `json:"directedRequestRestricted,omitempty" tf:"directed_request_restricted,omitempty"`

	// Specifies an UNENCRYPTED key will follow 6 - Specifies an ENCRYPTED key will follow 7 - Specifies HIDDEN key will follow
	// 0 - Specifies an UNENCRYPTED key will follow 6 - Specifies an ENCRYPTED key will follow 7 - Specifies HIDDEN key will follow
	// - Choices: `0`, `6`, `7`
	// +kubebuilder:validation:Optional
	Encryption *string `json:"encryption,omitempty" tf:"encryption,omitempty"`

	// (String, Sensitive)
	// +kubebuilder:validation:Optional
	KeySecretRef *v2.SecretKeySelector `json:"keySecretRef,omitempty" tf:"-"`

	// only) The write-only value of the attribute.
	// The write-only value of the attribute.
	// +kubebuilder:validation:Optional
	KeyWo *string `json:"keyWo,omitempty" tf:"key_wo,omitempty"`

	// only version of the attribute.
	// The write-only version of the attribute.
	// +kubebuilder:validation:Optional
	KeyWoVersion *float64 `json:"keyWoVersion,omitempty" tf:"key_wo_version,omitempty"`

	// (Number) Time to wait for a TACACS server to reply
	// Time to wait for a TACACS server to reply
	// - Range: `1`-`1000`
	// +kubebuilder:validation:Optional
	Timeout *float64 `json:"timeout,omitempty" tf:"timeout,omitempty"`
}

// TACACSServerSpec defines the desired state of TACACSServer
type TACACSServerSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   TACACSServerParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TACACSServerInitParameters `json:"initProvider,omitempty"`
}

// TACACSServerStatus defines the observed state of TACACSServer.
type TACACSServerStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               TACACSServerObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// TACACSServer is the Schema for the TACACSServers API. This resource can manage the TACACS Server configuration.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,iosxe}
type TACACSServer struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              TACACSServerSpec   `json:"spec"`
	Status            TACACSServerStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TACACSServerList contains a list of TACACSServers
type TACACSServerList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TACACSServer `json:"items"`
}

// Repository type metadata.
var (
	TACACSServer_Kind             = "TACACSServer"
	TACACSServer_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: TACACSServer_Kind}.String()
	TACACSServer_KindAPIVersion   = TACACSServer_Kind + "." + CRDGroupVersion.String()
	TACACSServer_GroupVersionKind = CRDGroupVersion.WithKind(TACACSServer_Kind)
)

func init() {
	SchemeBuilder.Register(&TACACSServer{}, &TACACSServerList{})
}
