apiVersion: acl.iosxe.upbound.io/v1alpha1
kind: RoleBased
metadata:
  annotations:
    meta.upbound.io/example-id: acl/v1alpha1/rolebased
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    name: RBACL1
