// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ExporterInitParameters struct {

	// is. Default value is all.
	// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is. Default value is `all`.
	// - Choices: `all`, `attributes`
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// (String) Provide a description for this Flow Exporter
	// Provide a description for this Flow Exporter
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String)
	DestinationIP *string `json:"destinationIp,omitempty" tf:"destination_ip,omitempty"`

	// (String) Optional VRF label
	// Optional VRF label
	DestinationIPVrf *string `json:"destinationIpVrf,omitempty" tf:"destination_ip_vrf,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// (String) Export protocol version
	// Export protocol version
	// - Choices: `ipfix`, `netflow-v5`, `netflow-v9`
	ExportProtocol *string `json:"exportProtocol,omitempty" tf:"export_protocol,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) Option resend time
	// Option resend time
	// - Range: `1`-`86400`
	OptionApplicationAttributesTimeout *float64 `json:"optionApplicationAttributesTimeout,omitempty" tf:"option_application_attributes_timeout,omitempty"`

	// (Number) Option resend time
	// Option resend time
	// - Range: `1`-`86400`
	OptionApplicationTableTimeout *float64 `json:"optionApplicationTableTimeout,omitempty" tf:"option_application_table_timeout,omitempty"`

	// (Number) Option resend time
	// Option resend time
	// - Range: `1`-`86400`
	OptionInterfaceTableTimeout *float64 `json:"optionInterfaceTableTimeout,omitempty" tf:"option_interface_table_timeout,omitempty"`

	// (Boolean) Export Sampler Option
	// Export Sampler Option
	OptionSamplerTable *bool `json:"optionSamplerTable,omitempty" tf:"option_sampler_table,omitempty"`

	// (Number) Option resend time
	// Option resend time
	// - Range: `1`-`86400`
	OptionVrfTableTimeout *float64 `json:"optionVrfTableTimeout,omitempty" tf:"option_vrf_table_timeout,omitempty"`

	// (String) Five GigabitEthernet
	// Five GigabitEthernet
	SourceFiveGigabitEthernet *string `json:"sourceFiveGigabitEthernet,omitempty" tf:"source_five_gigabit_ethernet,omitempty"`

	// (String) Forty GigabitEthernet
	// Forty GigabitEthernet
	SourceFortyGigabitEthernet *string `json:"sourceFortyGigabitEthernet,omitempty" tf:"source_forty_gigabit_ethernet,omitempty"`

	// (String) GigabitEthernet IEEE 802.3z
	// GigabitEthernet IEEE 802.3z
	SourceGigabitEthernet *string `json:"sourceGigabitEthernet,omitempty" tf:"source_gigabit_ethernet,omitempty"`

	// (String) Hundred GigabitEthernet
	// Hundred GigabitEthernet
	SourceHundredGigabitEthernet *string `json:"sourceHundredGigabitEthernet,omitempty" tf:"source_hundred_gigabit_ethernet,omitempty"`

	// (Number) Loopback interface
	// Loopback interface
	// - Range: `0`-`2147483647`
	SourceLoopback *float64 `json:"sourceLoopback,omitempty" tf:"source_loopback,omitempty"`

	// (Number) Ethernet Channel of interfaces
	// Ethernet Channel of interfaces
	// - Range: `0`-`4294967295`
	SourcePortChannel *float64 `json:"sourcePortChannel,omitempty" tf:"source_port_channel,omitempty"`

	// (String) Ten Gigabit Ethernet
	// Ten Gigabit Ethernet
	SourceTenGigabitEthernet *string `json:"sourceTenGigabitEthernet,omitempty" tf:"source_ten_gigabit_ethernet,omitempty"`

	// (String) Twenty Five GigabitEthernet
	// Twenty Five GigabitEthernet
	SourceTwentyFiveGigabitEthernet *string `json:"sourceTwentyFiveGigabitEthernet,omitempty" tf:"source_twenty_five_gigabit_ethernet,omitempty"`

	// (String) Two GigabitEthernet
	// Two GigabitEthernet
	SourceTwoGigabitEthernet *string `json:"sourceTwoGigabitEthernet,omitempty" tf:"source_two_gigabit_ethernet,omitempty"`

	// (Number) Iosxr Vlans
	// Iosxr Vlans
	// - Range: `0`-`65535`
	SourceVlan *float64 `json:"sourceVlan,omitempty" tf:"source_vlan,omitempty"`

	// (Number) Optional TTL or hop limit
	// Optional TTL or hop limit
	// - Range: `0`-`255`
	TTL *float64 `json:"ttl,omitempty" tf:"ttl,omitempty"`

	// (Number) Resend data based on a timeout
	// Resend data based on a timeout
	// - Range: `1`-`86400`
	TemplateDataTimeout *float64 `json:"templateDataTimeout,omitempty" tf:"template_data_timeout,omitempty"`

	// (Number) UDP transport protocol
	// UDP transport protocol
	// - Range: `0`-`65535`
	TransportUDP *float64 `json:"transportUdp,omitempty" tf:"transport_udp,omitempty"`
}

type ExporterObservation struct {

	// is. Default value is all.
	// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is. Default value is `all`.
	// - Choices: `all`, `attributes`
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// (String) Provide a description for this Flow Exporter
	// Provide a description for this Flow Exporter
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String)
	DestinationIP *string `json:"destinationIp,omitempty" tf:"destination_ip,omitempty"`

	// (String) Optional VRF label
	// Optional VRF label
	DestinationIPVrf *string `json:"destinationIpVrf,omitempty" tf:"destination_ip_vrf,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// (String) Export protocol version
	// Export protocol version
	// - Choices: `ipfix`, `netflow-v5`, `netflow-v9`
	ExportProtocol *string `json:"exportProtocol,omitempty" tf:"export_protocol,omitempty"`

	// (String) The path of the object.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) Option resend time
	// Option resend time
	// - Range: `1`-`86400`
	OptionApplicationAttributesTimeout *float64 `json:"optionApplicationAttributesTimeout,omitempty" tf:"option_application_attributes_timeout,omitempty"`

	// (Number) Option resend time
	// Option resend time
	// - Range: `1`-`86400`
	OptionApplicationTableTimeout *float64 `json:"optionApplicationTableTimeout,omitempty" tf:"option_application_table_timeout,omitempty"`

	// (Number) Option resend time
	// Option resend time
	// - Range: `1`-`86400`
	OptionInterfaceTableTimeout *float64 `json:"optionInterfaceTableTimeout,omitempty" tf:"option_interface_table_timeout,omitempty"`

	// (Boolean) Export Sampler Option
	// Export Sampler Option
	OptionSamplerTable *bool `json:"optionSamplerTable,omitempty" tf:"option_sampler_table,omitempty"`

	// (Number) Option resend time
	// Option resend time
	// - Range: `1`-`86400`
	OptionVrfTableTimeout *float64 `json:"optionVrfTableTimeout,omitempty" tf:"option_vrf_table_timeout,omitempty"`

	// (String) Five GigabitEthernet
	// Five GigabitEthernet
	SourceFiveGigabitEthernet *string `json:"sourceFiveGigabitEthernet,omitempty" tf:"source_five_gigabit_ethernet,omitempty"`

	// (String) Forty GigabitEthernet
	// Forty GigabitEthernet
	SourceFortyGigabitEthernet *string `json:"sourceFortyGigabitEthernet,omitempty" tf:"source_forty_gigabit_ethernet,omitempty"`

	// (String) GigabitEthernet IEEE 802.3z
	// GigabitEthernet IEEE 802.3z
	SourceGigabitEthernet *string `json:"sourceGigabitEthernet,omitempty" tf:"source_gigabit_ethernet,omitempty"`

	// (String) Hundred GigabitEthernet
	// Hundred GigabitEthernet
	SourceHundredGigabitEthernet *string `json:"sourceHundredGigabitEthernet,omitempty" tf:"source_hundred_gigabit_ethernet,omitempty"`

	// (Number) Loopback interface
	// Loopback interface
	// - Range: `0`-`2147483647`
	SourceLoopback *float64 `json:"sourceLoopback,omitempty" tf:"source_loopback,omitempty"`

	// (Number) Ethernet Channel of interfaces
	// Ethernet Channel of interfaces
	// - Range: `0`-`4294967295`
	SourcePortChannel *float64 `json:"sourcePortChannel,omitempty" tf:"source_port_channel,omitempty"`

	// (String) Ten Gigabit Ethernet
	// Ten Gigabit Ethernet
	SourceTenGigabitEthernet *string `json:"sourceTenGigabitEthernet,omitempty" tf:"source_ten_gigabit_ethernet,omitempty"`

	// (String) Twenty Five GigabitEthernet
	// Twenty Five GigabitEthernet
	SourceTwentyFiveGigabitEthernet *string `json:"sourceTwentyFiveGigabitEthernet,omitempty" tf:"source_twenty_five_gigabit_ethernet,omitempty"`

	// (String) Two GigabitEthernet
	// Two GigabitEthernet
	SourceTwoGigabitEthernet *string `json:"sourceTwoGigabitEthernet,omitempty" tf:"source_two_gigabit_ethernet,omitempty"`

	// (Number) Iosxr Vlans
	// Iosxr Vlans
	// - Range: `0`-`65535`
	SourceVlan *float64 `json:"sourceVlan,omitempty" tf:"source_vlan,omitempty"`

	// (Number) Optional TTL or hop limit
	// Optional TTL or hop limit
	// - Range: `0`-`255`
	TTL *float64 `json:"ttl,omitempty" tf:"ttl,omitempty"`

	// (Number) Resend data based on a timeout
	// Resend data based on a timeout
	// - Range: `1`-`86400`
	TemplateDataTimeout *float64 `json:"templateDataTimeout,omitempty" tf:"template_data_timeout,omitempty"`

	// (Number) UDP transport protocol
	// UDP transport protocol
	// - Range: `0`-`65535`
	TransportUDP *float64 `json:"transportUdp,omitempty" tf:"transport_udp,omitempty"`
}

type ExporterParameters struct {

	// is. Default value is all.
	// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is. Default value is `all`.
	// - Choices: `all`, `attributes`
	// +kubebuilder:validation:Optional
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// (String) Provide a description for this Flow Exporter
	// Provide a description for this Flow Exporter
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	DestinationIP *string `json:"destinationIp,omitempty" tf:"destination_ip,omitempty"`

	// (String) Optional VRF label
	// Optional VRF label
	// +kubebuilder:validation:Optional
	DestinationIPVrf *string `json:"destinationIpVrf,omitempty" tf:"destination_ip_vrf,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	// +kubebuilder:validation:Optional
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// (String) Export protocol version
	// Export protocol version
	// - Choices: `ipfix`, `netflow-v5`, `netflow-v9`
	// +kubebuilder:validation:Optional
	ExportProtocol *string `json:"exportProtocol,omitempty" tf:"export_protocol,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) Option resend time
	// Option resend time
	// - Range: `1`-`86400`
	// +kubebuilder:validation:Optional
	OptionApplicationAttributesTimeout *float64 `json:"optionApplicationAttributesTimeout,omitempty" tf:"option_application_attributes_timeout,omitempty"`

	// (Number) Option resend time
	// Option resend time
	// - Range: `1`-`86400`
	// +kubebuilder:validation:Optional
	OptionApplicationTableTimeout *float64 `json:"optionApplicationTableTimeout,omitempty" tf:"option_application_table_timeout,omitempty"`

	// (Number) Option resend time
	// Option resend time
	// - Range: `1`-`86400`
	// +kubebuilder:validation:Optional
	OptionInterfaceTableTimeout *float64 `json:"optionInterfaceTableTimeout,omitempty" tf:"option_interface_table_timeout,omitempty"`

	// (Boolean) Export Sampler Option
	// Export Sampler Option
	// +kubebuilder:validation:Optional
	OptionSamplerTable *bool `json:"optionSamplerTable,omitempty" tf:"option_sampler_table,omitempty"`

	// (Number) Option resend time
	// Option resend time
	// - Range: `1`-`86400`
	// +kubebuilder:validation:Optional
	OptionVrfTableTimeout *float64 `json:"optionVrfTableTimeout,omitempty" tf:"option_vrf_table_timeout,omitempty"`

	// (String) Five GigabitEthernet
	// Five GigabitEthernet
	// +kubebuilder:validation:Optional
	SourceFiveGigabitEthernet *string `json:"sourceFiveGigabitEthernet,omitempty" tf:"source_five_gigabit_ethernet,omitempty"`

	// (String) Forty GigabitEthernet
	// Forty GigabitEthernet
	// +kubebuilder:validation:Optional
	SourceFortyGigabitEthernet *string `json:"sourceFortyGigabitEthernet,omitempty" tf:"source_forty_gigabit_ethernet,omitempty"`

	// (String) GigabitEthernet IEEE 802.3z
	// GigabitEthernet IEEE 802.3z
	// +kubebuilder:validation:Optional
	SourceGigabitEthernet *string `json:"sourceGigabitEthernet,omitempty" tf:"source_gigabit_ethernet,omitempty"`

	// (String) Hundred GigabitEthernet
	// Hundred GigabitEthernet
	// +kubebuilder:validation:Optional
	SourceHundredGigabitEthernet *string `json:"sourceHundredGigabitEthernet,omitempty" tf:"source_hundred_gigabit_ethernet,omitempty"`

	// (Number) Loopback interface
	// Loopback interface
	// - Range: `0`-`2147483647`
	// +kubebuilder:validation:Optional
	SourceLoopback *float64 `json:"sourceLoopback,omitempty" tf:"source_loopback,omitempty"`

	// (Number) Ethernet Channel of interfaces
	// Ethernet Channel of interfaces
	// - Range: `0`-`4294967295`
	// +kubebuilder:validation:Optional
	SourcePortChannel *float64 `json:"sourcePortChannel,omitempty" tf:"source_port_channel,omitempty"`

	// (String) Ten Gigabit Ethernet
	// Ten Gigabit Ethernet
	// +kubebuilder:validation:Optional
	SourceTenGigabitEthernet *string `json:"sourceTenGigabitEthernet,omitempty" tf:"source_ten_gigabit_ethernet,omitempty"`

	// (String) Twenty Five GigabitEthernet
	// Twenty Five GigabitEthernet
	// +kubebuilder:validation:Optional
	SourceTwentyFiveGigabitEthernet *string `json:"sourceTwentyFiveGigabitEthernet,omitempty" tf:"source_twenty_five_gigabit_ethernet,omitempty"`

	// (String) Two GigabitEthernet
	// Two GigabitEthernet
	// +kubebuilder:validation:Optional
	SourceTwoGigabitEthernet *string `json:"sourceTwoGigabitEthernet,omitempty" tf:"source_two_gigabit_ethernet,omitempty"`

	// (Number) Iosxr Vlans
	// Iosxr Vlans
	// - Range: `0`-`65535`
	// +kubebuilder:validation:Optional
	SourceVlan *float64 `json:"sourceVlan,omitempty" tf:"source_vlan,omitempty"`

	// (Number) Optional TTL or hop limit
	// Optional TTL or hop limit
	// - Range: `0`-`255`
	// +kubebuilder:validation:Optional
	TTL *float64 `json:"ttl,omitempty" tf:"ttl,omitempty"`

	// (Number) Resend data based on a timeout
	// Resend data based on a timeout
	// - Range: `1`-`86400`
	// +kubebuilder:validation:Optional
	TemplateDataTimeout *float64 `json:"templateDataTimeout,omitempty" tf:"template_data_timeout,omitempty"`

	// (Number) UDP transport protocol
	// UDP transport protocol
	// - Range: `0`-`65535`
	// +kubebuilder:validation:Optional
	TransportUDP *float64 `json:"transportUdp,omitempty" tf:"transport_udp,omitempty"`
}

// ExporterSpec defines the desired state of Exporter
type ExporterSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ExporterParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ExporterInitParameters `json:"initProvider,omitempty"`
}

// ExporterStatus defines the observed state of Exporter.
type ExporterStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ExporterObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Exporter is the Schema for the Exporters API. This resource can manage the Flow Exporter configuration.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,iosxe}
type Exporter struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   ExporterSpec   `json:"spec"`
	Status ExporterStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ExporterList contains a list of Exporters
type ExporterList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Exporter `json:"items"`
}

// Repository type metadata.
var (
	Exporter_Kind             = "Exporter"
	Exporter_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Exporter_Kind}.String()
	Exporter_KindAPIVersion   = Exporter_Kind + "." + CRDGroupVersion.String()
	Exporter_GroupVersionKind = CRDGroupVersion.WithKind(Exporter_Kind)
)

func init() {
	SchemeBuilder.Register(&Exporter{}, &ExporterList{})
}
