apiVersion: security.iosxe.m.upbound.io/v1alpha1
kind: KeyChain
metadata:
  annotations:
    meta.upbound.io/example-id: security/v1alpha1/keychain
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: crossplane-system
spec:
  forProvider:
    keys:
    - acceptLifetimeInfinite: true
      acceptLifetimeStartDay: 1
      acceptLifetimeStartMonth: Jan
      acceptLifetimeStartTime: "00:00:00"
      acceptLifetimeStartYear: 2025
      id: "1"
      keyStringKeySecretRef:
        key: example-key
        name: example-secret
      sendLifetimeInfinite: true
      sendLifetimeStartDay: 1
      sendLifetimeStartMonth: Jan
      sendLifetimeStartTime: "00:00:00"
      sendLifetimeStartYear: 2025
    name: OSPF-AUTH
