apiVersion: switching.iosxe.m.upbound.io/v1alpha1
kind: VTP
metadata:
  annotations:
    meta.upbound.io/example-id: switching/v1alpha1/vtp
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: crossplane-system
spec:
  forProvider:
    domain: TESTDOMAIN
    file: TEST
    interface: GigabitEthernet1/0/1
    modeTransparent: true
    passwordHidden: false
    passwordSecretRef:
      key: example-key
      name: example-secret
    version: 3
