// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type MulticastInitParameters struct {

	// is. Default value is all.
	// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is. Default value is `all`.
	// - Choices: `all`, `attributes`
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// cost paths
	// RPF across equal-cost paths
	Multipath *bool `json:"multipath,omitempty" tf:"multipath,omitempty"`

	// (source, group) load sharing algorithm selection
	// Per-(source, group) load sharing algorithm selection
	// - Choices: `basic`, `next-hop-based`
	MultipathSGHash *string `json:"multipathSGHash,omitempty" tf:"multipath_s_g_hash,omitempty"`

	// (Attributes List) Select VPN Routing/Forwarding instance (see below for nested schema)
	Vrfs []MulticastVrfsInitParameters `json:"vrfs,omitempty" tf:"vrfs,omitempty"`
}

type MulticastObservation struct {

	// is. Default value is all.
	// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is. Default value is `all`.
	// - Choices: `all`, `attributes`
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// (String) The path of the object.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// cost paths
	// RPF across equal-cost paths
	Multipath *bool `json:"multipath,omitempty" tf:"multipath,omitempty"`

	// (source, group) load sharing algorithm selection
	// Per-(source, group) load sharing algorithm selection
	// - Choices: `basic`, `next-hop-based`
	MultipathSGHash *string `json:"multipathSGHash,omitempty" tf:"multipath_s_g_hash,omitempty"`

	// (Attributes List) Select VPN Routing/Forwarding instance (see below for nested schema)
	Vrfs []MulticastVrfsObservation `json:"vrfs,omitempty" tf:"vrfs,omitempty"`
}

type MulticastParameters struct {

	// is. Default value is all.
	// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is. Default value is `all`.
	// - Choices: `all`, `attributes`
	// +kubebuilder:validation:Optional
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	// +kubebuilder:validation:Optional
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// cost paths
	// RPF across equal-cost paths
	// +kubebuilder:validation:Optional
	Multipath *bool `json:"multipath,omitempty" tf:"multipath,omitempty"`

	// (source, group) load sharing algorithm selection
	// Per-(source, group) load sharing algorithm selection
	// - Choices: `basic`, `next-hop-based`
	// +kubebuilder:validation:Optional
	MultipathSGHash *string `json:"multipathSGHash,omitempty" tf:"multipath_s_g_hash,omitempty"`

	// (Attributes List) Select VPN Routing/Forwarding instance (see below for nested schema)
	// +kubebuilder:validation:Optional
	Vrfs []MulticastVrfsParameters `json:"vrfs,omitempty" tf:"vrfs,omitempty"`
}

type MulticastVrfsInitParameters struct {

	// cost paths
	// RPF across equal-cost paths
	Multipath *bool `json:"multipath,omitempty" tf:"multipath,omitempty"`

	// (source, group) load sharing algorithm selection
	// Per-(source, group) load sharing algorithm selection
	// - Choices: `basic`, `next-hop-based`
	MultipathSGHash *string `json:"multipathSGHash,omitempty" tf:"multipath_s_g_hash,omitempty"`

	// (String)
	Vrf *string `json:"vrf,omitempty" tf:"vrf,omitempty"`
}

type MulticastVrfsObservation struct {

	// cost paths
	// RPF across equal-cost paths
	Multipath *bool `json:"multipath,omitempty" tf:"multipath,omitempty"`

	// (source, group) load sharing algorithm selection
	// Per-(source, group) load sharing algorithm selection
	// - Choices: `basic`, `next-hop-based`
	MultipathSGHash *string `json:"multipathSGHash,omitempty" tf:"multipath_s_g_hash,omitempty"`

	// (String)
	Vrf *string `json:"vrf,omitempty" tf:"vrf,omitempty"`
}

type MulticastVrfsParameters struct {

	// cost paths
	// RPF across equal-cost paths
	// +kubebuilder:validation:Optional
	Multipath *bool `json:"multipath,omitempty" tf:"multipath,omitempty"`

	// (source, group) load sharing algorithm selection
	// Per-(source, group) load sharing algorithm selection
	// - Choices: `basic`, `next-hop-based`
	// +kubebuilder:validation:Optional
	MultipathSGHash *string `json:"multipathSGHash,omitempty" tf:"multipath_s_g_hash,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Vrf *string `json:"vrf" tf:"vrf,omitempty"`
}

// MulticastSpec defines the desired state of Multicast
type MulticastSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            MulticastParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider MulticastInitParameters `json:"initProvider,omitempty"`
}

// MulticastStatus defines the observed state of Multicast.
type MulticastStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               MulticastObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Multicast is the Schema for the Multicasts API. This resource can manage the Multicast configuration.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,iosxe}
type Multicast struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              MulticastSpec   `json:"spec"`
	Status            MulticastStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MulticastList contains a list of Multicasts
type MulticastList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Multicast `json:"items"`
}

// Repository type metadata.
var (
	Multicast_Kind             = "Multicast"
	Multicast_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Multicast_Kind}.String()
	Multicast_KindAPIVersion   = Multicast_Kind + "." + CRDGroupVersion.String()
	Multicast_GroupVersionKind = CRDGroupVersion.WithKind(Multicast_Kind)
)

func init() {
	SchemeBuilder.Register(&Multicast{}, &MulticastList{})
}
