apiVersion: interface.iosxe.upbound.io/v1alpha1
kind: ISIS
metadata:
  annotations:
    meta.upbound.io/example-id: interface/v1alpha1/isis
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    ipv4MetricLevels:
    - level: level-1
      value: 100
    name: "100"
    type: Loopback
