// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type AccessGroupsInitParameters struct {

	// (String) Specify a template name (maximum 48 characters)
	// Specify the access list name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type AccessGroupsObservation struct {

	// (String) Specify a template name (maximum 48 characters)
	// Specify the access list name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type AccessGroupsParameters struct {

	// (String) Specify a template name (maximum 48 characters)
	// Specify the access list name
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`
}

type InterfaceTemplatesInitParameters struct {

	// (String) Specify a template name (maximum 48 characters)
	// Enter name of interface template
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type InterfaceTemplatesObservation struct {

	// (String) Specify a template name (maximum 48 characters)
	// Enter name of interface template
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type InterfaceTemplatesParameters struct {

	// (String) Specify a template name (maximum 48 characters)
	// Enter name of interface template
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`
}

type ServiceTemplateInitParameters struct {

	// (Number) Enter a value between 1 and 1073741823
	// Enter a value between 1 and 1073741823
	// - Range: `1`-`1073741823`
	AbsoluteTimer *float64 `json:"absoluteTimer,omitempty" tf:"absolute_timer,omitempty"`

	// (Attributes List) Access list to be applied (see below for nested schema)
	AccessGroups []AccessGroupsInitParameters `json:"accessGroups,omitempty" tf:"access_groups,omitempty"`

	// authentication
	// pre-authentication
	DNSACLPreauth *string `json:"dnsAclPreauth,omitempty" tf:"dns_acl_preauth,omitempty"`

	// (String) Enter a description
	// Enter a description
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// (Number) Enter a value between 1 and 65535
	// Enter a value between 1 and 65535
	// - Range: `1`-`65535`
	InactivityTimer *float64 `json:"inactivityTimer,omitempty" tf:"inactivity_timer,omitempty"`

	// (Boolean) ARP probe
	// ARP probe
	InactivityTimerProbe *bool `json:"inactivityTimerProbe,omitempty" tf:"inactivity_timer_probe,omitempty"`

	// (Attributes List) Interface template to be applied (see below for nested schema)
	InterfaceTemplates []InterfaceTemplatesInitParameters `json:"interfaceTemplates,omitempty" tf:"interface_templates,omitempty"`

	// (String) Set the link security policy
	// Set the link security policy
	// - Choices: `must-not-secure`, `must-secure`, `should-secure`
	LinksecPolicy *string `json:"linksecPolicy,omitempty" tf:"linksec_policy,omitempty"`

	// (String) mdns policy to be applied
	// mdns policy to be applied
	MdnsServicePolicy *string `json:"mdnsServicePolicy,omitempty" tf:"mdns_service_policy,omitempty"`

	// (String) Specify a template name (maximum 48 characters)
	// Specify a template name (maximum 48 characters)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Append client Mac Address in redirect URL
	// Append client Mac Address in redirect URL
	RedirectAppendClientMac *string `json:"redirectAppendClientMac,omitempty" tf:"redirect_append_client_mac,omitempty"`

	// (String) Append switch Mac Address in redirect URL
	// Append switch Mac Address in redirect URL
	RedirectAppendSwitchMac *string `json:"redirectAppendSwitchMac,omitempty" tf:"redirect_append_switch_mac,omitempty"`

	// (String) Specify a valid URL
	// Specify a valid URL
	RedirectURL *string `json:"redirectUrl,omitempty" tf:"redirect_url,omitempty"`

	// (String) Specify the access list name
	// Specify the access list name
	RedirectURLMatchACL *string `json:"redirectUrlMatchAcl,omitempty" tf:"redirect_url_match_acl,omitempty"`

	// Choices: one-time-redirect, redirect-on-no-match
	//
	// - Choices: `one-time-redirect`, `redirect-on-no-match`
	RedirectURLMatchAction *string `json:"redirectUrlMatchAction,omitempty" tf:"redirect_url_match_action,omitempty"`

	// (String) Configure input Qos policy
	// Configure input Qos policy
	ServicePolicyQosInput *string `json:"servicePolicyQosInput,omitempty" tf:"service_policy_qos_input,omitempty"`

	// (String) Configure output Qos policy
	// Configure output Qos policy
	ServicePolicyQosOutput *string `json:"servicePolicyQosOutput,omitempty" tf:"service_policy_qos_output,omitempty"`

	// (Number) SGT tag
	// SGT tag
	// - Range: `2`-`65519`
	Sgt *float64 `json:"sgt,omitempty" tf:"sgt,omitempty"`

	// (Attributes List) tag name (see below for nested schema)
	Tags []TagsInitParameters `json:"tags,omitempty" tf:"tags,omitempty"`

	// (String) tunnel profile name
	// tunnel profile name
	TunnelCapwapName *string `json:"tunnelCapwapName,omitempty" tf:"tunnel_capwap_name,omitempty"`

	// (Number) Vlan to be applied
	// Vlan to be applied
	// - Range: `1`-`4094`
	Vlan *float64 `json:"vlan,omitempty" tf:"vlan,omitempty"`

	// (String) Vnid to be applied
	// Vnid to be applied
	Vnid *string `json:"vnid,omitempty" tf:"vnid,omitempty"`

	// (Boolean) Critical voice vlan
	// Critical voice vlan
	VoiceVlan *bool `json:"voiceVlan,omitempty" tf:"voice_vlan,omitempty"`
}

type ServiceTemplateObservation struct {

	// (Number) Enter a value between 1 and 1073741823
	// Enter a value between 1 and 1073741823
	// - Range: `1`-`1073741823`
	AbsoluteTimer *float64 `json:"absoluteTimer,omitempty" tf:"absolute_timer,omitempty"`

	// (Attributes List) Access list to be applied (see below for nested schema)
	AccessGroups []AccessGroupsObservation `json:"accessGroups,omitempty" tf:"access_groups,omitempty"`

	// authentication
	// pre-authentication
	DNSACLPreauth *string `json:"dnsAclPreauth,omitempty" tf:"dns_acl_preauth,omitempty"`

	// (String) Enter a description
	// Enter a description
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// (String) The path of the object.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Number) Enter a value between 1 and 65535
	// Enter a value between 1 and 65535
	// - Range: `1`-`65535`
	InactivityTimer *float64 `json:"inactivityTimer,omitempty" tf:"inactivity_timer,omitempty"`

	// (Boolean) ARP probe
	// ARP probe
	InactivityTimerProbe *bool `json:"inactivityTimerProbe,omitempty" tf:"inactivity_timer_probe,omitempty"`

	// (Attributes List) Interface template to be applied (see below for nested schema)
	InterfaceTemplates []InterfaceTemplatesObservation `json:"interfaceTemplates,omitempty" tf:"interface_templates,omitempty"`

	// (String) Set the link security policy
	// Set the link security policy
	// - Choices: `must-not-secure`, `must-secure`, `should-secure`
	LinksecPolicy *string `json:"linksecPolicy,omitempty" tf:"linksec_policy,omitempty"`

	// (String) mdns policy to be applied
	// mdns policy to be applied
	MdnsServicePolicy *string `json:"mdnsServicePolicy,omitempty" tf:"mdns_service_policy,omitempty"`

	// (String) Specify a template name (maximum 48 characters)
	// Specify a template name (maximum 48 characters)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Append client Mac Address in redirect URL
	// Append client Mac Address in redirect URL
	RedirectAppendClientMac *string `json:"redirectAppendClientMac,omitempty" tf:"redirect_append_client_mac,omitempty"`

	// (String) Append switch Mac Address in redirect URL
	// Append switch Mac Address in redirect URL
	RedirectAppendSwitchMac *string `json:"redirectAppendSwitchMac,omitempty" tf:"redirect_append_switch_mac,omitempty"`

	// (String) Specify a valid URL
	// Specify a valid URL
	RedirectURL *string `json:"redirectUrl,omitempty" tf:"redirect_url,omitempty"`

	// (String) Specify the access list name
	// Specify the access list name
	RedirectURLMatchACL *string `json:"redirectUrlMatchAcl,omitempty" tf:"redirect_url_match_acl,omitempty"`

	// Choices: one-time-redirect, redirect-on-no-match
	//
	// - Choices: `one-time-redirect`, `redirect-on-no-match`
	RedirectURLMatchAction *string `json:"redirectUrlMatchAction,omitempty" tf:"redirect_url_match_action,omitempty"`

	// (String) Configure input Qos policy
	// Configure input Qos policy
	ServicePolicyQosInput *string `json:"servicePolicyQosInput,omitempty" tf:"service_policy_qos_input,omitempty"`

	// (String) Configure output Qos policy
	// Configure output Qos policy
	ServicePolicyQosOutput *string `json:"servicePolicyQosOutput,omitempty" tf:"service_policy_qos_output,omitempty"`

	// (Number) SGT tag
	// SGT tag
	// - Range: `2`-`65519`
	Sgt *float64 `json:"sgt,omitempty" tf:"sgt,omitempty"`

	// (Attributes List) tag name (see below for nested schema)
	Tags []TagsObservation `json:"tags,omitempty" tf:"tags,omitempty"`

	// (String) tunnel profile name
	// tunnel profile name
	TunnelCapwapName *string `json:"tunnelCapwapName,omitempty" tf:"tunnel_capwap_name,omitempty"`

	// (Number) Vlan to be applied
	// Vlan to be applied
	// - Range: `1`-`4094`
	Vlan *float64 `json:"vlan,omitempty" tf:"vlan,omitempty"`

	// (String) Vnid to be applied
	// Vnid to be applied
	Vnid *string `json:"vnid,omitempty" tf:"vnid,omitempty"`

	// (Boolean) Critical voice vlan
	// Critical voice vlan
	VoiceVlan *bool `json:"voiceVlan,omitempty" tf:"voice_vlan,omitempty"`
}

type ServiceTemplateParameters struct {

	// (Number) Enter a value between 1 and 1073741823
	// Enter a value between 1 and 1073741823
	// - Range: `1`-`1073741823`
	// +kubebuilder:validation:Optional
	AbsoluteTimer *float64 `json:"absoluteTimer,omitempty" tf:"absolute_timer,omitempty"`

	// (Attributes List) Access list to be applied (see below for nested schema)
	// +kubebuilder:validation:Optional
	AccessGroups []AccessGroupsParameters `json:"accessGroups,omitempty" tf:"access_groups,omitempty"`

	// authentication
	// pre-authentication
	// +kubebuilder:validation:Optional
	DNSACLPreauth *string `json:"dnsAclPreauth,omitempty" tf:"dns_acl_preauth,omitempty"`

	// (String) Enter a description
	// Enter a description
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	// +kubebuilder:validation:Optional
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// (Number) Enter a value between 1 and 65535
	// Enter a value between 1 and 65535
	// - Range: `1`-`65535`
	// +kubebuilder:validation:Optional
	InactivityTimer *float64 `json:"inactivityTimer,omitempty" tf:"inactivity_timer,omitempty"`

	// (Boolean) ARP probe
	// ARP probe
	// +kubebuilder:validation:Optional
	InactivityTimerProbe *bool `json:"inactivityTimerProbe,omitempty" tf:"inactivity_timer_probe,omitempty"`

	// (Attributes List) Interface template to be applied (see below for nested schema)
	// +kubebuilder:validation:Optional
	InterfaceTemplates []InterfaceTemplatesParameters `json:"interfaceTemplates,omitempty" tf:"interface_templates,omitempty"`

	// (String) Set the link security policy
	// Set the link security policy
	// - Choices: `must-not-secure`, `must-secure`, `should-secure`
	// +kubebuilder:validation:Optional
	LinksecPolicy *string `json:"linksecPolicy,omitempty" tf:"linksec_policy,omitempty"`

	// (String) mdns policy to be applied
	// mdns policy to be applied
	// +kubebuilder:validation:Optional
	MdnsServicePolicy *string `json:"mdnsServicePolicy,omitempty" tf:"mdns_service_policy,omitempty"`

	// (String) Specify a template name (maximum 48 characters)
	// Specify a template name (maximum 48 characters)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Append client Mac Address in redirect URL
	// Append client Mac Address in redirect URL
	// +kubebuilder:validation:Optional
	RedirectAppendClientMac *string `json:"redirectAppendClientMac,omitempty" tf:"redirect_append_client_mac,omitempty"`

	// (String) Append switch Mac Address in redirect URL
	// Append switch Mac Address in redirect URL
	// +kubebuilder:validation:Optional
	RedirectAppendSwitchMac *string `json:"redirectAppendSwitchMac,omitempty" tf:"redirect_append_switch_mac,omitempty"`

	// (String) Specify a valid URL
	// Specify a valid URL
	// +kubebuilder:validation:Optional
	RedirectURL *string `json:"redirectUrl,omitempty" tf:"redirect_url,omitempty"`

	// (String) Specify the access list name
	// Specify the access list name
	// +kubebuilder:validation:Optional
	RedirectURLMatchACL *string `json:"redirectUrlMatchAcl,omitempty" tf:"redirect_url_match_acl,omitempty"`

	// Choices: one-time-redirect, redirect-on-no-match
	//
	// - Choices: `one-time-redirect`, `redirect-on-no-match`
	// +kubebuilder:validation:Optional
	RedirectURLMatchAction *string `json:"redirectUrlMatchAction,omitempty" tf:"redirect_url_match_action,omitempty"`

	// (String) Configure input Qos policy
	// Configure input Qos policy
	// +kubebuilder:validation:Optional
	ServicePolicyQosInput *string `json:"servicePolicyQosInput,omitempty" tf:"service_policy_qos_input,omitempty"`

	// (String) Configure output Qos policy
	// Configure output Qos policy
	// +kubebuilder:validation:Optional
	ServicePolicyQosOutput *string `json:"servicePolicyQosOutput,omitempty" tf:"service_policy_qos_output,omitempty"`

	// (Number) SGT tag
	// SGT tag
	// - Range: `2`-`65519`
	// +kubebuilder:validation:Optional
	Sgt *float64 `json:"sgt,omitempty" tf:"sgt,omitempty"`

	// (Attributes List) tag name (see below for nested schema)
	// +kubebuilder:validation:Optional
	Tags []TagsParameters `json:"tags,omitempty" tf:"tags,omitempty"`

	// (String) tunnel profile name
	// tunnel profile name
	// +kubebuilder:validation:Optional
	TunnelCapwapName *string `json:"tunnelCapwapName,omitempty" tf:"tunnel_capwap_name,omitempty"`

	// (Number) Vlan to be applied
	// Vlan to be applied
	// - Range: `1`-`4094`
	// +kubebuilder:validation:Optional
	Vlan *float64 `json:"vlan,omitempty" tf:"vlan,omitempty"`

	// (String) Vnid to be applied
	// Vnid to be applied
	// +kubebuilder:validation:Optional
	Vnid *string `json:"vnid,omitempty" tf:"vnid,omitempty"`

	// (Boolean) Critical voice vlan
	// Critical voice vlan
	// +kubebuilder:validation:Optional
	VoiceVlan *bool `json:"voiceVlan,omitempty" tf:"voice_vlan,omitempty"`
}

type TagsInitParameters struct {

	// (String) Specify a template name (maximum 48 characters)
	// Specify the Tag name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type TagsObservation struct {

	// (String) Specify a template name (maximum 48 characters)
	// Specify the Tag name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type TagsParameters struct {

	// (String) Specify a template name (maximum 48 characters)
	// Specify the Tag name
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`
}

// ServiceTemplateSpec defines the desired state of ServiceTemplate
type ServiceTemplateSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   ServiceTemplateParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ServiceTemplateInitParameters `json:"initProvider,omitempty"`
}

// ServiceTemplateStatus defines the observed state of ServiceTemplate.
type ServiceTemplateStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ServiceTemplateObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ServiceTemplate is the Schema for the ServiceTemplates API. This resource can manage the Service Template configuration.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,iosxe}
type ServiceTemplate struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   ServiceTemplateSpec   `json:"spec"`
	Status ServiceTemplateStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ServiceTemplateList contains a list of ServiceTemplates
type ServiceTemplateList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ServiceTemplate `json:"items"`
}

// Repository type metadata.
var (
	ServiceTemplate_Kind             = "ServiceTemplate"
	ServiceTemplate_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ServiceTemplate_Kind}.String()
	ServiceTemplate_KindAPIVersion   = ServiceTemplate_Kind + "." + CRDGroupVersion.String()
	ServiceTemplate_GroupVersionKind = CRDGroupVersion.WithKind(ServiceTemplate_Kind)
)

func init() {
	SchemeBuilder.Register(&ServiceTemplate{}, &ServiceTemplateList{})
}
