// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type IPv4MetricLevelsInitParameters struct {

	// IS level (level-1 or level-2)
	// IS-IS level (level-1 or level-2)
	// - Choices: `level-1`, `level-2`
	Level *string `json:"level,omitempty" tf:"level,omitempty"`

	// 16777214)
	// Metric value (1-16777214)
	// - Range: `1`-`16777214`
	Value *float64 `json:"value,omitempty" tf:"value,omitempty"`
}

type IPv4MetricLevelsObservation struct {

	// IS level (level-1 or level-2)
	// IS-IS level (level-1 or level-2)
	// - Choices: `level-1`, `level-2`
	Level *string `json:"level,omitempty" tf:"level,omitempty"`

	// 16777214)
	// Metric value (1-16777214)
	// - Range: `1`-`16777214`
	Value *float64 `json:"value,omitempty" tf:"value,omitempty"`
}

type IPv4MetricLevelsParameters struct {

	// IS level (level-1 or level-2)
	// IS-IS level (level-1 or level-2)
	// - Choices: `level-1`, `level-2`
	// +kubebuilder:validation:Optional
	Level *string `json:"level" tf:"level,omitempty"`

	// 16777214)
	// Metric value (1-16777214)
	// - Range: `1`-`16777214`
	// +kubebuilder:validation:Optional
	Value *float64 `json:"value" tf:"value,omitempty"`
}

type ISISInitParameters struct {

	// is. Default value is all.
	// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is. Default value is `all`.
	// - Choices: `all`, `attributes`
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// IS metric for interface (see below for nested schema)
	IPv4MetricLevels []IPv4MetricLevelsInitParameters `json:"ipv4MetricLevels,omitempty" tf:"ipv4_metric_levels,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// to-point
	// Set ISIS network type to point-to-point
	NetworkPointToPoint *bool `json:"networkPointToPoint,omitempty" tf:"network_point_to_point,omitempty"`

	// (String) Interface type
	// Interface type
	// - Choices: `GigabitEthernet`, `TwoGigabitEthernet`, `FiveGigabitEthernet`, `TenGigabitEthernet`, `TwentyFiveGigE`, `FortyGigabitEthernet`, `FiftyGigabitEthernet`, `HundredGigE`, `TwoHundredGigE`, `FourHundredGigE`, `Loopback`, `Vlan`, `Port-channel`, `Port-channel-subinterface/Port-channel`, `Tunnel`
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ISISObservation struct {

	// is. Default value is all.
	// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is. Default value is `all`.
	// - Choices: `all`, `attributes`
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// (String) The path of the object.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// IS metric for interface (see below for nested schema)
	IPv4MetricLevels []IPv4MetricLevelsObservation `json:"ipv4MetricLevels,omitempty" tf:"ipv4_metric_levels,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// to-point
	// Set ISIS network type to point-to-point
	NetworkPointToPoint *bool `json:"networkPointToPoint,omitempty" tf:"network_point_to_point,omitempty"`

	// (String) Interface type
	// Interface type
	// - Choices: `GigabitEthernet`, `TwoGigabitEthernet`, `FiveGigabitEthernet`, `TenGigabitEthernet`, `TwentyFiveGigE`, `FortyGigabitEthernet`, `FiftyGigabitEthernet`, `HundredGigE`, `TwoHundredGigE`, `FourHundredGigE`, `Loopback`, `Vlan`, `Port-channel`, `Port-channel-subinterface/Port-channel`, `Tunnel`
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ISISParameters struct {

	// is. Default value is all.
	// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is. Default value is `all`.
	// - Choices: `all`, `attributes`
	// +kubebuilder:validation:Optional
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	// +kubebuilder:validation:Optional
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// IS metric for interface (see below for nested schema)
	// +kubebuilder:validation:Optional
	IPv4MetricLevels []IPv4MetricLevelsParameters `json:"ipv4MetricLevels,omitempty" tf:"ipv4_metric_levels,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// to-point
	// Set ISIS network type to point-to-point
	// +kubebuilder:validation:Optional
	NetworkPointToPoint *bool `json:"networkPointToPoint,omitempty" tf:"network_point_to_point,omitempty"`

	// (String) Interface type
	// Interface type
	// - Choices: `GigabitEthernet`, `TwoGigabitEthernet`, `FiveGigabitEthernet`, `TenGigabitEthernet`, `TwentyFiveGigE`, `FortyGigabitEthernet`, `FiftyGigabitEthernet`, `HundredGigE`, `TwoHundredGigE`, `FourHundredGigE`, `Loopback`, `Vlan`, `Port-channel`, `Port-channel-subinterface/Port-channel`, `Tunnel`
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

// ISISSpec defines the desired state of ISIS
type ISISSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ISISParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ISISInitParameters `json:"initProvider,omitempty"`
}

// ISISStatus defines the observed state of ISIS.
type ISISStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ISISObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ISIS is the Schema for the ISISs API. This resource can manage the Interface ISIS configuration.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,iosxe}
type ISIS struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	Spec   ISISSpec   `json:"spec"`
	Status ISISStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ISISList contains a list of ISISs
type ISISList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ISIS `json:"items"`
}

// Repository type metadata.
var (
	ISIS_Kind             = "ISIS"
	ISIS_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ISIS_Kind}.String()
	ISIS_KindAPIVersion   = ISIS_Kind + "." + CRDGroupVersion.String()
	ISIS_GroupVersionKind = CRDGroupVersion.WithKind(ISIS_Kind)
)

func init() {
	SchemeBuilder.Register(&ISIS{}, &ISISList{})
}
