// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type NVEInitParameters struct {

	// is. Default value is all.
	// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is. Default value is `all`.
	// - Choices: `all`, `attributes`
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// (String) Interface specific description
	// Interface specific description
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// (Boolean)
	HostReachabilityProtocolBGP *bool `json:"hostReachabilityProtocolBgp,omitempty" tf:"host_reachability_protocol_bgp,omitempty"`

	// Range: 1-4096
	//
	// - Range: `1`-`4096`
	Name *float64 `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) Shutdown the selected interface
	// Shutdown the selected interface
	Shutdown *bool `json:"shutdown,omitempty" tf:"shutdown,omitempty"`

	// (Number) Loopback interface
	// Loopback interface
	// - Range: `0`-`2147483647`
	SourceInterfaceLoopback *float64 `json:"sourceInterfaceLoopback,omitempty" tf:"source_interface_loopback,omitempty"`

	// (Attributes List) Configure VNI information (see below for nested schema)
	VniVrfs []VniVrfsInitParameters `json:"vniVrfs,omitempty" tf:"vni_vrfs,omitempty"`

	// (Attributes List) Configure VNI information (see below for nested schema)
	Vnis []VnisInitParameters `json:"vnis,omitempty" tf:"vnis,omitempty"`
}

type NVEObservation struct {

	// is. Default value is all.
	// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is. Default value is `all`.
	// - Choices: `all`, `attributes`
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// (String) Interface specific description
	// Interface specific description
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// (Boolean)
	HostReachabilityProtocolBGP *bool `json:"hostReachabilityProtocolBgp,omitempty" tf:"host_reachability_protocol_bgp,omitempty"`

	// (String) The path of the object.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Range: 1-4096
	//
	// - Range: `1`-`4096`
	Name *float64 `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) Shutdown the selected interface
	// Shutdown the selected interface
	Shutdown *bool `json:"shutdown,omitempty" tf:"shutdown,omitempty"`

	// (Number) Loopback interface
	// Loopback interface
	// - Range: `0`-`2147483647`
	SourceInterfaceLoopback *float64 `json:"sourceInterfaceLoopback,omitempty" tf:"source_interface_loopback,omitempty"`

	// (Attributes List) Configure VNI information (see below for nested schema)
	VniVrfs []VniVrfsObservation `json:"vniVrfs,omitempty" tf:"vni_vrfs,omitempty"`

	// (Attributes List) Configure VNI information (see below for nested schema)
	Vnis []VnisObservation `json:"vnis,omitempty" tf:"vnis,omitempty"`
}

type NVEParameters struct {

	// is. Default value is all.
	// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is. Default value is `all`.
	// - Choices: `all`, `attributes`
	// +kubebuilder:validation:Optional
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// (String) Interface specific description
	// Interface specific description
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	// +kubebuilder:validation:Optional
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	HostReachabilityProtocolBGP *bool `json:"hostReachabilityProtocolBgp,omitempty" tf:"host_reachability_protocol_bgp,omitempty"`

	// Range: 1-4096
	//
	// - Range: `1`-`4096`
	// +kubebuilder:validation:Optional
	Name *float64 `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) Shutdown the selected interface
	// Shutdown the selected interface
	// +kubebuilder:validation:Optional
	Shutdown *bool `json:"shutdown,omitempty" tf:"shutdown,omitempty"`

	// (Number) Loopback interface
	// Loopback interface
	// - Range: `0`-`2147483647`
	// +kubebuilder:validation:Optional
	SourceInterfaceLoopback *float64 `json:"sourceInterfaceLoopback,omitempty" tf:"source_interface_loopback,omitempty"`

	// (Attributes List) Configure VNI information (see below for nested schema)
	// +kubebuilder:validation:Optional
	VniVrfs []VniVrfsParameters `json:"vniVrfs,omitempty" tf:"vni_vrfs,omitempty"`

	// (Attributes List) Configure VNI information (see below for nested schema)
	// +kubebuilder:validation:Optional
	Vnis []VnisParameters `json:"vnis,omitempty" tf:"vnis,omitempty"`
}

type VniVrfsInitParameters struct {

	// 16777215, example: 6010-6030 or 7115
	// VNI range or instance between 4096-16777215, example: 6010-6030 or 7115
	VniRange *string `json:"vniRange,omitempty" tf:"vni_range,omitempty"`

	// (String) Specify a particular VRF
	// Specify a particular VRF
	Vrf *string `json:"vrf,omitempty" tf:"vrf,omitempty"`
}

type VniVrfsObservation struct {

	// 16777215, example: 6010-6030 or 7115
	// VNI range or instance between 4096-16777215, example: 6010-6030 or 7115
	VniRange *string `json:"vniRange,omitempty" tf:"vni_range,omitempty"`

	// (String) Specify a particular VRF
	// Specify a particular VRF
	Vrf *string `json:"vrf,omitempty" tf:"vrf,omitempty"`
}

type VniVrfsParameters struct {

	// 16777215, example: 6010-6030 or 7115
	// VNI range or instance between 4096-16777215, example: 6010-6030 or 7115
	// +kubebuilder:validation:Optional
	VniRange *string `json:"vniRange" tf:"vni_range,omitempty"`

	// (String) Specify a particular VRF
	// Specify a particular VRF
	// +kubebuilder:validation:Optional
	Vrf *string `json:"vrf,omitempty" tf:"vrf,omitempty"`
}

type VnisInitParameters struct {

	// (String) Starting Multicast Group IPv4 Address
	// Starting Multicast Group IPv4 Address
	IPv4MulticastGroup *string `json:"ipv4MulticastGroup,omitempty" tf:"ipv4_multicast_group,omitempty"`

	// plane (BGP) signaling
	// Ingress Replication control-plane (BGP) signaling
	IngressReplication *bool `json:"ingressReplication,omitempty" tf:"ingress_replication,omitempty"`

	// (Boolean) Enable vxlan centralized gateway forwarding for routed traffic
	// Enable vxlan centralized gateway forwarding for routed traffic
	LocalRouting *bool `json:"localRouting,omitempty" tf:"local_routing,omitempty"`

	// 16777215, example: 6010-6030 or 7115
	// VNI range or instance between 4096-16777215, example: 6010-6030 or 7115
	VniRange *string `json:"vniRange,omitempty" tf:"vni_range,omitempty"`
}

type VnisObservation struct {

	// (String) Starting Multicast Group IPv4 Address
	// Starting Multicast Group IPv4 Address
	IPv4MulticastGroup *string `json:"ipv4MulticastGroup,omitempty" tf:"ipv4_multicast_group,omitempty"`

	// plane (BGP) signaling
	// Ingress Replication control-plane (BGP) signaling
	IngressReplication *bool `json:"ingressReplication,omitempty" tf:"ingress_replication,omitempty"`

	// (Boolean) Enable vxlan centralized gateway forwarding for routed traffic
	// Enable vxlan centralized gateway forwarding for routed traffic
	LocalRouting *bool `json:"localRouting,omitempty" tf:"local_routing,omitempty"`

	// 16777215, example: 6010-6030 or 7115
	// VNI range or instance between 4096-16777215, example: 6010-6030 or 7115
	VniRange *string `json:"vniRange,omitempty" tf:"vni_range,omitempty"`
}

type VnisParameters struct {

	// (String) Starting Multicast Group IPv4 Address
	// Starting Multicast Group IPv4 Address
	// +kubebuilder:validation:Optional
	IPv4MulticastGroup *string `json:"ipv4MulticastGroup,omitempty" tf:"ipv4_multicast_group,omitempty"`

	// plane (BGP) signaling
	// Ingress Replication control-plane (BGP) signaling
	// +kubebuilder:validation:Optional
	IngressReplication *bool `json:"ingressReplication,omitempty" tf:"ingress_replication,omitempty"`

	// (Boolean) Enable vxlan centralized gateway forwarding for routed traffic
	// Enable vxlan centralized gateway forwarding for routed traffic
	// +kubebuilder:validation:Optional
	LocalRouting *bool `json:"localRouting,omitempty" tf:"local_routing,omitempty"`

	// 16777215, example: 6010-6030 or 7115
	// VNI range or instance between 4096-16777215, example: 6010-6030 or 7115
	// +kubebuilder:validation:Optional
	VniRange *string `json:"vniRange" tf:"vni_range,omitempty"`
}

// NVESpec defines the desired state of NVE
type NVESpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            NVEParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider NVEInitParameters `json:"initProvider,omitempty"`
}

// NVEStatus defines the observed state of NVE.
type NVEStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               NVEObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// NVE is the Schema for the NVEs API. This resource can manage the Interface NVE configuration.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,iosxe}
type NVE struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   NVESpec   `json:"spec"`
	Status NVEStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NVEList contains a list of NVEs
type NVEList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NVE `json:"items"`
}

// Repository type metadata.
var (
	NVE_Kind             = "NVE"
	NVE_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: NVE_Kind}.String()
	NVE_KindAPIVersion   = NVE_Kind + "." + CRDGroupVersion.String()
	NVE_GroupVersionKind = CRDGroupVersion.WithKind(NVE_Kind)
)

func init() {
	SchemeBuilder.Register(&NVE{}, &NVEList{})
}
