// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type SwitchportInitParameters struct {

	// (String)
	AccessVlan *string `json:"accessVlan,omitempty" tf:"access_vlan,omitempty"`

	// is. Default value is all.
	// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is. Default value is `all`.
	// - Choices: `all`, `attributes`
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// (Boolean) Set port host
	// Set port host
	Host *bool `json:"host,omitempty" tf:"host,omitempty"`

	// (Boolean) Set trunking mode to ACCESS unconditionally
	// Set trunking mode to ACCESS unconditionally
	ModeAccess *bool `json:"modeAccess,omitempty" tf:"mode_access,omitempty"`

	// (Boolean) set trunking mode to TUNNEL unconditionally
	// set trunking mode to TUNNEL unconditionally
	ModeDot1QTunnel *bool `json:"modeDot1QTunnel,omitempty" tf:"mode_dot1q_tunnel,omitempty"`

	// vlan host
	// Set the mode to private-vlan host
	ModePrivateVlanHost *bool `json:"modePrivateVlanHost,omitempty" tf:"mode_private_vlan_host,omitempty"`

	// vlan promiscuous
	// Set the mode to private-vlan promiscuous
	ModePrivateVlanPromiscuous *bool `json:"modePrivateVlanPromiscuous,omitempty" tf:"mode_private_vlan_promiscuous,omitempty"`

	// vlan trunk
	// Set the mode to private-vlan trunk
	ModePrivateVlanTrunk *bool `json:"modePrivateVlanTrunk,omitempty" tf:"mode_private_vlan_trunk,omitempty"`

	// (Boolean) Set trunking mode to TRUNK unconditionally
	// Set trunking mode to TRUNK unconditionally
	ModeTrunk *bool `json:"modeTrunk,omitempty" tf:"mode_trunk,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) Device will not engage in negotiation protocol on this interface
	// Device will not engage in negotiation protocol on this interface
	Nonegotiate *bool `json:"nonegotiate,omitempty" tf:"nonegotiate,omitempty"`

	// (String)
	TrunkAllowedVlans *string `json:"trunkAllowedVlans,omitempty" tf:"trunk_allowed_vlans,omitempty"`

	// (Attributes List) (see below for nested schema)
	TrunkAllowedVlansAdd []TrunkAllowedVlansAddInitParameters `json:"trunkAllowedVlansAdd,omitempty" tf:"trunk_allowed_vlans_add,omitempty"`

	// (Boolean) all VLANs
	// all VLANs
	TrunkAllowedVlansAll *bool `json:"trunkAllowedVlansAll,omitempty" tf:"trunk_allowed_vlans_all,omitempty"`

	// (String) all VLANs except the following
	// all VLANs except the following
	TrunkAllowedVlansExcept *string `json:"trunkAllowedVlansExcept,omitempty" tf:"trunk_allowed_vlans_except,omitempty"`

	// (String)
	TrunkAllowedVlansLegacy *string `json:"trunkAllowedVlansLegacy,omitempty" tf:"trunk_allowed_vlans_legacy,omitempty"`

	// (Boolean) no VLANs
	// no VLANs
	TrunkAllowedVlansNone *bool `json:"trunkAllowedVlansNone,omitempty" tf:"trunk_allowed_vlans_none,omitempty"`

	// (Boolean) no VLANs
	// no VLANs
	TrunkAllowedVlansNoneLegacy *bool `json:"trunkAllowedVlansNoneLegacy,omitempty" tf:"trunk_allowed_vlans_none_legacy,omitempty"`

	// (String) VLAN IDs of disallowed VLANs when this port is in trunking mode
	// VLAN IDs of disallowed VLANs when this port is in trunking mode
	TrunkAllowedVlansRemove *string `json:"trunkAllowedVlansRemove,omitempty" tf:"trunk_allowed_vlans_remove,omitempty"`

	// Range: 1-4094
	//
	// - Range: `1`-`4094`
	TrunkNativeVlan *float64 `json:"trunkNativeVlan,omitempty" tf:"trunk_native_vlan,omitempty"`

	// (Boolean)
	TrunkNativeVlanTag *bool `json:"trunkNativeVlanTag,omitempty" tf:"trunk_native_vlan_tag,omitempty"`

	// (String) Interface type
	// Interface type
	// - Choices: `GigabitEthernet`, `TwoGigabitEthernet`, `FiveGigabitEthernet`, `TenGigabitEthernet`, `TwentyFiveGigE`, `FortyGigabitEthernet`, `FiftyGigabitEthernet`, `HundredGigE`, `TwoHundredGigE`, `FourHundredGigE`, `Port-channel`
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String)
	VoiceVlan *string `json:"voiceVlan,omitempty" tf:"voice_vlan,omitempty"`
}

type SwitchportObservation struct {

	// (String)
	AccessVlan *string `json:"accessVlan,omitempty" tf:"access_vlan,omitempty"`

	// is. Default value is all.
	// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is. Default value is `all`.
	// - Choices: `all`, `attributes`
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// (Boolean) Set port host
	// Set port host
	Host *bool `json:"host,omitempty" tf:"host,omitempty"`

	// (String) The path of the object.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean) Set trunking mode to ACCESS unconditionally
	// Set trunking mode to ACCESS unconditionally
	ModeAccess *bool `json:"modeAccess,omitempty" tf:"mode_access,omitempty"`

	// (Boolean) set trunking mode to TUNNEL unconditionally
	// set trunking mode to TUNNEL unconditionally
	ModeDot1QTunnel *bool `json:"modeDot1QTunnel,omitempty" tf:"mode_dot1q_tunnel,omitempty"`

	// vlan host
	// Set the mode to private-vlan host
	ModePrivateVlanHost *bool `json:"modePrivateVlanHost,omitempty" tf:"mode_private_vlan_host,omitempty"`

	// vlan promiscuous
	// Set the mode to private-vlan promiscuous
	ModePrivateVlanPromiscuous *bool `json:"modePrivateVlanPromiscuous,omitempty" tf:"mode_private_vlan_promiscuous,omitempty"`

	// vlan trunk
	// Set the mode to private-vlan trunk
	ModePrivateVlanTrunk *bool `json:"modePrivateVlanTrunk,omitempty" tf:"mode_private_vlan_trunk,omitempty"`

	// (Boolean) Set trunking mode to TRUNK unconditionally
	// Set trunking mode to TRUNK unconditionally
	ModeTrunk *bool `json:"modeTrunk,omitempty" tf:"mode_trunk,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) Device will not engage in negotiation protocol on this interface
	// Device will not engage in negotiation protocol on this interface
	Nonegotiate *bool `json:"nonegotiate,omitempty" tf:"nonegotiate,omitempty"`

	// (String)
	TrunkAllowedVlans *string `json:"trunkAllowedVlans,omitempty" tf:"trunk_allowed_vlans,omitempty"`

	// (Attributes List) (see below for nested schema)
	TrunkAllowedVlansAdd []TrunkAllowedVlansAddObservation `json:"trunkAllowedVlansAdd,omitempty" tf:"trunk_allowed_vlans_add,omitempty"`

	// (Boolean) all VLANs
	// all VLANs
	TrunkAllowedVlansAll *bool `json:"trunkAllowedVlansAll,omitempty" tf:"trunk_allowed_vlans_all,omitempty"`

	// (String) all VLANs except the following
	// all VLANs except the following
	TrunkAllowedVlansExcept *string `json:"trunkAllowedVlansExcept,omitempty" tf:"trunk_allowed_vlans_except,omitempty"`

	// (String)
	TrunkAllowedVlansLegacy *string `json:"trunkAllowedVlansLegacy,omitempty" tf:"trunk_allowed_vlans_legacy,omitempty"`

	// (Boolean) no VLANs
	// no VLANs
	TrunkAllowedVlansNone *bool `json:"trunkAllowedVlansNone,omitempty" tf:"trunk_allowed_vlans_none,omitempty"`

	// (Boolean) no VLANs
	// no VLANs
	TrunkAllowedVlansNoneLegacy *bool `json:"trunkAllowedVlansNoneLegacy,omitempty" tf:"trunk_allowed_vlans_none_legacy,omitempty"`

	// (String) VLAN IDs of disallowed VLANs when this port is in trunking mode
	// VLAN IDs of disallowed VLANs when this port is in trunking mode
	TrunkAllowedVlansRemove *string `json:"trunkAllowedVlansRemove,omitempty" tf:"trunk_allowed_vlans_remove,omitempty"`

	// Range: 1-4094
	//
	// - Range: `1`-`4094`
	TrunkNativeVlan *float64 `json:"trunkNativeVlan,omitempty" tf:"trunk_native_vlan,omitempty"`

	// (Boolean)
	TrunkNativeVlanTag *bool `json:"trunkNativeVlanTag,omitempty" tf:"trunk_native_vlan_tag,omitempty"`

	// (String) Interface type
	// Interface type
	// - Choices: `GigabitEthernet`, `TwoGigabitEthernet`, `FiveGigabitEthernet`, `TenGigabitEthernet`, `TwentyFiveGigE`, `FortyGigabitEthernet`, `FiftyGigabitEthernet`, `HundredGigE`, `TwoHundredGigE`, `FourHundredGigE`, `Port-channel`
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String)
	VoiceVlan *string `json:"voiceVlan,omitempty" tf:"voice_vlan,omitempty"`
}

type SwitchportParameters struct {

	// (String)
	// +kubebuilder:validation:Optional
	AccessVlan *string `json:"accessVlan,omitempty" tf:"access_vlan,omitempty"`

	// is. Default value is all.
	// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is. Default value is `all`.
	// - Choices: `all`, `attributes`
	// +kubebuilder:validation:Optional
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	// +kubebuilder:validation:Optional
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// (Boolean) Set port host
	// Set port host
	// +kubebuilder:validation:Optional
	Host *bool `json:"host,omitempty" tf:"host,omitempty"`

	// (Boolean) Set trunking mode to ACCESS unconditionally
	// Set trunking mode to ACCESS unconditionally
	// +kubebuilder:validation:Optional
	ModeAccess *bool `json:"modeAccess,omitempty" tf:"mode_access,omitempty"`

	// (Boolean) set trunking mode to TUNNEL unconditionally
	// set trunking mode to TUNNEL unconditionally
	// +kubebuilder:validation:Optional
	ModeDot1QTunnel *bool `json:"modeDot1QTunnel,omitempty" tf:"mode_dot1q_tunnel,omitempty"`

	// vlan host
	// Set the mode to private-vlan host
	// +kubebuilder:validation:Optional
	ModePrivateVlanHost *bool `json:"modePrivateVlanHost,omitempty" tf:"mode_private_vlan_host,omitempty"`

	// vlan promiscuous
	// Set the mode to private-vlan promiscuous
	// +kubebuilder:validation:Optional
	ModePrivateVlanPromiscuous *bool `json:"modePrivateVlanPromiscuous,omitempty" tf:"mode_private_vlan_promiscuous,omitempty"`

	// vlan trunk
	// Set the mode to private-vlan trunk
	// +kubebuilder:validation:Optional
	ModePrivateVlanTrunk *bool `json:"modePrivateVlanTrunk,omitempty" tf:"mode_private_vlan_trunk,omitempty"`

	// (Boolean) Set trunking mode to TRUNK unconditionally
	// Set trunking mode to TRUNK unconditionally
	// +kubebuilder:validation:Optional
	ModeTrunk *bool `json:"modeTrunk,omitempty" tf:"mode_trunk,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) Device will not engage in negotiation protocol on this interface
	// Device will not engage in negotiation protocol on this interface
	// +kubebuilder:validation:Optional
	Nonegotiate *bool `json:"nonegotiate,omitempty" tf:"nonegotiate,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	TrunkAllowedVlans *string `json:"trunkAllowedVlans,omitempty" tf:"trunk_allowed_vlans,omitempty"`

	// (Attributes List) (see below for nested schema)
	// +kubebuilder:validation:Optional
	TrunkAllowedVlansAdd []TrunkAllowedVlansAddParameters `json:"trunkAllowedVlansAdd,omitempty" tf:"trunk_allowed_vlans_add,omitempty"`

	// (Boolean) all VLANs
	// all VLANs
	// +kubebuilder:validation:Optional
	TrunkAllowedVlansAll *bool `json:"trunkAllowedVlansAll,omitempty" tf:"trunk_allowed_vlans_all,omitempty"`

	// (String) all VLANs except the following
	// all VLANs except the following
	// +kubebuilder:validation:Optional
	TrunkAllowedVlansExcept *string `json:"trunkAllowedVlansExcept,omitempty" tf:"trunk_allowed_vlans_except,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	TrunkAllowedVlansLegacy *string `json:"trunkAllowedVlansLegacy,omitempty" tf:"trunk_allowed_vlans_legacy,omitempty"`

	// (Boolean) no VLANs
	// no VLANs
	// +kubebuilder:validation:Optional
	TrunkAllowedVlansNone *bool `json:"trunkAllowedVlansNone,omitempty" tf:"trunk_allowed_vlans_none,omitempty"`

	// (Boolean) no VLANs
	// no VLANs
	// +kubebuilder:validation:Optional
	TrunkAllowedVlansNoneLegacy *bool `json:"trunkAllowedVlansNoneLegacy,omitempty" tf:"trunk_allowed_vlans_none_legacy,omitempty"`

	// (String) VLAN IDs of disallowed VLANs when this port is in trunking mode
	// VLAN IDs of disallowed VLANs when this port is in trunking mode
	// +kubebuilder:validation:Optional
	TrunkAllowedVlansRemove *string `json:"trunkAllowedVlansRemove,omitempty" tf:"trunk_allowed_vlans_remove,omitempty"`

	// Range: 1-4094
	//
	// - Range: `1`-`4094`
	// +kubebuilder:validation:Optional
	TrunkNativeVlan *float64 `json:"trunkNativeVlan,omitempty" tf:"trunk_native_vlan,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	TrunkNativeVlanTag *bool `json:"trunkNativeVlanTag,omitempty" tf:"trunk_native_vlan_tag,omitempty"`

	// (String) Interface type
	// Interface type
	// - Choices: `GigabitEthernet`, `TwoGigabitEthernet`, `FiveGigabitEthernet`, `TenGigabitEthernet`, `TwentyFiveGigE`, `FortyGigabitEthernet`, `FiftyGigabitEthernet`, `HundredGigE`, `TwoHundredGigE`, `FourHundredGigE`, `Port-channel`
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	VoiceVlan *string `json:"voiceVlan,omitempty" tf:"voice_vlan,omitempty"`
}

type TrunkAllowedVlansAddInitParameters struct {

	// (String)
	Vlans *string `json:"vlans,omitempty" tf:"vlans,omitempty"`
}

type TrunkAllowedVlansAddObservation struct {

	// (String)
	Vlans *string `json:"vlans,omitempty" tf:"vlans,omitempty"`
}

type TrunkAllowedVlansAddParameters struct {

	// (String)
	// +kubebuilder:validation:Optional
	Vlans *string `json:"vlans" tf:"vlans,omitempty"`
}

// SwitchportSpec defines the desired state of Switchport
type SwitchportSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            SwitchportParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SwitchportInitParameters `json:"initProvider,omitempty"`
}

// SwitchportStatus defines the observed state of Switchport.
type SwitchportStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               SwitchportObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Switchport is the Schema for the Switchports API. This resource can manage the Interface Switchport configuration.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,iosxe}
type Switchport struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	Spec   SwitchportSpec   `json:"spec"`
	Status SwitchportStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SwitchportList contains a list of Switchports
type SwitchportList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Switchport `json:"items"`
}

// Repository type metadata.
var (
	Switchport_Kind             = "Switchport"
	Switchport_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Switchport_Kind}.String()
	Switchport_KindAPIVersion   = Switchport_Kind + "." + CRDGroupVersion.String()
	Switchport_GroupVersionKind = CRDGroupVersion.WithKind(Switchport_Kind)
)

func init() {
	SchemeBuilder.Register(&Switchport{}, &SwitchportList{})
}
