apiVersion: bgp.iosxe.upbound.io/v1alpha1
kind: AddressFamilyIPv4VRF
metadata:
  annotations:
    meta.upbound.io/example-id: bgp/v1alpha1/addressfamilyipv4vrf
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    afName: unicast
    asnSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    vrfs:
    - ipv4UnicastAdminDistances:
      - distance: 200
        sourceIp: 10.1.1.1
        wildcard: 0.0.0.0
      ipv4UnicastAdvertiseL2VpnEvpn: true
      ipv4UnicastAggregateAddresses:
      - ipv4Address: 50.0.0.0
        ipv4Mask: 255.255.0.0
        summaryOnly: true
      ipv4UnicastDistanceBgpExternal: 20
      ipv4UnicastDistanceBgpInternal: 200
      ipv4UnicastDistanceBgpLocal: 200
      ipv4UnicastImportPathSelectionAll: true
      ipv4UnicastMaximumPathsEbgp: 2
      ipv4UnicastMaximumPathsIbgp: 2
      ipv4UnicastNetworks:
      - backdoor: true
        network: 13.0.0.0
        routeMap: RM1
      ipv4UnicastNetworksMask:
      - backdoor: true
        mask: 255.255.0.0
        network: 12.0.0.0
        routeMap: RM1
      ipv4UnicastRedistributeConnected: true
      ipv4UnicastRedistributeConnectedMetric: 100
      ipv4UnicastRedistributeConnectedRouteMap: RM_BGP_CONNECTED
      ipv4UnicastRedistributeStatic: true
      ipv4UnicastRedistributeStaticMetric: 200
      ipv4UnicastRedistributeStaticRouteMap: RM_BGP_STATIC
      ipv4UnicastRouterIdLoopback: 101
      name: VRF1
