apiVersion: bgp.iosxe.upbound.io/v1alpha1
kind: AddressFamilyIPv6
metadata:
  annotations:
    meta.upbound.io/example-id: bgp/v1alpha1/addressfamilyipv6
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    afName: unicast
    asnSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    ipv6UnicastAdminDistances:
    - distance: 200
      sourceIpv6Address: 2001:DB8::/48
    ipv6UnicastAggregateAddresses:
    - ipv6Address: 2001:DB8::/32
    ipv6UnicastDistanceBgpExternal: 20
    ipv6UnicastDistanceBgpInternal: 200
    ipv6UnicastDistanceBgpLocal: 200
    ipv6UnicastMaximumPathsEbgp: 2
    ipv6UnicastMaximumPathsIbgp: 2
    ipv6UnicastNetworks:
    - backdoor: true
      network: 2001:1234::/64
      routeMap: RM1
    ipv6UnicastRedistributeConnected: true
    ipv6UnicastRedistributeConnectedMetric: 100
    ipv6UnicastRedistributeConnectedRouteMap: RM_BGP6_CONNECTED
    ipv6UnicastRedistributeStatic: true
    ipv6UnicastRedistributeStaticMetric: 200
    ipv6UnicastRedistributeStaticRouteMap: RM_BGP6_STATIC
