apiVersion: bgp.iosxe.upbound.io/v1alpha1
kind: L2VPNEVPNNeighbor
metadata:
  annotations:
    meta.upbound.io/example-id: bgp/v1alpha1/l2vpnevpnneighbor
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    activate: true
    asnSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    inheritPeerPolicy: PEER_POLICY_TEMPLATE_1
    ip: 3.3.3.3
    routeMaps:
    - inOut: in
      routeMapName: RM1
    routeReflectorClient: false
    sendCommunity: both
    softReconfiguration: inbound
