// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type VTPInitParameters struct {

	// is. Default value is all.
	// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is. Default value is `all`.
	// - Choices: `all`, `attributes`
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// (String) Set the name of the VTP administrative domain.
	// Set the name of the VTP administrative domain.
	Domain *string `json:"domain,omitempty" tf:"domain,omitempty"`

	// (String) Configure IFS filesystem file where VTP configuration is stored.
	// Configure IFS filesystem file where VTP configuration is stored.
	File *string `json:"file,omitempty" tf:"file,omitempty"`

	// (String) The name of the interface providing the VTP updater ID for this device
	// The name of the interface providing the VTP updater ID for this device
	Interface *string `json:"interface,omitempty" tf:"interface,omitempty"`

	// (Boolean) Use only this interface's IP address as the VTP IP updater address
	// Use only this interface's IP address as the VTP IP updater address
	InterfaceOnly *bool `json:"interfaceOnly,omitempty" tf:"interface_only,omitempty"`

	// (Boolean) Set the device to client mode
	// Set the device to client mode
	ModeClient *bool `json:"modeClient,omitempty" tf:"mode_client,omitempty"`

	// (Boolean) Set the mode for MST VTP instance
	// Set the mode for MST VTP instance
	ModeClientMst *bool `json:"modeClientMst,omitempty" tf:"mode_client_mst,omitempty"`

	// (Boolean) Set the mode for unknown VTP instances
	// Set the mode for unknown VTP instances
	ModeClientUnknown *bool `json:"modeClientUnknown,omitempty" tf:"mode_client_unknown,omitempty"`

	// (Boolean) Set the mode for VLAN VTP instance
	// Set the mode for VLAN VTP instance
	ModeClientVlan *bool `json:"modeClientVlan,omitempty" tf:"mode_client_vlan,omitempty"`

	// (Boolean) Set the device to off mode
	// Set the device to off mode
	ModeOff *bool `json:"modeOff,omitempty" tf:"mode_off,omitempty"`

	// (Boolean) Set the mode for MST VTP instance
	// Set the mode for MST VTP instance
	ModeOffMst *bool `json:"modeOffMst,omitempty" tf:"mode_off_mst,omitempty"`

	// (Boolean) Set the mode for unknown VTP instances
	// Set the mode for unknown VTP instances
	ModeOffUnknown *bool `json:"modeOffUnknown,omitempty" tf:"mode_off_unknown,omitempty"`

	// (Boolean) Set the mode for VLAN VTP instance
	// Set the mode for VLAN VTP instance
	ModeOffVlan *bool `json:"modeOffVlan,omitempty" tf:"mode_off_vlan,omitempty"`

	// (Boolean) Set the device to server mode
	// Set the device to server mode
	ModeServer *bool `json:"modeServer,omitempty" tf:"mode_server,omitempty"`

	// (Boolean) Set the mode for MST VTP instance
	// Set the mode for MST VTP instance
	ModeServerMst *bool `json:"modeServerMst,omitempty" tf:"mode_server_mst,omitempty"`

	// (Boolean) Set the mode for unknown VTP instances
	// Set the mode for unknown VTP instances
	ModeServerUnknown *bool `json:"modeServerUnknown,omitempty" tf:"mode_server_unknown,omitempty"`

	// (Boolean) Set the mode for VLAN VTP instance
	// Set the mode for VLAN VTP instance
	ModeServerVlan *bool `json:"modeServerVlan,omitempty" tf:"mode_server_vlan,omitempty"`

	// (Boolean) Set the device to transparent mode
	// Set the device to transparent mode
	ModeTransparent *bool `json:"modeTransparent,omitempty" tf:"mode_transparent,omitempty"`

	// (Boolean) Set the mode for MST VTP instance
	// Set the mode for MST VTP instance
	ModeTransparentMst *bool `json:"modeTransparentMst,omitempty" tf:"mode_transparent_mst,omitempty"`

	// (Boolean) Set the mode for unknown VTP instances
	// Set the mode for unknown VTP instances
	ModeTransparentUnknown *bool `json:"modeTransparentUnknown,omitempty" tf:"mode_transparent_unknown,omitempty"`

	// (Boolean) Set the mode for VLAN VTP instance
	// Set the mode for VLAN VTP instance
	ModeTransparentVlan *bool `json:"modeTransparentVlan,omitempty" tf:"mode_transparent_vlan,omitempty"`

	// (Boolean) Set the VTP password hidden option
	// Set the VTP password hidden option
	PasswordHidden *bool `json:"passwordHidden,omitempty" tf:"password_hidden,omitempty"`

	// (Boolean, Sensitive) Specify the vtp password in encrypted form
	// Specify the vtp password in encrypted form
	PasswordSecret *bool `json:"passwordSecret,omitempty" tf:"password_secret,omitempty"`

	// (String, Sensitive) The ascii password for the VTP administrative domain
	// The ascii password for the VTP administrative domain
	PasswordSecretRef *v2.LocalSecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// only) The write-only value of the attribute.
	// The write-only value of the attribute.
	PasswordSecretWo *string `json:"passwordSecretWo,omitempty" tf:"password_secret_wo,omitempty"`

	// only version of the attribute.
	// The write-only version of the attribute.
	PasswordSecretWoVersion *float64 `json:"passwordSecretWoVersion,omitempty" tf:"password_secret_wo_version,omitempty"`

	// only) The write-only value of the attribute.
	// The write-only value of the attribute.
	PasswordWo *string `json:"passwordWo,omitempty" tf:"password_wo,omitempty"`

	// only version of the attribute.
	// The write-only version of the attribute.
	PasswordWoVersion *float64 `json:"passwordWoVersion,omitempty" tf:"password_wo_version,omitempty"`

	// (Boolean) Set the administrative domain to permit pruning
	// Set the administrative domain to permit pruning
	Pruning *bool `json:"pruning,omitempty" tf:"pruning,omitempty"`

	// (Number) Set the administrative domain to VTP version
	// Set the administrative domain to VTP version
	// - Range: `1`-`3`
	Version *float64 `json:"version,omitempty" tf:"version,omitempty"`
}

type VTPObservation struct {

	// is. Default value is all.
	// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is. Default value is `all`.
	// - Choices: `all`, `attributes`
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// (String) Set the name of the VTP administrative domain.
	// Set the name of the VTP administrative domain.
	Domain *string `json:"domain,omitempty" tf:"domain,omitempty"`

	// (String) Configure IFS filesystem file where VTP configuration is stored.
	// Configure IFS filesystem file where VTP configuration is stored.
	File *string `json:"file,omitempty" tf:"file,omitempty"`

	// (String) The path of the object.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The name of the interface providing the VTP updater ID for this device
	// The name of the interface providing the VTP updater ID for this device
	Interface *string `json:"interface,omitempty" tf:"interface,omitempty"`

	// (Boolean) Use only this interface's IP address as the VTP IP updater address
	// Use only this interface's IP address as the VTP IP updater address
	InterfaceOnly *bool `json:"interfaceOnly,omitempty" tf:"interface_only,omitempty"`

	// (Boolean) Set the device to client mode
	// Set the device to client mode
	ModeClient *bool `json:"modeClient,omitempty" tf:"mode_client,omitempty"`

	// (Boolean) Set the mode for MST VTP instance
	// Set the mode for MST VTP instance
	ModeClientMst *bool `json:"modeClientMst,omitempty" tf:"mode_client_mst,omitempty"`

	// (Boolean) Set the mode for unknown VTP instances
	// Set the mode for unknown VTP instances
	ModeClientUnknown *bool `json:"modeClientUnknown,omitempty" tf:"mode_client_unknown,omitempty"`

	// (Boolean) Set the mode for VLAN VTP instance
	// Set the mode for VLAN VTP instance
	ModeClientVlan *bool `json:"modeClientVlan,omitempty" tf:"mode_client_vlan,omitempty"`

	// (Boolean) Set the device to off mode
	// Set the device to off mode
	ModeOff *bool `json:"modeOff,omitempty" tf:"mode_off,omitempty"`

	// (Boolean) Set the mode for MST VTP instance
	// Set the mode for MST VTP instance
	ModeOffMst *bool `json:"modeOffMst,omitempty" tf:"mode_off_mst,omitempty"`

	// (Boolean) Set the mode for unknown VTP instances
	// Set the mode for unknown VTP instances
	ModeOffUnknown *bool `json:"modeOffUnknown,omitempty" tf:"mode_off_unknown,omitempty"`

	// (Boolean) Set the mode for VLAN VTP instance
	// Set the mode for VLAN VTP instance
	ModeOffVlan *bool `json:"modeOffVlan,omitempty" tf:"mode_off_vlan,omitempty"`

	// (Boolean) Set the device to server mode
	// Set the device to server mode
	ModeServer *bool `json:"modeServer,omitempty" tf:"mode_server,omitempty"`

	// (Boolean) Set the mode for MST VTP instance
	// Set the mode for MST VTP instance
	ModeServerMst *bool `json:"modeServerMst,omitempty" tf:"mode_server_mst,omitempty"`

	// (Boolean) Set the mode for unknown VTP instances
	// Set the mode for unknown VTP instances
	ModeServerUnknown *bool `json:"modeServerUnknown,omitempty" tf:"mode_server_unknown,omitempty"`

	// (Boolean) Set the mode for VLAN VTP instance
	// Set the mode for VLAN VTP instance
	ModeServerVlan *bool `json:"modeServerVlan,omitempty" tf:"mode_server_vlan,omitempty"`

	// (Boolean) Set the device to transparent mode
	// Set the device to transparent mode
	ModeTransparent *bool `json:"modeTransparent,omitempty" tf:"mode_transparent,omitempty"`

	// (Boolean) Set the mode for MST VTP instance
	// Set the mode for MST VTP instance
	ModeTransparentMst *bool `json:"modeTransparentMst,omitempty" tf:"mode_transparent_mst,omitempty"`

	// (Boolean) Set the mode for unknown VTP instances
	// Set the mode for unknown VTP instances
	ModeTransparentUnknown *bool `json:"modeTransparentUnknown,omitempty" tf:"mode_transparent_unknown,omitempty"`

	// (Boolean) Set the mode for VLAN VTP instance
	// Set the mode for VLAN VTP instance
	ModeTransparentVlan *bool `json:"modeTransparentVlan,omitempty" tf:"mode_transparent_vlan,omitempty"`

	// (Boolean) Set the VTP password hidden option
	// Set the VTP password hidden option
	PasswordHidden *bool `json:"passwordHidden,omitempty" tf:"password_hidden,omitempty"`

	// (Boolean, Sensitive) Specify the vtp password in encrypted form
	// Specify the vtp password in encrypted form
	PasswordSecret *bool `json:"passwordSecret,omitempty" tf:"password_secret,omitempty"`

	// only) The write-only value of the attribute.
	// The write-only value of the attribute.
	PasswordSecretWo *string `json:"passwordSecretWo,omitempty" tf:"password_secret_wo,omitempty"`

	// only version of the attribute.
	// The write-only version of the attribute.
	PasswordSecretWoVersion *float64 `json:"passwordSecretWoVersion,omitempty" tf:"password_secret_wo_version,omitempty"`

	// only) The write-only value of the attribute.
	// The write-only value of the attribute.
	PasswordWo *string `json:"passwordWo,omitempty" tf:"password_wo,omitempty"`

	// only version of the attribute.
	// The write-only version of the attribute.
	PasswordWoVersion *float64 `json:"passwordWoVersion,omitempty" tf:"password_wo_version,omitempty"`

	// (Boolean) Set the administrative domain to permit pruning
	// Set the administrative domain to permit pruning
	Pruning *bool `json:"pruning,omitempty" tf:"pruning,omitempty"`

	// (Number) Set the administrative domain to VTP version
	// Set the administrative domain to VTP version
	// - Range: `1`-`3`
	Version *float64 `json:"version,omitempty" tf:"version,omitempty"`
}

type VTPParameters struct {

	// is. Default value is all.
	// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is. Default value is `all`.
	// - Choices: `all`, `attributes`
	// +kubebuilder:validation:Optional
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	// +kubebuilder:validation:Optional
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// (String) Set the name of the VTP administrative domain.
	// Set the name of the VTP administrative domain.
	// +kubebuilder:validation:Optional
	Domain *string `json:"domain,omitempty" tf:"domain,omitempty"`

	// (String) Configure IFS filesystem file where VTP configuration is stored.
	// Configure IFS filesystem file where VTP configuration is stored.
	// +kubebuilder:validation:Optional
	File *string `json:"file,omitempty" tf:"file,omitempty"`

	// (String) The name of the interface providing the VTP updater ID for this device
	// The name of the interface providing the VTP updater ID for this device
	// +kubebuilder:validation:Optional
	Interface *string `json:"interface,omitempty" tf:"interface,omitempty"`

	// (Boolean) Use only this interface's IP address as the VTP IP updater address
	// Use only this interface's IP address as the VTP IP updater address
	// +kubebuilder:validation:Optional
	InterfaceOnly *bool `json:"interfaceOnly,omitempty" tf:"interface_only,omitempty"`

	// (Boolean) Set the device to client mode
	// Set the device to client mode
	// +kubebuilder:validation:Optional
	ModeClient *bool `json:"modeClient,omitempty" tf:"mode_client,omitempty"`

	// (Boolean) Set the mode for MST VTP instance
	// Set the mode for MST VTP instance
	// +kubebuilder:validation:Optional
	ModeClientMst *bool `json:"modeClientMst,omitempty" tf:"mode_client_mst,omitempty"`

	// (Boolean) Set the mode for unknown VTP instances
	// Set the mode for unknown VTP instances
	// +kubebuilder:validation:Optional
	ModeClientUnknown *bool `json:"modeClientUnknown,omitempty" tf:"mode_client_unknown,omitempty"`

	// (Boolean) Set the mode for VLAN VTP instance
	// Set the mode for VLAN VTP instance
	// +kubebuilder:validation:Optional
	ModeClientVlan *bool `json:"modeClientVlan,omitempty" tf:"mode_client_vlan,omitempty"`

	// (Boolean) Set the device to off mode
	// Set the device to off mode
	// +kubebuilder:validation:Optional
	ModeOff *bool `json:"modeOff,omitempty" tf:"mode_off,omitempty"`

	// (Boolean) Set the mode for MST VTP instance
	// Set the mode for MST VTP instance
	// +kubebuilder:validation:Optional
	ModeOffMst *bool `json:"modeOffMst,omitempty" tf:"mode_off_mst,omitempty"`

	// (Boolean) Set the mode for unknown VTP instances
	// Set the mode for unknown VTP instances
	// +kubebuilder:validation:Optional
	ModeOffUnknown *bool `json:"modeOffUnknown,omitempty" tf:"mode_off_unknown,omitempty"`

	// (Boolean) Set the mode for VLAN VTP instance
	// Set the mode for VLAN VTP instance
	// +kubebuilder:validation:Optional
	ModeOffVlan *bool `json:"modeOffVlan,omitempty" tf:"mode_off_vlan,omitempty"`

	// (Boolean) Set the device to server mode
	// Set the device to server mode
	// +kubebuilder:validation:Optional
	ModeServer *bool `json:"modeServer,omitempty" tf:"mode_server,omitempty"`

	// (Boolean) Set the mode for MST VTP instance
	// Set the mode for MST VTP instance
	// +kubebuilder:validation:Optional
	ModeServerMst *bool `json:"modeServerMst,omitempty" tf:"mode_server_mst,omitempty"`

	// (Boolean) Set the mode for unknown VTP instances
	// Set the mode for unknown VTP instances
	// +kubebuilder:validation:Optional
	ModeServerUnknown *bool `json:"modeServerUnknown,omitempty" tf:"mode_server_unknown,omitempty"`

	// (Boolean) Set the mode for VLAN VTP instance
	// Set the mode for VLAN VTP instance
	// +kubebuilder:validation:Optional
	ModeServerVlan *bool `json:"modeServerVlan,omitempty" tf:"mode_server_vlan,omitempty"`

	// (Boolean) Set the device to transparent mode
	// Set the device to transparent mode
	// +kubebuilder:validation:Optional
	ModeTransparent *bool `json:"modeTransparent,omitempty" tf:"mode_transparent,omitempty"`

	// (Boolean) Set the mode for MST VTP instance
	// Set the mode for MST VTP instance
	// +kubebuilder:validation:Optional
	ModeTransparentMst *bool `json:"modeTransparentMst,omitempty" tf:"mode_transparent_mst,omitempty"`

	// (Boolean) Set the mode for unknown VTP instances
	// Set the mode for unknown VTP instances
	// +kubebuilder:validation:Optional
	ModeTransparentUnknown *bool `json:"modeTransparentUnknown,omitempty" tf:"mode_transparent_unknown,omitempty"`

	// (Boolean) Set the mode for VLAN VTP instance
	// Set the mode for VLAN VTP instance
	// +kubebuilder:validation:Optional
	ModeTransparentVlan *bool `json:"modeTransparentVlan,omitempty" tf:"mode_transparent_vlan,omitempty"`

	// (Boolean) Set the VTP password hidden option
	// Set the VTP password hidden option
	// +kubebuilder:validation:Optional
	PasswordHidden *bool `json:"passwordHidden,omitempty" tf:"password_hidden,omitempty"`

	// (Boolean, Sensitive) Specify the vtp password in encrypted form
	// Specify the vtp password in encrypted form
	// +kubebuilder:validation:Optional
	PasswordSecret *bool `json:"passwordSecret,omitempty" tf:"password_secret,omitempty"`

	// (String, Sensitive) The ascii password for the VTP administrative domain
	// The ascii password for the VTP administrative domain
	// +kubebuilder:validation:Optional
	PasswordSecretRef *v2.LocalSecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// only) The write-only value of the attribute.
	// The write-only value of the attribute.
	// +kubebuilder:validation:Optional
	PasswordSecretWo *string `json:"passwordSecretWo,omitempty" tf:"password_secret_wo,omitempty"`

	// only version of the attribute.
	// The write-only version of the attribute.
	// +kubebuilder:validation:Optional
	PasswordSecretWoVersion *float64 `json:"passwordSecretWoVersion,omitempty" tf:"password_secret_wo_version,omitempty"`

	// only) The write-only value of the attribute.
	// The write-only value of the attribute.
	// +kubebuilder:validation:Optional
	PasswordWo *string `json:"passwordWo,omitempty" tf:"password_wo,omitempty"`

	// only version of the attribute.
	// The write-only version of the attribute.
	// +kubebuilder:validation:Optional
	PasswordWoVersion *float64 `json:"passwordWoVersion,omitempty" tf:"password_wo_version,omitempty"`

	// (Boolean) Set the administrative domain to permit pruning
	// Set the administrative domain to permit pruning
	// +kubebuilder:validation:Optional
	Pruning *bool `json:"pruning,omitempty" tf:"pruning,omitempty"`

	// (Number) Set the administrative domain to VTP version
	// Set the administrative domain to VTP version
	// - Range: `1`-`3`
	// +kubebuilder:validation:Optional
	Version *float64 `json:"version,omitempty" tf:"version,omitempty"`
}

// VTPSpec defines the desired state of VTP
type VTPSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            VTPParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider VTPInitParameters `json:"initProvider,omitempty"`
}

// VTPStatus defines the observed state of VTP.
type VTPStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               VTPObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// VTP is the Schema for the VTPs API. This resource can manage the VTP configuration.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,iosxe}
type VTP struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              VTPSpec   `json:"spec"`
	Status            VTPStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// VTPList contains a list of VTPs
type VTPList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []VTP `json:"items"`
}

// Repository type metadata.
var (
	VTP_Kind             = "VTP"
	VTP_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: VTP_Kind}.String()
	VTP_KindAPIVersion   = VTP_Kind + "." + CRDGroupVersion.String()
	VTP_GroupVersionKind = CRDGroupVersion.WithKind(VTP_Kind)
)

func init() {
	SchemeBuilder.Register(&VTP{}, &VTPList{})
}
