// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type AddressFamilyIPv6InitParameters struct {

	// Choices: flowspec, mdt, multicast, mvpn, unicast
	//
	// - Choices: `flowspec`, `mdt`, `multicast`, `mvpn`, `unicast`
	AfName *string `json:"afName,omitempty" tf:"af_name,omitempty"`

	// (String)
	// +crossplane:generate:reference:type=github.com/upbound/provider-upjet-iosxe/apis/namespaced/bgp/v1alpha1.BGP
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("asn",false)
	Asn *string `json:"asn,omitempty" tf:"asn,omitempty"`

	// Reference to a BGP in bgp to populate asn.
	// +kubebuilder:validation:Optional
	AsnRef *v2.NamespacedReference `json:"asnRef,omitempty" tf:"-"`

	// Selector for a BGP in bgp to populate asn.
	// +kubebuilder:validation:Optional
	AsnSelector *v2.NamespacedSelector `json:"asnSelector,omitempty" tf:"-"`

	// is. Default value is all.
	// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is. Default value is `all`.
	// - Choices: `all`, `attributes`
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// (Attributes List) (see below for nested schema)
	IPv6UnicastAdminDistances []IPv6UnicastAdminDistancesInitParameters `json:"ipv6UnicastAdminDistances,omitempty" tf:"ipv6_unicast_admin_distances,omitempty"`

	// (Attributes List) Configure BGP aggregate entries (see below for nested schema)
	IPv6UnicastAggregateAddresses []IPv6UnicastAggregateAddressesInitParameters `json:"ipv6UnicastAggregateAddresses,omitempty" tf:"ipv6_unicast_aggregate_addresses,omitempty"`

	// (Number) Distance for routes external to the AS
	// Distance for routes external to the AS
	// - Range: `1`-`255`
	IPv6UnicastDistanceBGPExternal *float64 `json:"ipv6UnicastDistanceBgpExternal,omitempty" tf:"ipv6_unicast_distance_bgp_external,omitempty"`

	// (Number) Distance for routes internal to the AS
	// Distance for routes internal to the AS
	// - Range: `1`-`255`
	IPv6UnicastDistanceBGPInternal *float64 `json:"ipv6UnicastDistanceBgpInternal,omitempty" tf:"ipv6_unicast_distance_bgp_internal,omitempty"`

	// (Number) Distance for local routes
	// Distance for local routes
	// - Range: `1`-`255`
	IPv6UnicastDistanceBGPLocal *float64 `json:"ipv6UnicastDistanceBgpLocal,omitempty" tf:"ipv6_unicast_distance_bgp_local,omitempty"`

	// multipath
	// eBGP-multipath
	// - Range: `1`-`32`
	IPv6UnicastMaximumPathsEbgp *float64 `json:"ipv6UnicastMaximumPathsEbgp,omitempty" tf:"ipv6_unicast_maximum_paths_ebgp,omitempty"`

	// multipath
	// iBGP-multipath
	// - Range: `1`-`32`
	IPv6UnicastMaximumPathsIbgp *float64 `json:"ipv6UnicastMaximumPathsIbgp,omitempty" tf:"ipv6_unicast_maximum_paths_ibgp,omitempty"`

	// (Attributes List) Specify a network to announce via BGP (see below for nested schema)
	IPv6UnicastNetworks []IPv6UnicastNetworksInitParameters `json:"ipv6UnicastNetworks,omitempty" tf:"ipv6_unicast_networks,omitempty"`

	// (Boolean) Connected
	// Connected
	IPv6UnicastRedistributeConnected *bool `json:"ipv6UnicastRedistributeConnected,omitempty" tf:"ipv6_unicast_redistribute_connected,omitempty"`

	// (Number) Metric for redistributed routes
	// Metric for redistributed routes
	// - Range: `0`-`4294967295`
	IPv6UnicastRedistributeConnectedMetric *float64 `json:"ipv6UnicastRedistributeConnectedMetric,omitempty" tf:"ipv6_unicast_redistribute_connected_metric,omitempty"`

	// (String) Route map reference
	// Route map reference
	IPv6UnicastRedistributeConnectedRouteMap *string `json:"ipv6UnicastRedistributeConnectedRouteMap,omitempty" tf:"ipv6_unicast_redistribute_connected_route_map,omitempty"`

	// (Boolean) Static routes
	// Static routes
	IPv6UnicastRedistributeStatic *bool `json:"ipv6UnicastRedistributeStatic,omitempty" tf:"ipv6_unicast_redistribute_static,omitempty"`

	// (Number) Metric for redistributed routes
	// Metric for redistributed routes
	// - Range: `0`-`4294967295`
	IPv6UnicastRedistributeStaticMetric *float64 `json:"ipv6UnicastRedistributeStaticMetric,omitempty" tf:"ipv6_unicast_redistribute_static_metric,omitempty"`

	// (String) Route map reference
	// Route map reference
	IPv6UnicastRedistributeStaticRouteMap *string `json:"ipv6UnicastRedistributeStaticRouteMap,omitempty" tf:"ipv6_unicast_redistribute_static_route_map,omitempty"`
}

type AddressFamilyIPv6Observation struct {

	// Choices: flowspec, mdt, multicast, mvpn, unicast
	//
	// - Choices: `flowspec`, `mdt`, `multicast`, `mvpn`, `unicast`
	AfName *string `json:"afName,omitempty" tf:"af_name,omitempty"`

	// (String)
	Asn *string `json:"asn,omitempty" tf:"asn,omitempty"`

	// is. Default value is all.
	// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is. Default value is `all`.
	// - Choices: `all`, `attributes`
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// (String) The path of the object.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Attributes List) (see below for nested schema)
	IPv6UnicastAdminDistances []IPv6UnicastAdminDistancesObservation `json:"ipv6UnicastAdminDistances,omitempty" tf:"ipv6_unicast_admin_distances,omitempty"`

	// (Attributes List) Configure BGP aggregate entries (see below for nested schema)
	IPv6UnicastAggregateAddresses []IPv6UnicastAggregateAddressesObservation `json:"ipv6UnicastAggregateAddresses,omitempty" tf:"ipv6_unicast_aggregate_addresses,omitempty"`

	// (Number) Distance for routes external to the AS
	// Distance for routes external to the AS
	// - Range: `1`-`255`
	IPv6UnicastDistanceBGPExternal *float64 `json:"ipv6UnicastDistanceBgpExternal,omitempty" tf:"ipv6_unicast_distance_bgp_external,omitempty"`

	// (Number) Distance for routes internal to the AS
	// Distance for routes internal to the AS
	// - Range: `1`-`255`
	IPv6UnicastDistanceBGPInternal *float64 `json:"ipv6UnicastDistanceBgpInternal,omitempty" tf:"ipv6_unicast_distance_bgp_internal,omitempty"`

	// (Number) Distance for local routes
	// Distance for local routes
	// - Range: `1`-`255`
	IPv6UnicastDistanceBGPLocal *float64 `json:"ipv6UnicastDistanceBgpLocal,omitempty" tf:"ipv6_unicast_distance_bgp_local,omitempty"`

	// multipath
	// eBGP-multipath
	// - Range: `1`-`32`
	IPv6UnicastMaximumPathsEbgp *float64 `json:"ipv6UnicastMaximumPathsEbgp,omitempty" tf:"ipv6_unicast_maximum_paths_ebgp,omitempty"`

	// multipath
	// iBGP-multipath
	// - Range: `1`-`32`
	IPv6UnicastMaximumPathsIbgp *float64 `json:"ipv6UnicastMaximumPathsIbgp,omitempty" tf:"ipv6_unicast_maximum_paths_ibgp,omitempty"`

	// (Attributes List) Specify a network to announce via BGP (see below for nested schema)
	IPv6UnicastNetworks []IPv6UnicastNetworksObservation `json:"ipv6UnicastNetworks,omitempty" tf:"ipv6_unicast_networks,omitempty"`

	// (Boolean) Connected
	// Connected
	IPv6UnicastRedistributeConnected *bool `json:"ipv6UnicastRedistributeConnected,omitempty" tf:"ipv6_unicast_redistribute_connected,omitempty"`

	// (Number) Metric for redistributed routes
	// Metric for redistributed routes
	// - Range: `0`-`4294967295`
	IPv6UnicastRedistributeConnectedMetric *float64 `json:"ipv6UnicastRedistributeConnectedMetric,omitempty" tf:"ipv6_unicast_redistribute_connected_metric,omitempty"`

	// (String) Route map reference
	// Route map reference
	IPv6UnicastRedistributeConnectedRouteMap *string `json:"ipv6UnicastRedistributeConnectedRouteMap,omitempty" tf:"ipv6_unicast_redistribute_connected_route_map,omitempty"`

	// (Boolean) Static routes
	// Static routes
	IPv6UnicastRedistributeStatic *bool `json:"ipv6UnicastRedistributeStatic,omitempty" tf:"ipv6_unicast_redistribute_static,omitempty"`

	// (Number) Metric for redistributed routes
	// Metric for redistributed routes
	// - Range: `0`-`4294967295`
	IPv6UnicastRedistributeStaticMetric *float64 `json:"ipv6UnicastRedistributeStaticMetric,omitempty" tf:"ipv6_unicast_redistribute_static_metric,omitempty"`

	// (String) Route map reference
	// Route map reference
	IPv6UnicastRedistributeStaticRouteMap *string `json:"ipv6UnicastRedistributeStaticRouteMap,omitempty" tf:"ipv6_unicast_redistribute_static_route_map,omitempty"`
}

type AddressFamilyIPv6Parameters struct {

	// Choices: flowspec, mdt, multicast, mvpn, unicast
	//
	// - Choices: `flowspec`, `mdt`, `multicast`, `mvpn`, `unicast`
	// +kubebuilder:validation:Optional
	AfName *string `json:"afName,omitempty" tf:"af_name,omitempty"`

	// (String)
	// +crossplane:generate:reference:type=github.com/upbound/provider-upjet-iosxe/apis/namespaced/bgp/v1alpha1.BGP
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("asn",false)
	// +kubebuilder:validation:Optional
	Asn *string `json:"asn,omitempty" tf:"asn,omitempty"`

	// Reference to a BGP in bgp to populate asn.
	// +kubebuilder:validation:Optional
	AsnRef *v2.NamespacedReference `json:"asnRef,omitempty" tf:"-"`

	// Selector for a BGP in bgp to populate asn.
	// +kubebuilder:validation:Optional
	AsnSelector *v2.NamespacedSelector `json:"asnSelector,omitempty" tf:"-"`

	// is. Default value is all.
	// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is. Default value is `all`.
	// - Choices: `all`, `attributes`
	// +kubebuilder:validation:Optional
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	// +kubebuilder:validation:Optional
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// (Attributes List) (see below for nested schema)
	// +kubebuilder:validation:Optional
	IPv6UnicastAdminDistances []IPv6UnicastAdminDistancesParameters `json:"ipv6UnicastAdminDistances,omitempty" tf:"ipv6_unicast_admin_distances,omitempty"`

	// (Attributes List) Configure BGP aggregate entries (see below for nested schema)
	// +kubebuilder:validation:Optional
	IPv6UnicastAggregateAddresses []IPv6UnicastAggregateAddressesParameters `json:"ipv6UnicastAggregateAddresses,omitempty" tf:"ipv6_unicast_aggregate_addresses,omitempty"`

	// (Number) Distance for routes external to the AS
	// Distance for routes external to the AS
	// - Range: `1`-`255`
	// +kubebuilder:validation:Optional
	IPv6UnicastDistanceBGPExternal *float64 `json:"ipv6UnicastDistanceBgpExternal,omitempty" tf:"ipv6_unicast_distance_bgp_external,omitempty"`

	// (Number) Distance for routes internal to the AS
	// Distance for routes internal to the AS
	// - Range: `1`-`255`
	// +kubebuilder:validation:Optional
	IPv6UnicastDistanceBGPInternal *float64 `json:"ipv6UnicastDistanceBgpInternal,omitempty" tf:"ipv6_unicast_distance_bgp_internal,omitempty"`

	// (Number) Distance for local routes
	// Distance for local routes
	// - Range: `1`-`255`
	// +kubebuilder:validation:Optional
	IPv6UnicastDistanceBGPLocal *float64 `json:"ipv6UnicastDistanceBgpLocal,omitempty" tf:"ipv6_unicast_distance_bgp_local,omitempty"`

	// multipath
	// eBGP-multipath
	// - Range: `1`-`32`
	// +kubebuilder:validation:Optional
	IPv6UnicastMaximumPathsEbgp *float64 `json:"ipv6UnicastMaximumPathsEbgp,omitempty" tf:"ipv6_unicast_maximum_paths_ebgp,omitempty"`

	// multipath
	// iBGP-multipath
	// - Range: `1`-`32`
	// +kubebuilder:validation:Optional
	IPv6UnicastMaximumPathsIbgp *float64 `json:"ipv6UnicastMaximumPathsIbgp,omitempty" tf:"ipv6_unicast_maximum_paths_ibgp,omitempty"`

	// (Attributes List) Specify a network to announce via BGP (see below for nested schema)
	// +kubebuilder:validation:Optional
	IPv6UnicastNetworks []IPv6UnicastNetworksParameters `json:"ipv6UnicastNetworks,omitempty" tf:"ipv6_unicast_networks,omitempty"`

	// (Boolean) Connected
	// Connected
	// +kubebuilder:validation:Optional
	IPv6UnicastRedistributeConnected *bool `json:"ipv6UnicastRedistributeConnected,omitempty" tf:"ipv6_unicast_redistribute_connected,omitempty"`

	// (Number) Metric for redistributed routes
	// Metric for redistributed routes
	// - Range: `0`-`4294967295`
	// +kubebuilder:validation:Optional
	IPv6UnicastRedistributeConnectedMetric *float64 `json:"ipv6UnicastRedistributeConnectedMetric,omitempty" tf:"ipv6_unicast_redistribute_connected_metric,omitempty"`

	// (String) Route map reference
	// Route map reference
	// +kubebuilder:validation:Optional
	IPv6UnicastRedistributeConnectedRouteMap *string `json:"ipv6UnicastRedistributeConnectedRouteMap,omitempty" tf:"ipv6_unicast_redistribute_connected_route_map,omitempty"`

	// (Boolean) Static routes
	// Static routes
	// +kubebuilder:validation:Optional
	IPv6UnicastRedistributeStatic *bool `json:"ipv6UnicastRedistributeStatic,omitempty" tf:"ipv6_unicast_redistribute_static,omitempty"`

	// (Number) Metric for redistributed routes
	// Metric for redistributed routes
	// - Range: `0`-`4294967295`
	// +kubebuilder:validation:Optional
	IPv6UnicastRedistributeStaticMetric *float64 `json:"ipv6UnicastRedistributeStaticMetric,omitempty" tf:"ipv6_unicast_redistribute_static_metric,omitempty"`

	// (String) Route map reference
	// Route map reference
	// +kubebuilder:validation:Optional
	IPv6UnicastRedistributeStaticRouteMap *string `json:"ipv6UnicastRedistributeStaticRouteMap,omitempty" tf:"ipv6_unicast_redistribute_static_route_map,omitempty"`
}

type IPv6UnicastAdminDistancesInitParameters struct {

	// (Number) Administrative distance
	// Administrative distance
	// - Range: `1`-`255`
	Distance *float64 `json:"distance,omitempty" tf:"distance,omitempty"`

	// (String) IPv6 prefix list name to match routes from the source
	// IPv6 prefix list name to match routes from the source
	PrefixListName *string `json:"prefixListName,omitempty" tf:"prefix_list_name,omitempty"`

	// (String) Prefix to match source address
	// Prefix to match source address
	SourceIPv6Address *string `json:"sourceIpv6Address,omitempty" tf:"source_ipv6_address,omitempty"`
}

type IPv6UnicastAdminDistancesObservation struct {

	// (Number) Administrative distance
	// Administrative distance
	// - Range: `1`-`255`
	Distance *float64 `json:"distance,omitempty" tf:"distance,omitempty"`

	// (String) IPv6 prefix list name to match routes from the source
	// IPv6 prefix list name to match routes from the source
	PrefixListName *string `json:"prefixListName,omitempty" tf:"prefix_list_name,omitempty"`

	// (String) Prefix to match source address
	// Prefix to match source address
	SourceIPv6Address *string `json:"sourceIpv6Address,omitempty" tf:"source_ipv6_address,omitempty"`
}

type IPv6UnicastAdminDistancesParameters struct {

	// (Number) Administrative distance
	// Administrative distance
	// - Range: `1`-`255`
	// +kubebuilder:validation:Optional
	Distance *float64 `json:"distance" tf:"distance,omitempty"`

	// (String) IPv6 prefix list name to match routes from the source
	// IPv6 prefix list name to match routes from the source
	// +kubebuilder:validation:Optional
	PrefixListName *string `json:"prefixListName,omitempty" tf:"prefix_list_name,omitempty"`

	// (String) Prefix to match source address
	// Prefix to match source address
	// +kubebuilder:validation:Optional
	SourceIPv6Address *string `json:"sourceIpv6Address" tf:"source_ipv6_address,omitempty"`
}

type IPv6UnicastAggregateAddressesInitParameters struct {

	// (String)
	IPv6Address *string `json:"ipv6Address,omitempty" tf:"ipv6_address,omitempty"`
}

type IPv6UnicastAggregateAddressesObservation struct {

	// (String)
	IPv6Address *string `json:"ipv6Address,omitempty" tf:"ipv6_address,omitempty"`
}

type IPv6UnicastAggregateAddressesParameters struct {

	// (String)
	// +kubebuilder:validation:Optional
	IPv6Address *string `json:"ipv6Address" tf:"ipv6_address,omitempty"`
}

type IPv6UnicastNetworksInitParameters struct {

	// (Boolean) Specify a BGP backdoor route
	// Specify a BGP backdoor route
	Backdoor *bool `json:"backdoor,omitempty" tf:"backdoor,omitempty"`

	// (String)
	Network *string `json:"network,omitempty" tf:"network,omitempty"`

	// map to modify the attributes
	// Route-map to modify the attributes
	RouteMap *string `json:"routeMap,omitempty" tf:"route_map,omitempty"`
}

type IPv6UnicastNetworksObservation struct {

	// (Boolean) Specify a BGP backdoor route
	// Specify a BGP backdoor route
	Backdoor *bool `json:"backdoor,omitempty" tf:"backdoor,omitempty"`

	// (String)
	Network *string `json:"network,omitempty" tf:"network,omitempty"`

	// map to modify the attributes
	// Route-map to modify the attributes
	RouteMap *string `json:"routeMap,omitempty" tf:"route_map,omitempty"`
}

type IPv6UnicastNetworksParameters struct {

	// (Boolean) Specify a BGP backdoor route
	// Specify a BGP backdoor route
	// +kubebuilder:validation:Optional
	Backdoor *bool `json:"backdoor,omitempty" tf:"backdoor,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Network *string `json:"network" tf:"network,omitempty"`

	// map to modify the attributes
	// Route-map to modify the attributes
	// +kubebuilder:validation:Optional
	RouteMap *string `json:"routeMap,omitempty" tf:"route_map,omitempty"`
}

// AddressFamilyIPv6Spec defines the desired state of AddressFamilyIPv6
type AddressFamilyIPv6Spec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            AddressFamilyIPv6Parameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AddressFamilyIPv6InitParameters `json:"initProvider,omitempty"`
}

// AddressFamilyIPv6Status defines the observed state of AddressFamilyIPv6.
type AddressFamilyIPv6Status struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               AddressFamilyIPv6Observation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AddressFamilyIPv6 is the Schema for the AddressFamilyIPv6s API. This resource can manage the BGP Address Family IPv6 configuration.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,iosxe}
type AddressFamilyIPv6 struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.afName) || (has(self.initProvider) && has(self.initProvider.afName))",message="spec.forProvider.afName is a required parameter"
	Spec   AddressFamilyIPv6Spec   `json:"spec"`
	Status AddressFamilyIPv6Status `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AddressFamilyIPv6List contains a list of AddressFamilyIPv6s
type AddressFamilyIPv6List struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AddressFamilyIPv6 `json:"items"`
}

// Repository type metadata.
var (
	AddressFamilyIPv6_Kind             = "AddressFamilyIPv6"
	AddressFamilyIPv6_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AddressFamilyIPv6_Kind}.String()
	AddressFamilyIPv6_KindAPIVersion   = AddressFamilyIPv6_Kind + "." + CRDGroupVersion.String()
	AddressFamilyIPv6_GroupVersionKind = CRDGroupVersion.WithKind(AddressFamilyIPv6_Kind)
)

func init() {
	SchemeBuilder.Register(&AddressFamilyIPv6{}, &AddressFamilyIPv6List{})
}
