// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type PeerPolicyTemplateInitParameters struct {

	// Range: 1-10
	//
	// - Range: `1`-`10`
	AllowasInAsNumber *float64 `json:"allowasInAsNumber,omitempty" tf:"allowas_in_as_number,omitempty"`

	// (Boolean)
	AsOverrideSplitHorizon *bool `json:"asOverrideSplitHorizon,omitempty" tf:"as_override_split_horizon,omitempty"`

	// (String)
	// +crossplane:generate:reference:type=github.com/upbound/provider-upjet-iosxe/apis/namespaced/bgp/v1alpha1.BGP
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("asn",false)
	Asn *string `json:"asn,omitempty" tf:"asn,omitempty"`

	// Reference to a BGP in bgp to populate asn.
	// +kubebuilder:validation:Optional
	AsnRef *v2.NamespacedReference `json:"asnRef,omitempty" tf:"-"`

	// Selector for a BGP in bgp to populate asn.
	// +kubebuilder:validation:Optional
	AsnSelector *v2.NamespacedSelector `json:"asnSelector,omitempty" tf:"-"`

	// is. Default value is all.
	// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is. Default value is `all`.
	// - Choices: `all`, `attributes`
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes List) Apply route map to neighbor (see below for nested schema)
	RouteMaps []PeerPolicyTemplateRouteMapsInitParameters `json:"routeMaps,omitempty" tf:"route_maps,omitempty"`

	// (Boolean) Configure a neighbor as Route Reflector client
	// Configure a neighbor as Route Reflector client
	RouteReflectorClient *bool `json:"routeReflectorClient,omitempty" tf:"route_reflector_client,omitempty"`

	// Choices: both, extended, standard
	//
	// - Choices: `both`, `extended`, `standard`
	SendCommunity *string `json:"sendCommunity,omitempty" tf:"send_community,omitempty"`
}

type PeerPolicyTemplateObservation struct {

	// Range: 1-10
	//
	// - Range: `1`-`10`
	AllowasInAsNumber *float64 `json:"allowasInAsNumber,omitempty" tf:"allowas_in_as_number,omitempty"`

	// (Boolean)
	AsOverrideSplitHorizon *bool `json:"asOverrideSplitHorizon,omitempty" tf:"as_override_split_horizon,omitempty"`

	// (String)
	Asn *string `json:"asn,omitempty" tf:"asn,omitempty"`

	// is. Default value is all.
	// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is. Default value is `all`.
	// - Choices: `all`, `attributes`
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// (String) The path of the object.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes List) Apply route map to neighbor (see below for nested schema)
	RouteMaps []PeerPolicyTemplateRouteMapsObservation `json:"routeMaps,omitempty" tf:"route_maps,omitempty"`

	// (Boolean) Configure a neighbor as Route Reflector client
	// Configure a neighbor as Route Reflector client
	RouteReflectorClient *bool `json:"routeReflectorClient,omitempty" tf:"route_reflector_client,omitempty"`

	// Choices: both, extended, standard
	//
	// - Choices: `both`, `extended`, `standard`
	SendCommunity *string `json:"sendCommunity,omitempty" tf:"send_community,omitempty"`
}

type PeerPolicyTemplateParameters struct {

	// Range: 1-10
	//
	// - Range: `1`-`10`
	// +kubebuilder:validation:Optional
	AllowasInAsNumber *float64 `json:"allowasInAsNumber,omitempty" tf:"allowas_in_as_number,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	AsOverrideSplitHorizon *bool `json:"asOverrideSplitHorizon,omitempty" tf:"as_override_split_horizon,omitempty"`

	// (String)
	// +crossplane:generate:reference:type=github.com/upbound/provider-upjet-iosxe/apis/namespaced/bgp/v1alpha1.BGP
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("asn",false)
	// +kubebuilder:validation:Optional
	Asn *string `json:"asn,omitempty" tf:"asn,omitempty"`

	// Reference to a BGP in bgp to populate asn.
	// +kubebuilder:validation:Optional
	AsnRef *v2.NamespacedReference `json:"asnRef,omitempty" tf:"-"`

	// Selector for a BGP in bgp to populate asn.
	// +kubebuilder:validation:Optional
	AsnSelector *v2.NamespacedSelector `json:"asnSelector,omitempty" tf:"-"`

	// is. Default value is all.
	// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is. Default value is `all`.
	// - Choices: `all`, `attributes`
	// +kubebuilder:validation:Optional
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	// +kubebuilder:validation:Optional
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes List) Apply route map to neighbor (see below for nested schema)
	// +kubebuilder:validation:Optional
	RouteMaps []PeerPolicyTemplateRouteMapsParameters `json:"routeMaps,omitempty" tf:"route_maps,omitempty"`

	// (Boolean) Configure a neighbor as Route Reflector client
	// Configure a neighbor as Route Reflector client
	// +kubebuilder:validation:Optional
	RouteReflectorClient *bool `json:"routeReflectorClient,omitempty" tf:"route_reflector_client,omitempty"`

	// Choices: both, extended, standard
	//
	// - Choices: `both`, `extended`, `standard`
	// +kubebuilder:validation:Optional
	SendCommunity *string `json:"sendCommunity,omitempty" tf:"send_community,omitempty"`
}

type PeerPolicyTemplateRouteMapsInitParameters struct {

	// Choices: in, out
	//
	// - Choices: `in`, `out`
	InOut *string `json:"inOut,omitempty" tf:"in_out,omitempty"`

	// (String)
	RouteMapName *string `json:"routeMapName,omitempty" tf:"route_map_name,omitempty"`
}

type PeerPolicyTemplateRouteMapsObservation struct {

	// Choices: in, out
	//
	// - Choices: `in`, `out`
	InOut *string `json:"inOut,omitempty" tf:"in_out,omitempty"`

	// (String)
	RouteMapName *string `json:"routeMapName,omitempty" tf:"route_map_name,omitempty"`
}

type PeerPolicyTemplateRouteMapsParameters struct {

	// Choices: in, out
	//
	// - Choices: `in`, `out`
	// +kubebuilder:validation:Optional
	InOut *string `json:"inOut" tf:"in_out,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	RouteMapName *string `json:"routeMapName" tf:"route_map_name,omitempty"`
}

// PeerPolicyTemplateSpec defines the desired state of PeerPolicyTemplate
type PeerPolicyTemplateSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            PeerPolicyTemplateParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PeerPolicyTemplateInitParameters `json:"initProvider,omitempty"`
}

// PeerPolicyTemplateStatus defines the observed state of PeerPolicyTemplate.
type PeerPolicyTemplateStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               PeerPolicyTemplateObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// PeerPolicyTemplate is the Schema for the PeerPolicyTemplates API. This resource can manage the BGP Peer Policy Template configuration.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,iosxe}
type PeerPolicyTemplate struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   PeerPolicyTemplateSpec   `json:"spec"`
	Status PeerPolicyTemplateStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PeerPolicyTemplateList contains a list of PeerPolicyTemplates
type PeerPolicyTemplateList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PeerPolicyTemplate `json:"items"`
}

// Repository type metadata.
var (
	PeerPolicyTemplate_Kind             = "PeerPolicyTemplate"
	PeerPolicyTemplate_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: PeerPolicyTemplate_Kind}.String()
	PeerPolicyTemplate_KindAPIVersion   = PeerPolicyTemplate_Kind + "." + CRDGroupVersion.String()
	PeerPolicyTemplate_GroupVersionKind = CRDGroupVersion.WithKind(PeerPolicyTemplate_Kind)
)

func init() {
	SchemeBuilder.Register(&PeerPolicyTemplate{}, &PeerPolicyTemplateList{})
}
