//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MPLS) DeepCopyInto(out *MPLS) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MPLS.
func (in *MPLS) DeepCopy() *MPLS {
	if in == nil {
		return nil
	}
	out := new(MPLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MPLS) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MPLSInitParameters) DeepCopyInto(out *MPLSInitParameters) {
	*out = *in
	if in.DeleteMode != nil {
		in, out := &in.DeleteMode, &out.DeleteMode
		*out = new(string)
		**out = **in
	}
	if in.Device != nil {
		in, out := &in.Device, &out.Device
		*out = new(string)
		**out = **in
	}
	if in.LabelModeAllVrfsAllAfsPerCe != nil {
		in, out := &in.LabelModeAllVrfsAllAfsPerCe, &out.LabelModeAllVrfsAllAfsPerCe
		*out = new(bool)
		**out = **in
	}
	if in.LabelModeAllVrfsAllAfsPerPrefix != nil {
		in, out := &in.LabelModeAllVrfsAllAfsPerPrefix, &out.LabelModeAllVrfsAllAfsPerPrefix
		*out = new(bool)
		**out = **in
	}
	if in.LabelModeAllVrfsAllAfsPerVrf != nil {
		in, out := &in.LabelModeAllVrfsAllAfsPerVrf, &out.LabelModeAllVrfsAllAfsPerVrf
		*out = new(bool)
		**out = **in
	}
	if in.LabelModeAllVrfsAllAfsVrfConnAggr != nil {
		in, out := &in.LabelModeAllVrfsAllAfsVrfConnAggr, &out.LabelModeAllVrfsAllAfsVrfConnAggr
		*out = new(bool)
		**out = **in
	}
	if in.LabelModeAllVrfsBGPVpnv4PerCe != nil {
		in, out := &in.LabelModeAllVrfsBGPVpnv4PerCe, &out.LabelModeAllVrfsBGPVpnv4PerCe
		*out = new(bool)
		**out = **in
	}
	if in.LabelModeAllVrfsBGPVpnv4PerPrefix != nil {
		in, out := &in.LabelModeAllVrfsBGPVpnv4PerPrefix, &out.LabelModeAllVrfsBGPVpnv4PerPrefix
		*out = new(bool)
		**out = **in
	}
	if in.LabelModeAllVrfsBGPVpnv4PerVrf != nil {
		in, out := &in.LabelModeAllVrfsBGPVpnv4PerVrf, &out.LabelModeAllVrfsBGPVpnv4PerVrf
		*out = new(bool)
		**out = **in
	}
	if in.LabelModeAllVrfsBGPVpnv4VrfConnAggr != nil {
		in, out := &in.LabelModeAllVrfsBGPVpnv4VrfConnAggr, &out.LabelModeAllVrfsBGPVpnv4VrfConnAggr
		*out = new(bool)
		**out = **in
	}
	if in.LabelModeAllVrfsBGPVpnv6PerCe != nil {
		in, out := &in.LabelModeAllVrfsBGPVpnv6PerCe, &out.LabelModeAllVrfsBGPVpnv6PerCe
		*out = new(bool)
		**out = **in
	}
	if in.LabelModeAllVrfsBGPVpnv6PerPrefix != nil {
		in, out := &in.LabelModeAllVrfsBGPVpnv6PerPrefix, &out.LabelModeAllVrfsBGPVpnv6PerPrefix
		*out = new(bool)
		**out = **in
	}
	if in.LabelModeAllVrfsBGPVpnv6PerVrf != nil {
		in, out := &in.LabelModeAllVrfsBGPVpnv6PerVrf, &out.LabelModeAllVrfsBGPVpnv6PerVrf
		*out = new(bool)
		**out = **in
	}
	if in.LabelModeAllVrfsBGPVpnv6VrfConnAggr != nil {
		in, out := &in.LabelModeAllVrfsBGPVpnv6VrfConnAggr, &out.LabelModeAllVrfsBGPVpnv6VrfConnAggr
		*out = new(bool)
		**out = **in
	}
	if in.LabelProtocol != nil {
		in, out := &in.LabelProtocol, &out.LabelProtocol
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MPLSInitParameters.
func (in *MPLSInitParameters) DeepCopy() *MPLSInitParameters {
	if in == nil {
		return nil
	}
	out := new(MPLSInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MPLSList) DeepCopyInto(out *MPLSList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MPLS, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MPLSList.
func (in *MPLSList) DeepCopy() *MPLSList {
	if in == nil {
		return nil
	}
	out := new(MPLSList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MPLSList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MPLSObservation) DeepCopyInto(out *MPLSObservation) {
	*out = *in
	if in.DeleteMode != nil {
		in, out := &in.DeleteMode, &out.DeleteMode
		*out = new(string)
		**out = **in
	}
	if in.Device != nil {
		in, out := &in.Device, &out.Device
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.LabelModeAllVrfsAllAfsPerCe != nil {
		in, out := &in.LabelModeAllVrfsAllAfsPerCe, &out.LabelModeAllVrfsAllAfsPerCe
		*out = new(bool)
		**out = **in
	}
	if in.LabelModeAllVrfsAllAfsPerPrefix != nil {
		in, out := &in.LabelModeAllVrfsAllAfsPerPrefix, &out.LabelModeAllVrfsAllAfsPerPrefix
		*out = new(bool)
		**out = **in
	}
	if in.LabelModeAllVrfsAllAfsPerVrf != nil {
		in, out := &in.LabelModeAllVrfsAllAfsPerVrf, &out.LabelModeAllVrfsAllAfsPerVrf
		*out = new(bool)
		**out = **in
	}
	if in.LabelModeAllVrfsAllAfsVrfConnAggr != nil {
		in, out := &in.LabelModeAllVrfsAllAfsVrfConnAggr, &out.LabelModeAllVrfsAllAfsVrfConnAggr
		*out = new(bool)
		**out = **in
	}
	if in.LabelModeAllVrfsBGPVpnv4PerCe != nil {
		in, out := &in.LabelModeAllVrfsBGPVpnv4PerCe, &out.LabelModeAllVrfsBGPVpnv4PerCe
		*out = new(bool)
		**out = **in
	}
	if in.LabelModeAllVrfsBGPVpnv4PerPrefix != nil {
		in, out := &in.LabelModeAllVrfsBGPVpnv4PerPrefix, &out.LabelModeAllVrfsBGPVpnv4PerPrefix
		*out = new(bool)
		**out = **in
	}
	if in.LabelModeAllVrfsBGPVpnv4PerVrf != nil {
		in, out := &in.LabelModeAllVrfsBGPVpnv4PerVrf, &out.LabelModeAllVrfsBGPVpnv4PerVrf
		*out = new(bool)
		**out = **in
	}
	if in.LabelModeAllVrfsBGPVpnv4VrfConnAggr != nil {
		in, out := &in.LabelModeAllVrfsBGPVpnv4VrfConnAggr, &out.LabelModeAllVrfsBGPVpnv4VrfConnAggr
		*out = new(bool)
		**out = **in
	}
	if in.LabelModeAllVrfsBGPVpnv6PerCe != nil {
		in, out := &in.LabelModeAllVrfsBGPVpnv6PerCe, &out.LabelModeAllVrfsBGPVpnv6PerCe
		*out = new(bool)
		**out = **in
	}
	if in.LabelModeAllVrfsBGPVpnv6PerPrefix != nil {
		in, out := &in.LabelModeAllVrfsBGPVpnv6PerPrefix, &out.LabelModeAllVrfsBGPVpnv6PerPrefix
		*out = new(bool)
		**out = **in
	}
	if in.LabelModeAllVrfsBGPVpnv6PerVrf != nil {
		in, out := &in.LabelModeAllVrfsBGPVpnv6PerVrf, &out.LabelModeAllVrfsBGPVpnv6PerVrf
		*out = new(bool)
		**out = **in
	}
	if in.LabelModeAllVrfsBGPVpnv6VrfConnAggr != nil {
		in, out := &in.LabelModeAllVrfsBGPVpnv6VrfConnAggr, &out.LabelModeAllVrfsBGPVpnv6VrfConnAggr
		*out = new(bool)
		**out = **in
	}
	if in.LabelProtocol != nil {
		in, out := &in.LabelProtocol, &out.LabelProtocol
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MPLSObservation.
func (in *MPLSObservation) DeepCopy() *MPLSObservation {
	if in == nil {
		return nil
	}
	out := new(MPLSObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MPLSParameters) DeepCopyInto(out *MPLSParameters) {
	*out = *in
	if in.DeleteMode != nil {
		in, out := &in.DeleteMode, &out.DeleteMode
		*out = new(string)
		**out = **in
	}
	if in.Device != nil {
		in, out := &in.Device, &out.Device
		*out = new(string)
		**out = **in
	}
	if in.LabelModeAllVrfsAllAfsPerCe != nil {
		in, out := &in.LabelModeAllVrfsAllAfsPerCe, &out.LabelModeAllVrfsAllAfsPerCe
		*out = new(bool)
		**out = **in
	}
	if in.LabelModeAllVrfsAllAfsPerPrefix != nil {
		in, out := &in.LabelModeAllVrfsAllAfsPerPrefix, &out.LabelModeAllVrfsAllAfsPerPrefix
		*out = new(bool)
		**out = **in
	}
	if in.LabelModeAllVrfsAllAfsPerVrf != nil {
		in, out := &in.LabelModeAllVrfsAllAfsPerVrf, &out.LabelModeAllVrfsAllAfsPerVrf
		*out = new(bool)
		**out = **in
	}
	if in.LabelModeAllVrfsAllAfsVrfConnAggr != nil {
		in, out := &in.LabelModeAllVrfsAllAfsVrfConnAggr, &out.LabelModeAllVrfsAllAfsVrfConnAggr
		*out = new(bool)
		**out = **in
	}
	if in.LabelModeAllVrfsBGPVpnv4PerCe != nil {
		in, out := &in.LabelModeAllVrfsBGPVpnv4PerCe, &out.LabelModeAllVrfsBGPVpnv4PerCe
		*out = new(bool)
		**out = **in
	}
	if in.LabelModeAllVrfsBGPVpnv4PerPrefix != nil {
		in, out := &in.LabelModeAllVrfsBGPVpnv4PerPrefix, &out.LabelModeAllVrfsBGPVpnv4PerPrefix
		*out = new(bool)
		**out = **in
	}
	if in.LabelModeAllVrfsBGPVpnv4PerVrf != nil {
		in, out := &in.LabelModeAllVrfsBGPVpnv4PerVrf, &out.LabelModeAllVrfsBGPVpnv4PerVrf
		*out = new(bool)
		**out = **in
	}
	if in.LabelModeAllVrfsBGPVpnv4VrfConnAggr != nil {
		in, out := &in.LabelModeAllVrfsBGPVpnv4VrfConnAggr, &out.LabelModeAllVrfsBGPVpnv4VrfConnAggr
		*out = new(bool)
		**out = **in
	}
	if in.LabelModeAllVrfsBGPVpnv6PerCe != nil {
		in, out := &in.LabelModeAllVrfsBGPVpnv6PerCe, &out.LabelModeAllVrfsBGPVpnv6PerCe
		*out = new(bool)
		**out = **in
	}
	if in.LabelModeAllVrfsBGPVpnv6PerPrefix != nil {
		in, out := &in.LabelModeAllVrfsBGPVpnv6PerPrefix, &out.LabelModeAllVrfsBGPVpnv6PerPrefix
		*out = new(bool)
		**out = **in
	}
	if in.LabelModeAllVrfsBGPVpnv6PerVrf != nil {
		in, out := &in.LabelModeAllVrfsBGPVpnv6PerVrf, &out.LabelModeAllVrfsBGPVpnv6PerVrf
		*out = new(bool)
		**out = **in
	}
	if in.LabelModeAllVrfsBGPVpnv6VrfConnAggr != nil {
		in, out := &in.LabelModeAllVrfsBGPVpnv6VrfConnAggr, &out.LabelModeAllVrfsBGPVpnv6VrfConnAggr
		*out = new(bool)
		**out = **in
	}
	if in.LabelProtocol != nil {
		in, out := &in.LabelProtocol, &out.LabelProtocol
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MPLSParameters.
func (in *MPLSParameters) DeepCopy() *MPLSParameters {
	if in == nil {
		return nil
	}
	out := new(MPLSParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MPLSSpec) DeepCopyInto(out *MPLSSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MPLSSpec.
func (in *MPLSSpec) DeepCopy() *MPLSSpec {
	if in == nil {
		return nil
	}
	out := new(MPLSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MPLSStatus) DeepCopyInto(out *MPLSStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MPLSStatus.
func (in *MPLSStatus) DeepCopy() *MPLSStatus {
	if in == nil {
		return nil
	}
	out := new(MPLSStatus)
	in.DeepCopyInto(out)
	return out
}
