apiVersion: routing.iosxe.m.upbound.io/v1alpha1
kind: PrefixList
metadata:
  annotations:
    meta.upbound.io/example-id: routing/v1alpha1/prefixlist
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: crossplane-system
spec:
  forProvider:
    prefixListDescription:
    - description: My prefix list
      name: PREFIX_LIST_1
    prefixes:
    - action: permit
      ge: 24
      ip: 10.0.0.0/8
      le: 32
      name: PREFIX_LIST_1
      seq: 10
