// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type AddressFamilyIPv4MVPNInitParameters struct {

	// Choices: flowspec, labeled-unicast, mdt, multicast, mvpn, sr-policy, tunnel, unicast
	//
	// - Choices: `flowspec`, `labeled-unicast`, `mdt`, `multicast`, `mvpn`, `sr-policy`, `tunnel`, `unicast`
	AfName *string `json:"afName,omitempty" tf:"af_name,omitempty"`

	// (String)
	// +crossplane:generate:reference:type=github.com/upbound/provider-upjet-iosxe/apis/cluster/bgp/v1alpha1.BGP
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("asn",false)
	Asn *string `json:"asn,omitempty" tf:"asn,omitempty"`

	// Reference to a BGP in bgp to populate asn.
	// +kubebuilder:validation:Optional
	AsnRef *v2.Reference `json:"asnRef,omitempty" tf:"-"`

	// Selector for a BGP in bgp to populate asn.
	// +kubebuilder:validation:Optional
	AsnSelector *v2.Selector `json:"asnSelector,omitempty" tf:"-"`

	// is. Default value is all.
	// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is. Default value is `all`.
	// - Choices: `all`, `attributes`
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	Device *string `json:"device,omitempty" tf:"device,omitempty"`
}

type AddressFamilyIPv4MVPNObservation struct {

	// Choices: flowspec, labeled-unicast, mdt, multicast, mvpn, sr-policy, tunnel, unicast
	//
	// - Choices: `flowspec`, `labeled-unicast`, `mdt`, `multicast`, `mvpn`, `sr-policy`, `tunnel`, `unicast`
	AfName *string `json:"afName,omitempty" tf:"af_name,omitempty"`

	// (String)
	Asn *string `json:"asn,omitempty" tf:"asn,omitempty"`

	// is. Default value is all.
	// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is. Default value is `all`.
	// - Choices: `all`, `attributes`
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// (String) The path of the object.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type AddressFamilyIPv4MVPNParameters struct {

	// Choices: flowspec, labeled-unicast, mdt, multicast, mvpn, sr-policy, tunnel, unicast
	//
	// - Choices: `flowspec`, `labeled-unicast`, `mdt`, `multicast`, `mvpn`, `sr-policy`, `tunnel`, `unicast`
	// +kubebuilder:validation:Optional
	AfName *string `json:"afName,omitempty" tf:"af_name,omitempty"`

	// (String)
	// +crossplane:generate:reference:type=github.com/upbound/provider-upjet-iosxe/apis/cluster/bgp/v1alpha1.BGP
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("asn",false)
	// +kubebuilder:validation:Optional
	Asn *string `json:"asn,omitempty" tf:"asn,omitempty"`

	// Reference to a BGP in bgp to populate asn.
	// +kubebuilder:validation:Optional
	AsnRef *v2.Reference `json:"asnRef,omitempty" tf:"-"`

	// Selector for a BGP in bgp to populate asn.
	// +kubebuilder:validation:Optional
	AsnSelector *v2.Selector `json:"asnSelector,omitempty" tf:"-"`

	// is. Default value is all.
	// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is. Default value is `all`.
	// - Choices: `all`, `attributes`
	// +kubebuilder:validation:Optional
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	// +kubebuilder:validation:Optional
	Device *string `json:"device,omitempty" tf:"device,omitempty"`
}

// AddressFamilyIPv4MVPNSpec defines the desired state of AddressFamilyIPv4MVPN
type AddressFamilyIPv4MVPNSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   AddressFamilyIPv4MVPNParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AddressFamilyIPv4MVPNInitParameters `json:"initProvider,omitempty"`
}

// AddressFamilyIPv4MVPNStatus defines the observed state of AddressFamilyIPv4MVPN.
type AddressFamilyIPv4MVPNStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               AddressFamilyIPv4MVPNObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AddressFamilyIPv4MVPN is the Schema for the AddressFamilyIPv4MVPNs API. This resource can manage the BGP Address Family IPv4 MVPN configuration.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,iosxe}
type AddressFamilyIPv4MVPN struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.afName) || (has(self.initProvider) && has(self.initProvider.afName))",message="spec.forProvider.afName is a required parameter"
	Spec   AddressFamilyIPv4MVPNSpec   `json:"spec"`
	Status AddressFamilyIPv4MVPNStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AddressFamilyIPv4MVPNList contains a list of AddressFamilyIPv4MVPNs
type AddressFamilyIPv4MVPNList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AddressFamilyIPv4MVPN `json:"items"`
}

// Repository type metadata.
var (
	AddressFamilyIPv4MVPN_Kind             = "AddressFamilyIPv4MVPN"
	AddressFamilyIPv4MVPN_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AddressFamilyIPv4MVPN_Kind}.String()
	AddressFamilyIPv4MVPN_KindAPIVersion   = AddressFamilyIPv4MVPN_Kind + "." + CRDGroupVersion.String()
	AddressFamilyIPv4MVPN_GroupVersionKind = CRDGroupVersion.WithKind(AddressFamilyIPv4MVPN_Kind)
)

func init() {
	SchemeBuilder.Register(&AddressFamilyIPv4MVPN{}, &AddressFamilyIPv4MVPNList{})
}
