// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	resource "github.com/crossplane/upjet/v2/pkg/resource"
	errors "github.com/pkg/errors"
	v1alpha1 "github.com/upbound/provider-upjet-iosxe/apis/cluster/routing/v1alpha1"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this AddressFamilyIPv4.
func (mg *AddressFamilyIPv4) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Asn),
		Extract:      resource.ExtractParamPath("asn", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.AsnRef,
		Selector:     mg.Spec.ForProvider.AsnSelector,
		To: reference.To{
			List:    &BGPList{},
			Managed: &BGP{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Asn")
	}
	mg.Spec.ForProvider.Asn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.AsnRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Asn),
		Extract:      resource.ExtractParamPath("asn", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.AsnRef,
		Selector:     mg.Spec.InitProvider.AsnSelector,
		To: reference.To{
			List:    &BGPList{},
			Managed: &BGP{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Asn")
	}
	mg.Spec.InitProvider.Asn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.AsnRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this AddressFamilyIPv4MVPN.
func (mg *AddressFamilyIPv4MVPN) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Asn),
		Extract:      resource.ExtractParamPath("asn", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.AsnRef,
		Selector:     mg.Spec.ForProvider.AsnSelector,
		To: reference.To{
			List:    &BGPList{},
			Managed: &BGP{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Asn")
	}
	mg.Spec.ForProvider.Asn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.AsnRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Asn),
		Extract:      resource.ExtractParamPath("asn", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.AsnRef,
		Selector:     mg.Spec.InitProvider.AsnSelector,
		To: reference.To{
			List:    &BGPList{},
			Managed: &BGP{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Asn")
	}
	mg.Spec.InitProvider.Asn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.AsnRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this AddressFamilyIPv4VRF.
func (mg *AddressFamilyIPv4VRF) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Asn),
		Extract:      resource.ExtractParamPath("asn", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.AsnRef,
		Selector:     mg.Spec.ForProvider.AsnSelector,
		To: reference.To{
			List:    &BGPList{},
			Managed: &BGP{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Asn")
	}
	mg.Spec.ForProvider.Asn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.AsnRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Asn),
		Extract:      resource.ExtractParamPath("asn", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.AsnRef,
		Selector:     mg.Spec.InitProvider.AsnSelector,
		To: reference.To{
			List:    &BGPList{},
			Managed: &BGP{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Asn")
	}
	mg.Spec.InitProvider.Asn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.AsnRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this AddressFamilyIPv6.
func (mg *AddressFamilyIPv6) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Asn),
		Extract:      resource.ExtractParamPath("asn", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.AsnRef,
		Selector:     mg.Spec.ForProvider.AsnSelector,
		To: reference.To{
			List:    &BGPList{},
			Managed: &BGP{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Asn")
	}
	mg.Spec.ForProvider.Asn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.AsnRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Asn),
		Extract:      resource.ExtractParamPath("asn", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.AsnRef,
		Selector:     mg.Spec.InitProvider.AsnSelector,
		To: reference.To{
			List:    &BGPList{},
			Managed: &BGP{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Asn")
	}
	mg.Spec.InitProvider.Asn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.AsnRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this AddressFamilyIPv6VRF.
func (mg *AddressFamilyIPv6VRF) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Asn),
		Extract:      resource.ExtractParamPath("asn", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.AsnRef,
		Selector:     mg.Spec.ForProvider.AsnSelector,
		To: reference.To{
			List:    &BGPList{},
			Managed: &BGP{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Asn")
	}
	mg.Spec.ForProvider.Asn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.AsnRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Asn),
		Extract:      resource.ExtractParamPath("asn", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.AsnRef,
		Selector:     mg.Spec.InitProvider.AsnSelector,
		To: reference.To{
			List:    &BGPList{},
			Managed: &BGP{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Asn")
	}
	mg.Spec.InitProvider.Asn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.AsnRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this AddressFamilyL2VPN.
func (mg *AddressFamilyL2VPN) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Asn),
		Extract:      resource.ExtractParamPath("asn", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.AsnRef,
		Selector:     mg.Spec.ForProvider.AsnSelector,
		To: reference.To{
			List:    &BGPList{},
			Managed: &BGP{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Asn")
	}
	mg.Spec.ForProvider.Asn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.AsnRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Asn),
		Extract:      resource.ExtractParamPath("asn", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.AsnRef,
		Selector:     mg.Spec.InitProvider.AsnSelector,
		To: reference.To{
			List:    &BGPList{},
			Managed: &BGP{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Asn")
	}
	mg.Spec.InitProvider.Asn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.AsnRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this AddressFamilyVPNv4.
func (mg *AddressFamilyVPNv4) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Asn),
		Extract:      resource.ExtractParamPath("asn", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.AsnRef,
		Selector:     mg.Spec.ForProvider.AsnSelector,
		To: reference.To{
			List:    &BGPList{},
			Managed: &BGP{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Asn")
	}
	mg.Spec.ForProvider.Asn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.AsnRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Asn),
		Extract:      resource.ExtractParamPath("asn", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.AsnRef,
		Selector:     mg.Spec.InitProvider.AsnSelector,
		To: reference.To{
			List:    &BGPList{},
			Managed: &BGP{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Asn")
	}
	mg.Spec.InitProvider.Asn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.AsnRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this AddressFamilyVPNv6.
func (mg *AddressFamilyVPNv6) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Asn),
		Extract:      resource.ExtractParamPath("asn", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.AsnRef,
		Selector:     mg.Spec.ForProvider.AsnSelector,
		To: reference.To{
			List:    &BGPList{},
			Managed: &BGP{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Asn")
	}
	mg.Spec.ForProvider.Asn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.AsnRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Asn),
		Extract:      resource.ExtractParamPath("asn", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.AsnRef,
		Selector:     mg.Spec.InitProvider.AsnSelector,
		To: reference.To{
			List:    &BGPList{},
			Managed: &BGP{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Asn")
	}
	mg.Spec.InitProvider.Asn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.AsnRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this BMPServer.
func (mg *BMPServer) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Asn),
		Extract:      resource.ExtractParamPath("asn", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.AsnRef,
		Selector:     mg.Spec.ForProvider.AsnSelector,
		To: reference.To{
			List:    &BGPList{},
			Managed: &BGP{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Asn")
	}
	mg.Spec.ForProvider.Asn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.AsnRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Asn),
		Extract:      resource.ExtractParamPath("asn", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.AsnRef,
		Selector:     mg.Spec.InitProvider.AsnSelector,
		To: reference.To{
			List:    &BGPList{},
			Managed: &BGP{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Asn")
	}
	mg.Spec.InitProvider.Asn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.AsnRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this IPv4MVPNNeighbor.
func (mg *IPv4MVPNNeighbor) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Asn),
		Extract:      resource.ExtractParamPath("asn", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.AsnRef,
		Selector:     mg.Spec.ForProvider.AsnSelector,
		To: reference.To{
			List:    &BGPList{},
			Managed: &BGP{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Asn")
	}
	mg.Spec.ForProvider.Asn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.AsnRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Asn),
		Extract:      resource.ExtractParamPath("asn", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.AsnRef,
		Selector:     mg.Spec.InitProvider.AsnSelector,
		To: reference.To{
			List:    &BGPList{},
			Managed: &BGP{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Asn")
	}
	mg.Spec.InitProvider.Asn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.AsnRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this IPv4UnicastNeighbor.
func (mg *IPv4UnicastNeighbor) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Asn),
		Extract:      resource.ExtractParamPath("asn", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.AsnRef,
		Selector:     mg.Spec.ForProvider.AsnSelector,
		To: reference.To{
			List:    &BGPList{},
			Managed: &BGP{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Asn")
	}
	mg.Spec.ForProvider.Asn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.AsnRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Asn),
		Extract:      resource.ExtractParamPath("asn", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.AsnRef,
		Selector:     mg.Spec.InitProvider.AsnSelector,
		To: reference.To{
			List:    &BGPList{},
			Managed: &BGP{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Asn")
	}
	mg.Spec.InitProvider.Asn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.AsnRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this IPv4UnicastVRFNeighbor.
func (mg *IPv4UnicastVRFNeighbor) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Asn),
		Extract:      resource.ExtractParamPath("asn", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.AsnRef,
		Selector:     mg.Spec.ForProvider.AsnSelector,
		To: reference.To{
			List:    &BGPList{},
			Managed: &BGP{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Asn")
	}
	mg.Spec.ForProvider.Asn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.AsnRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Vrf),
		Extract:      resource.ExtractParamPath("name", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.VrfRef,
		Selector:     mg.Spec.ForProvider.VrfSelector,
		To: reference.To{
			List:    &v1alpha1.VRFList{},
			Managed: &v1alpha1.VRF{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Vrf")
	}
	mg.Spec.ForProvider.Vrf = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.VrfRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Asn),
		Extract:      resource.ExtractParamPath("asn", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.AsnRef,
		Selector:     mg.Spec.InitProvider.AsnSelector,
		To: reference.To{
			List:    &BGPList{},
			Managed: &BGP{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Asn")
	}
	mg.Spec.InitProvider.Asn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.AsnRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Vrf),
		Extract:      resource.ExtractParamPath("name", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.VrfRef,
		Selector:     mg.Spec.InitProvider.VrfSelector,
		To: reference.To{
			List:    &v1alpha1.VRFList{},
			Managed: &v1alpha1.VRF{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Vrf")
	}
	mg.Spec.InitProvider.Vrf = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.VrfRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this IPv6UnicastNeighbor.
func (mg *IPv6UnicastNeighbor) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Asn),
		Extract:      resource.ExtractParamPath("asn", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.AsnRef,
		Selector:     mg.Spec.ForProvider.AsnSelector,
		To: reference.To{
			List:    &BGPList{},
			Managed: &BGP{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Asn")
	}
	mg.Spec.ForProvider.Asn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.AsnRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Asn),
		Extract:      resource.ExtractParamPath("asn", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.AsnRef,
		Selector:     mg.Spec.InitProvider.AsnSelector,
		To: reference.To{
			List:    &BGPList{},
			Managed: &BGP{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Asn")
	}
	mg.Spec.InitProvider.Asn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.AsnRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this L2VPNEVPNNeighbor.
func (mg *L2VPNEVPNNeighbor) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Asn),
		Extract:      resource.ExtractParamPath("asn", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.AsnRef,
		Selector:     mg.Spec.ForProvider.AsnSelector,
		To: reference.To{
			List:    &BGPList{},
			Managed: &BGP{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Asn")
	}
	mg.Spec.ForProvider.Asn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.AsnRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Asn),
		Extract:      resource.ExtractParamPath("asn", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.AsnRef,
		Selector:     mg.Spec.InitProvider.AsnSelector,
		To: reference.To{
			List:    &BGPList{},
			Managed: &BGP{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Asn")
	}
	mg.Spec.InitProvider.Asn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.AsnRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Neighbor.
func (mg *Neighbor) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Asn),
		Extract:      resource.ExtractParamPath("asn", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.AsnRef,
		Selector:     mg.Spec.ForProvider.AsnSelector,
		To: reference.To{
			List:    &BGPList{},
			Managed: &BGP{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Asn")
	}
	mg.Spec.ForProvider.Asn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.AsnRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Asn),
		Extract:      resource.ExtractParamPath("asn", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.AsnRef,
		Selector:     mg.Spec.InitProvider.AsnSelector,
		To: reference.To{
			List:    &BGPList{},
			Managed: &BGP{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Asn")
	}
	mg.Spec.InitProvider.Asn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.AsnRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this PeerPolicyTemplate.
func (mg *PeerPolicyTemplate) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Asn),
		Extract:      resource.ExtractParamPath("asn", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.AsnRef,
		Selector:     mg.Spec.ForProvider.AsnSelector,
		To: reference.To{
			List:    &BGPList{},
			Managed: &BGP{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Asn")
	}
	mg.Spec.ForProvider.Asn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.AsnRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Asn),
		Extract:      resource.ExtractParamPath("asn", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.AsnRef,
		Selector:     mg.Spec.InitProvider.AsnSelector,
		To: reference.To{
			List:    &BGPList{},
			Managed: &BGP{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Asn")
	}
	mg.Spec.InitProvider.Asn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.AsnRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this PeerSessionTemplate.
func (mg *PeerSessionTemplate) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Asn),
		Extract:      resource.ExtractParamPath("asn", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.AsnRef,
		Selector:     mg.Spec.ForProvider.AsnSelector,
		To: reference.To{
			List:    &BGPList{},
			Managed: &BGP{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Asn")
	}
	mg.Spec.ForProvider.Asn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.AsnRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Asn),
		Extract:      resource.ExtractParamPath("asn", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.AsnRef,
		Selector:     mg.Spec.InitProvider.AsnSelector,
		To: reference.To{
			List:    &BGPList{},
			Managed: &BGP{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Asn")
	}
	mg.Spec.InitProvider.Asn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.AsnRef = rsp.ResolvedReference

	return nil
}
