// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type PeerSessionTemplateInitParameters struct {

	// (Boolean) accept ao mismatch connections
	// accept ao mismatch connections
	AoAcceptMismatchConnections *bool `json:"aoAcceptMismatchConnections,omitempty" tf:"ao_accept_mismatch_connections,omitempty"`

	// (Boolean) Include TCP options
	// Include TCP options
	AoIncludeTCPOptions *bool `json:"aoIncludeTcpOptions,omitempty" tf:"ao_include_tcp_options,omitempty"`

	// (String) Key Chain Name
	// Key Chain Name
	AoKeychain *string `json:"aoKeychain,omitempty" tf:"ao_keychain,omitempty"`

	// (String)
	// +crossplane:generate:reference:type=github.com/upbound/provider-upjet-iosxe/apis/cluster/bgp/v1alpha1.BGP
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("asn",false)
	Asn *string `json:"asn,omitempty" tf:"asn,omitempty"`

	// Reference to a BGP in bgp to populate asn.
	// +kubebuilder:validation:Optional
	AsnRef *v2.Reference `json:"asnRef,omitempty" tf:"-"`

	// Selector for a BGP in bgp to populate asn.
	// +kubebuilder:validation:Optional
	AsnSelector *v2.Selector `json:"asnSelector,omitempty" tf:"-"`

	// is. Default value is all.
	// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is. Default value is `all`.
	// - Choices: `all`, `attributes`
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// (String) Neighbor specific description
	// Neighbor specific description
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// hop away EBGP peer using loopback address
	// one-hop away EBGP peer using loopback address
	DisableConnectedCheck *bool `json:"disableConnectedCheck,omitempty" tf:"disable_connected_check,omitempty"`

	// hop ebgp peers, delete ebgp-multihop directly.
	// Allow EBGP neighbors not on directly connected networks. For single-hop ebgp peers, delete ebgp-multihop directly.
	EbgpMultihop *bool `json:"ebgpMultihop,omitempty" tf:"ebgp_multihop,omitempty"`

	// Range: 2-255
	//
	// - Range: `2`-`255`
	EbgpMultihopMaxHop *float64 `json:"ebgpMultihopMaxHop,omitempty" tf:"ebgp_multihop_max_hop,omitempty"`

	// session template
	// Inherit a peer-session template
	InheritPeerSession *string `json:"inheritPeerSession,omitempty" tf:"inherit_peer_session,omitempty"`

	// as
	// Specify a BGP neighbor remote-as
	RemoteAs *string `json:"remoteAs,omitempty" tf:"remote_as,omitempty"`

	// (String)
	TemplateName *string `json:"templateName,omitempty" tf:"template_name,omitempty"`

	// (Number) Loopback interface
	// Loopback interface
	UpdateSourceInterfaceLoopback *float64 `json:"updateSourceInterfaceLoopback,omitempty" tf:"update_source_interface_loopback,omitempty"`
}

type PeerSessionTemplateObservation struct {

	// (Boolean) accept ao mismatch connections
	// accept ao mismatch connections
	AoAcceptMismatchConnections *bool `json:"aoAcceptMismatchConnections,omitempty" tf:"ao_accept_mismatch_connections,omitempty"`

	// (Boolean) Include TCP options
	// Include TCP options
	AoIncludeTCPOptions *bool `json:"aoIncludeTcpOptions,omitempty" tf:"ao_include_tcp_options,omitempty"`

	// (String) Key Chain Name
	// Key Chain Name
	AoKeychain *string `json:"aoKeychain,omitempty" tf:"ao_keychain,omitempty"`

	// (String)
	Asn *string `json:"asn,omitempty" tf:"asn,omitempty"`

	// is. Default value is all.
	// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is. Default value is `all`.
	// - Choices: `all`, `attributes`
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// (String) Neighbor specific description
	// Neighbor specific description
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// hop away EBGP peer using loopback address
	// one-hop away EBGP peer using loopback address
	DisableConnectedCheck *bool `json:"disableConnectedCheck,omitempty" tf:"disable_connected_check,omitempty"`

	// hop ebgp peers, delete ebgp-multihop directly.
	// Allow EBGP neighbors not on directly connected networks. For single-hop ebgp peers, delete ebgp-multihop directly.
	EbgpMultihop *bool `json:"ebgpMultihop,omitempty" tf:"ebgp_multihop,omitempty"`

	// Range: 2-255
	//
	// - Range: `2`-`255`
	EbgpMultihopMaxHop *float64 `json:"ebgpMultihopMaxHop,omitempty" tf:"ebgp_multihop_max_hop,omitempty"`

	// (String) The path of the object.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// session template
	// Inherit a peer-session template
	InheritPeerSession *string `json:"inheritPeerSession,omitempty" tf:"inherit_peer_session,omitempty"`

	// as
	// Specify a BGP neighbor remote-as
	RemoteAs *string `json:"remoteAs,omitempty" tf:"remote_as,omitempty"`

	// (String)
	TemplateName *string `json:"templateName,omitempty" tf:"template_name,omitempty"`

	// (Number) Loopback interface
	// Loopback interface
	UpdateSourceInterfaceLoopback *float64 `json:"updateSourceInterfaceLoopback,omitempty" tf:"update_source_interface_loopback,omitempty"`
}

type PeerSessionTemplateParameters struct {

	// (Boolean) accept ao mismatch connections
	// accept ao mismatch connections
	// +kubebuilder:validation:Optional
	AoAcceptMismatchConnections *bool `json:"aoAcceptMismatchConnections,omitempty" tf:"ao_accept_mismatch_connections,omitempty"`

	// (Boolean) Include TCP options
	// Include TCP options
	// +kubebuilder:validation:Optional
	AoIncludeTCPOptions *bool `json:"aoIncludeTcpOptions,omitempty" tf:"ao_include_tcp_options,omitempty"`

	// (String) Key Chain Name
	// Key Chain Name
	// +kubebuilder:validation:Optional
	AoKeychain *string `json:"aoKeychain,omitempty" tf:"ao_keychain,omitempty"`

	// (String)
	// +crossplane:generate:reference:type=github.com/upbound/provider-upjet-iosxe/apis/cluster/bgp/v1alpha1.BGP
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("asn",false)
	// +kubebuilder:validation:Optional
	Asn *string `json:"asn,omitempty" tf:"asn,omitempty"`

	// Reference to a BGP in bgp to populate asn.
	// +kubebuilder:validation:Optional
	AsnRef *v2.Reference `json:"asnRef,omitempty" tf:"-"`

	// Selector for a BGP in bgp to populate asn.
	// +kubebuilder:validation:Optional
	AsnSelector *v2.Selector `json:"asnSelector,omitempty" tf:"-"`

	// is. Default value is all.
	// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is. Default value is `all`.
	// - Choices: `all`, `attributes`
	// +kubebuilder:validation:Optional
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// (String) Neighbor specific description
	// Neighbor specific description
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	// +kubebuilder:validation:Optional
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// hop away EBGP peer using loopback address
	// one-hop away EBGP peer using loopback address
	// +kubebuilder:validation:Optional
	DisableConnectedCheck *bool `json:"disableConnectedCheck,omitempty" tf:"disable_connected_check,omitempty"`

	// hop ebgp peers, delete ebgp-multihop directly.
	// Allow EBGP neighbors not on directly connected networks. For single-hop ebgp peers, delete ebgp-multihop directly.
	// +kubebuilder:validation:Optional
	EbgpMultihop *bool `json:"ebgpMultihop,omitempty" tf:"ebgp_multihop,omitempty"`

	// Range: 2-255
	//
	// - Range: `2`-`255`
	// +kubebuilder:validation:Optional
	EbgpMultihopMaxHop *float64 `json:"ebgpMultihopMaxHop,omitempty" tf:"ebgp_multihop_max_hop,omitempty"`

	// session template
	// Inherit a peer-session template
	// +kubebuilder:validation:Optional
	InheritPeerSession *string `json:"inheritPeerSession,omitempty" tf:"inherit_peer_session,omitempty"`

	// as
	// Specify a BGP neighbor remote-as
	// +kubebuilder:validation:Optional
	RemoteAs *string `json:"remoteAs,omitempty" tf:"remote_as,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	TemplateName *string `json:"templateName,omitempty" tf:"template_name,omitempty"`

	// (Number) Loopback interface
	// Loopback interface
	// +kubebuilder:validation:Optional
	UpdateSourceInterfaceLoopback *float64 `json:"updateSourceInterfaceLoopback,omitempty" tf:"update_source_interface_loopback,omitempty"`
}

// PeerSessionTemplateSpec defines the desired state of PeerSessionTemplate
type PeerSessionTemplateSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   PeerSessionTemplateParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PeerSessionTemplateInitParameters `json:"initProvider,omitempty"`
}

// PeerSessionTemplateStatus defines the observed state of PeerSessionTemplate.
type PeerSessionTemplateStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               PeerSessionTemplateObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// PeerSessionTemplate is the Schema for the PeerSessionTemplates API. This resource can manage the BGP Peer Session Template configuration.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,iosxe}
type PeerSessionTemplate struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.templateName) || (has(self.initProvider) && has(self.initProvider.templateName))",message="spec.forProvider.templateName is a required parameter"
	Spec   PeerSessionTemplateSpec   `json:"spec"`
	Status PeerSessionTemplateStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PeerSessionTemplateList contains a list of PeerSessionTemplates
type PeerSessionTemplateList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PeerSessionTemplate `json:"items"`
}

// Repository type metadata.
var (
	PeerSessionTemplate_Kind             = "PeerSessionTemplate"
	PeerSessionTemplate_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: PeerSessionTemplate_Kind}.String()
	PeerSessionTemplate_KindAPIVersion   = PeerSessionTemplate_Kind + "." + CRDGroupVersion.String()
	PeerSessionTemplate_GroupVersionKind = CRDGroupVersion.WithKind(PeerSessionTemplate_Kind)
)

func init() {
	SchemeBuilder.Register(&PeerSessionTemplate{}, &PeerSessionTemplateList{})
}
