apiVersion: mpls.iosxe.m.upbound.io/v1alpha1
kind: MPLS
metadata:
  annotations:
    meta.upbound.io/example-id: mpls/v1alpha1/mpls
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: crossplane-system
spec:
  forProvider:
    labelModeAllVrfsAllAfsPerVrf: true
