apiVersion: switching.iosxe.upbound.io/v1alpha1
kind: VLANAccessMap
metadata:
  annotations:
    meta.upbound.io/example-id: switching/v1alpha1/vlanaccessmap
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    action: forward
    matchIpAddress:
    - ACL1
    matchIpv6Address:
    - ACL2
    name: VAM1
    sequence: 10
