apiVersion: switching.iosxe.upbound.io/v1alpha1
kind: VLAN
metadata:
  annotations:
    meta.upbound.io/example-id: switching/v1alpha1/vlan
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    name: Vlan123
    shutdown: false
    vlanId: 123
