apiVersion: switching.iosxe.upbound.io/v1alpha1
kind: VLANConfiguration
metadata:
  annotations:
    meta.upbound.io/example-id: switching/v1alpha1/vlanconfiguration
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    evpnInstanceLegacy: 123
    evpnInstanceVniLegacy: 10123
    vlanId: "123"
