apiVersion: security.iosxe.upbound.io/v1alpha1
kind: ParameterMap
metadata:
  annotations:
    meta.upbound.io/example-id: security/v1alpha1/parametermap
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    icmpIdleTime: 10
    name: PM_INSPECT1
    sessionsMaximum: 10000
    tcpIdleTime: 3600
    tcpMaxIncompleteHost: 100
