// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ClockInitParameters struct {

	// (Boolean) Calendar time is authoritative
	// Calendar time is authoritative
	CalendarValid *bool `json:"calendarValid,omitempty" tf:"calendar_valid,omitempty"`

	// is. Default value is all.
	// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is. Default value is `all`.
	// - Choices: `all`, `attributes`
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// (Boolean) Configure absolute summer time
	// Configure absolute summer time
	SummerTimeDate *bool `json:"summerTimeDate,omitempty" tf:"summer_time_date,omitempty"`

	// Range: 1-31
	//
	// - Range: `1`-`31`
	SummerTimeDateEndDay *float64 `json:"summerTimeDateEndDay,omitempty" tf:"summer_time_date_end_day,omitempty"`

	// Choices: Apr, Aug, Dec, Feb, Jan, Jul, Jun, Mar, May, Nov, Oct, Sep
	//
	// - Choices: `Apr`, `Aug`, `Dec`, `Feb`, `Jan`, `Jul`, `Jun`, `Mar`, `May`, `Nov`, `Oct`, `Sep`
	SummerTimeDateEndMonth *string `json:"summerTimeDateEndMonth,omitempty" tf:"summer_time_date_end_month,omitempty"`

	// (String)
	SummerTimeDateEndTime *string `json:"summerTimeDateEndTime,omitempty" tf:"summer_time_date_end_time,omitempty"`

	// Range: 1993-2035
	//
	// - Range: `1993`-`2035`
	SummerTimeDateEndYear *float64 `json:"summerTimeDateEndYear,omitempty" tf:"summer_time_date_end_year,omitempty"`

	// Range: 1-1440
	//
	// - Range: `1`-`1440`
	SummerTimeDateOffset *float64 `json:"summerTimeDateOffset,omitempty" tf:"summer_time_date_offset,omitempty"`

	// Range: 1-31
	//
	// - Range: `1`-`31`
	SummerTimeDateStartDay *float64 `json:"summerTimeDateStartDay,omitempty" tf:"summer_time_date_start_day,omitempty"`

	// Choices: Apr, Aug, Dec, Feb, Jan, Jul, Jun, Mar, May, Nov, Oct, Sep
	//
	// - Choices: `Apr`, `Aug`, `Dec`, `Feb`, `Jan`, `Jul`, `Jun`, `Mar`, `May`, `Nov`, `Oct`, `Sep`
	SummerTimeDateStartMonth *string `json:"summerTimeDateStartMonth,omitempty" tf:"summer_time_date_start_month,omitempty"`

	// (String)
	SummerTimeDateStartTime *string `json:"summerTimeDateStartTime,omitempty" tf:"summer_time_date_start_time,omitempty"`

	// Range: 1993-2035
	//
	// - Range: `1993`-`2035`
	SummerTimeDateStartYear *float64 `json:"summerTimeDateStartYear,omitempty" tf:"summer_time_date_start_year,omitempty"`

	// (Boolean) Configure recurring summer time
	// Configure recurring summer time
	SummerTimeRecurring *bool `json:"summerTimeRecurring,omitempty" tf:"summer_time_recurring,omitempty"`

	// Choices: Apr, Aug, Dec, Feb, Jan, Jul, Jun, Mar, May, Nov, Oct, Sep
	//
	// - Choices: `Apr`, `Aug`, `Dec`, `Feb`, `Jan`, `Jul`, `Jun`, `Mar`, `May`, `Nov`, `Oct`, `Sep`
	SummerTimeRecurringEndMonth *string `json:"summerTimeRecurringEndMonth,omitempty" tf:"summer_time_recurring_end_month,omitempty"`

	// (String)
	SummerTimeRecurringEndTime *string `json:"summerTimeRecurringEndTime,omitempty" tf:"summer_time_recurring_end_time,omitempty"`

	// (String)
	SummerTimeRecurringEndWeek *string `json:"summerTimeRecurringEndWeek,omitempty" tf:"summer_time_recurring_end_week,omitempty"`

	// Choices: Fri, Mon, Sat, Sun, Thu, Tue, Wed
	//
	// - Choices: `Fri`, `Mon`, `Sat`, `Sun`, `Thu`, `Tue`, `Wed`
	SummerTimeRecurringEndWeekday *string `json:"summerTimeRecurringEndWeekday,omitempty" tf:"summer_time_recurring_end_weekday,omitempty"`

	// Range: 1-1440
	//
	// - Range: `1`-`1440`
	SummerTimeRecurringOffset *float64 `json:"summerTimeRecurringOffset,omitempty" tf:"summer_time_recurring_offset,omitempty"`

	// Choices: Apr, Aug, Dec, Feb, Jan, Jul, Jun, Mar, May, Nov, Oct, Sep
	//
	// - Choices: `Apr`, `Aug`, `Dec`, `Feb`, `Jan`, `Jul`, `Jun`, `Mar`, `May`, `Nov`, `Oct`, `Sep`
	SummerTimeRecurringStartMonth *string `json:"summerTimeRecurringStartMonth,omitempty" tf:"summer_time_recurring_start_month,omitempty"`

	// (String)
	SummerTimeRecurringStartTime *string `json:"summerTimeRecurringStartTime,omitempty" tf:"summer_time_recurring_start_time,omitempty"`

	// (String)
	SummerTimeRecurringStartWeek *string `json:"summerTimeRecurringStartWeek,omitempty" tf:"summer_time_recurring_start_week,omitempty"`

	// Choices: Fri, Mon, Sat, Sun, Thu, Tue, Wed
	//
	// - Choices: `Fri`, `Mon`, `Sat`, `Sun`, `Thu`, `Tue`, `Wed`
	SummerTimeRecurringStartWeekday *string `json:"summerTimeRecurringStartWeekday,omitempty" tf:"summer_time_recurring_start_weekday,omitempty"`

	// (String) Name of time zone in summer
	// Name of time zone in summer
	SummerTimeZone *string `json:"summerTimeZone,omitempty" tf:"summer_time_zone,omitempty"`

	// (String) Name of time zone
	// Name of time zone
	Timezone *string `json:"timezone,omitempty" tf:"timezone,omitempty"`

	// Range: -23-23
	//
	// - Range: `-23`-`23`
	TimezoneOffsetHours *float64 `json:"timezoneOffsetHours,omitempty" tf:"timezone_offset_hours,omitempty"`

	// Range: 0-59
	//
	// - Range: `0`-`59`
	TimezoneOffsetMinutes *float64 `json:"timezoneOffsetMinutes,omitempty" tf:"timezone_offset_minutes,omitempty"`
}

type ClockObservation struct {

	// (Boolean) Calendar time is authoritative
	// Calendar time is authoritative
	CalendarValid *bool `json:"calendarValid,omitempty" tf:"calendar_valid,omitempty"`

	// is. Default value is all.
	// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is. Default value is `all`.
	// - Choices: `all`, `attributes`
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// (String) The path of the object.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean) Configure absolute summer time
	// Configure absolute summer time
	SummerTimeDate *bool `json:"summerTimeDate,omitempty" tf:"summer_time_date,omitempty"`

	// Range: 1-31
	//
	// - Range: `1`-`31`
	SummerTimeDateEndDay *float64 `json:"summerTimeDateEndDay,omitempty" tf:"summer_time_date_end_day,omitempty"`

	// Choices: Apr, Aug, Dec, Feb, Jan, Jul, Jun, Mar, May, Nov, Oct, Sep
	//
	// - Choices: `Apr`, `Aug`, `Dec`, `Feb`, `Jan`, `Jul`, `Jun`, `Mar`, `May`, `Nov`, `Oct`, `Sep`
	SummerTimeDateEndMonth *string `json:"summerTimeDateEndMonth,omitempty" tf:"summer_time_date_end_month,omitempty"`

	// (String)
	SummerTimeDateEndTime *string `json:"summerTimeDateEndTime,omitempty" tf:"summer_time_date_end_time,omitempty"`

	// Range: 1993-2035
	//
	// - Range: `1993`-`2035`
	SummerTimeDateEndYear *float64 `json:"summerTimeDateEndYear,omitempty" tf:"summer_time_date_end_year,omitempty"`

	// Range: 1-1440
	//
	// - Range: `1`-`1440`
	SummerTimeDateOffset *float64 `json:"summerTimeDateOffset,omitempty" tf:"summer_time_date_offset,omitempty"`

	// Range: 1-31
	//
	// - Range: `1`-`31`
	SummerTimeDateStartDay *float64 `json:"summerTimeDateStartDay,omitempty" tf:"summer_time_date_start_day,omitempty"`

	// Choices: Apr, Aug, Dec, Feb, Jan, Jul, Jun, Mar, May, Nov, Oct, Sep
	//
	// - Choices: `Apr`, `Aug`, `Dec`, `Feb`, `Jan`, `Jul`, `Jun`, `Mar`, `May`, `Nov`, `Oct`, `Sep`
	SummerTimeDateStartMonth *string `json:"summerTimeDateStartMonth,omitempty" tf:"summer_time_date_start_month,omitempty"`

	// (String)
	SummerTimeDateStartTime *string `json:"summerTimeDateStartTime,omitempty" tf:"summer_time_date_start_time,omitempty"`

	// Range: 1993-2035
	//
	// - Range: `1993`-`2035`
	SummerTimeDateStartYear *float64 `json:"summerTimeDateStartYear,omitempty" tf:"summer_time_date_start_year,omitempty"`

	// (Boolean) Configure recurring summer time
	// Configure recurring summer time
	SummerTimeRecurring *bool `json:"summerTimeRecurring,omitempty" tf:"summer_time_recurring,omitempty"`

	// Choices: Apr, Aug, Dec, Feb, Jan, Jul, Jun, Mar, May, Nov, Oct, Sep
	//
	// - Choices: `Apr`, `Aug`, `Dec`, `Feb`, `Jan`, `Jul`, `Jun`, `Mar`, `May`, `Nov`, `Oct`, `Sep`
	SummerTimeRecurringEndMonth *string `json:"summerTimeRecurringEndMonth,omitempty" tf:"summer_time_recurring_end_month,omitempty"`

	// (String)
	SummerTimeRecurringEndTime *string `json:"summerTimeRecurringEndTime,omitempty" tf:"summer_time_recurring_end_time,omitempty"`

	// (String)
	SummerTimeRecurringEndWeek *string `json:"summerTimeRecurringEndWeek,omitempty" tf:"summer_time_recurring_end_week,omitempty"`

	// Choices: Fri, Mon, Sat, Sun, Thu, Tue, Wed
	//
	// - Choices: `Fri`, `Mon`, `Sat`, `Sun`, `Thu`, `Tue`, `Wed`
	SummerTimeRecurringEndWeekday *string `json:"summerTimeRecurringEndWeekday,omitempty" tf:"summer_time_recurring_end_weekday,omitempty"`

	// Range: 1-1440
	//
	// - Range: `1`-`1440`
	SummerTimeRecurringOffset *float64 `json:"summerTimeRecurringOffset,omitempty" tf:"summer_time_recurring_offset,omitempty"`

	// Choices: Apr, Aug, Dec, Feb, Jan, Jul, Jun, Mar, May, Nov, Oct, Sep
	//
	// - Choices: `Apr`, `Aug`, `Dec`, `Feb`, `Jan`, `Jul`, `Jun`, `Mar`, `May`, `Nov`, `Oct`, `Sep`
	SummerTimeRecurringStartMonth *string `json:"summerTimeRecurringStartMonth,omitempty" tf:"summer_time_recurring_start_month,omitempty"`

	// (String)
	SummerTimeRecurringStartTime *string `json:"summerTimeRecurringStartTime,omitempty" tf:"summer_time_recurring_start_time,omitempty"`

	// (String)
	SummerTimeRecurringStartWeek *string `json:"summerTimeRecurringStartWeek,omitempty" tf:"summer_time_recurring_start_week,omitempty"`

	// Choices: Fri, Mon, Sat, Sun, Thu, Tue, Wed
	//
	// - Choices: `Fri`, `Mon`, `Sat`, `Sun`, `Thu`, `Tue`, `Wed`
	SummerTimeRecurringStartWeekday *string `json:"summerTimeRecurringStartWeekday,omitempty" tf:"summer_time_recurring_start_weekday,omitempty"`

	// (String) Name of time zone in summer
	// Name of time zone in summer
	SummerTimeZone *string `json:"summerTimeZone,omitempty" tf:"summer_time_zone,omitempty"`

	// (String) Name of time zone
	// Name of time zone
	Timezone *string `json:"timezone,omitempty" tf:"timezone,omitempty"`

	// Range: -23-23
	//
	// - Range: `-23`-`23`
	TimezoneOffsetHours *float64 `json:"timezoneOffsetHours,omitempty" tf:"timezone_offset_hours,omitempty"`

	// Range: 0-59
	//
	// - Range: `0`-`59`
	TimezoneOffsetMinutes *float64 `json:"timezoneOffsetMinutes,omitempty" tf:"timezone_offset_minutes,omitempty"`
}

type ClockParameters struct {

	// (Boolean) Calendar time is authoritative
	// Calendar time is authoritative
	// +kubebuilder:validation:Optional
	CalendarValid *bool `json:"calendarValid,omitempty" tf:"calendar_valid,omitempty"`

	// is. Default value is all.
	// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is. Default value is `all`.
	// - Choices: `all`, `attributes`
	// +kubebuilder:validation:Optional
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	// +kubebuilder:validation:Optional
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// (Boolean) Configure absolute summer time
	// Configure absolute summer time
	// +kubebuilder:validation:Optional
	SummerTimeDate *bool `json:"summerTimeDate,omitempty" tf:"summer_time_date,omitempty"`

	// Range: 1-31
	//
	// - Range: `1`-`31`
	// +kubebuilder:validation:Optional
	SummerTimeDateEndDay *float64 `json:"summerTimeDateEndDay,omitempty" tf:"summer_time_date_end_day,omitempty"`

	// Choices: Apr, Aug, Dec, Feb, Jan, Jul, Jun, Mar, May, Nov, Oct, Sep
	//
	// - Choices: `Apr`, `Aug`, `Dec`, `Feb`, `Jan`, `Jul`, `Jun`, `Mar`, `May`, `Nov`, `Oct`, `Sep`
	// +kubebuilder:validation:Optional
	SummerTimeDateEndMonth *string `json:"summerTimeDateEndMonth,omitempty" tf:"summer_time_date_end_month,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	SummerTimeDateEndTime *string `json:"summerTimeDateEndTime,omitempty" tf:"summer_time_date_end_time,omitempty"`

	// Range: 1993-2035
	//
	// - Range: `1993`-`2035`
	// +kubebuilder:validation:Optional
	SummerTimeDateEndYear *float64 `json:"summerTimeDateEndYear,omitempty" tf:"summer_time_date_end_year,omitempty"`

	// Range: 1-1440
	//
	// - Range: `1`-`1440`
	// +kubebuilder:validation:Optional
	SummerTimeDateOffset *float64 `json:"summerTimeDateOffset,omitempty" tf:"summer_time_date_offset,omitempty"`

	// Range: 1-31
	//
	// - Range: `1`-`31`
	// +kubebuilder:validation:Optional
	SummerTimeDateStartDay *float64 `json:"summerTimeDateStartDay,omitempty" tf:"summer_time_date_start_day,omitempty"`

	// Choices: Apr, Aug, Dec, Feb, Jan, Jul, Jun, Mar, May, Nov, Oct, Sep
	//
	// - Choices: `Apr`, `Aug`, `Dec`, `Feb`, `Jan`, `Jul`, `Jun`, `Mar`, `May`, `Nov`, `Oct`, `Sep`
	// +kubebuilder:validation:Optional
	SummerTimeDateStartMonth *string `json:"summerTimeDateStartMonth,omitempty" tf:"summer_time_date_start_month,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	SummerTimeDateStartTime *string `json:"summerTimeDateStartTime,omitempty" tf:"summer_time_date_start_time,omitempty"`

	// Range: 1993-2035
	//
	// - Range: `1993`-`2035`
	// +kubebuilder:validation:Optional
	SummerTimeDateStartYear *float64 `json:"summerTimeDateStartYear,omitempty" tf:"summer_time_date_start_year,omitempty"`

	// (Boolean) Configure recurring summer time
	// Configure recurring summer time
	// +kubebuilder:validation:Optional
	SummerTimeRecurring *bool `json:"summerTimeRecurring,omitempty" tf:"summer_time_recurring,omitempty"`

	// Choices: Apr, Aug, Dec, Feb, Jan, Jul, Jun, Mar, May, Nov, Oct, Sep
	//
	// - Choices: `Apr`, `Aug`, `Dec`, `Feb`, `Jan`, `Jul`, `Jun`, `Mar`, `May`, `Nov`, `Oct`, `Sep`
	// +kubebuilder:validation:Optional
	SummerTimeRecurringEndMonth *string `json:"summerTimeRecurringEndMonth,omitempty" tf:"summer_time_recurring_end_month,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	SummerTimeRecurringEndTime *string `json:"summerTimeRecurringEndTime,omitempty" tf:"summer_time_recurring_end_time,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	SummerTimeRecurringEndWeek *string `json:"summerTimeRecurringEndWeek,omitempty" tf:"summer_time_recurring_end_week,omitempty"`

	// Choices: Fri, Mon, Sat, Sun, Thu, Tue, Wed
	//
	// - Choices: `Fri`, `Mon`, `Sat`, `Sun`, `Thu`, `Tue`, `Wed`
	// +kubebuilder:validation:Optional
	SummerTimeRecurringEndWeekday *string `json:"summerTimeRecurringEndWeekday,omitempty" tf:"summer_time_recurring_end_weekday,omitempty"`

	// Range: 1-1440
	//
	// - Range: `1`-`1440`
	// +kubebuilder:validation:Optional
	SummerTimeRecurringOffset *float64 `json:"summerTimeRecurringOffset,omitempty" tf:"summer_time_recurring_offset,omitempty"`

	// Choices: Apr, Aug, Dec, Feb, Jan, Jul, Jun, Mar, May, Nov, Oct, Sep
	//
	// - Choices: `Apr`, `Aug`, `Dec`, `Feb`, `Jan`, `Jul`, `Jun`, `Mar`, `May`, `Nov`, `Oct`, `Sep`
	// +kubebuilder:validation:Optional
	SummerTimeRecurringStartMonth *string `json:"summerTimeRecurringStartMonth,omitempty" tf:"summer_time_recurring_start_month,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	SummerTimeRecurringStartTime *string `json:"summerTimeRecurringStartTime,omitempty" tf:"summer_time_recurring_start_time,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	SummerTimeRecurringStartWeek *string `json:"summerTimeRecurringStartWeek,omitempty" tf:"summer_time_recurring_start_week,omitempty"`

	// Choices: Fri, Mon, Sat, Sun, Thu, Tue, Wed
	//
	// - Choices: `Fri`, `Mon`, `Sat`, `Sun`, `Thu`, `Tue`, `Wed`
	// +kubebuilder:validation:Optional
	SummerTimeRecurringStartWeekday *string `json:"summerTimeRecurringStartWeekday,omitempty" tf:"summer_time_recurring_start_weekday,omitempty"`

	// (String) Name of time zone in summer
	// Name of time zone in summer
	// +kubebuilder:validation:Optional
	SummerTimeZone *string `json:"summerTimeZone,omitempty" tf:"summer_time_zone,omitempty"`

	// (String) Name of time zone
	// Name of time zone
	// +kubebuilder:validation:Optional
	Timezone *string `json:"timezone,omitempty" tf:"timezone,omitempty"`

	// Range: -23-23
	//
	// - Range: `-23`-`23`
	// +kubebuilder:validation:Optional
	TimezoneOffsetHours *float64 `json:"timezoneOffsetHours,omitempty" tf:"timezone_offset_hours,omitempty"`

	// Range: 0-59
	//
	// - Range: `0`-`59`
	// +kubebuilder:validation:Optional
	TimezoneOffsetMinutes *float64 `json:"timezoneOffsetMinutes,omitempty" tf:"timezone_offset_minutes,omitempty"`
}

// ClockSpec defines the desired state of Clock
type ClockSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   ClockParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ClockInitParameters `json:"initProvider,omitempty"`
}

// ClockStatus defines the observed state of Clock.
type ClockStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ClockObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Clock is the Schema for the Clocks API. This resource can manage the Clock configuration.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,iosxe}
type Clock struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ClockSpec   `json:"spec"`
	Status            ClockStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ClockList contains a list of Clocks
type ClockList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Clock `json:"items"`
}

// Repository type metadata.
var (
	Clock_Kind             = "Clock"
	Clock_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Clock_Kind}.String()
	Clock_KindAPIVersion   = Clock_Kind + "." + CRDGroupVersion.String()
	Clock_GroupVersionKind = CRDGroupVersion.WithKind(Clock_Kind)
)

func init() {
	SchemeBuilder.Register(&Clock{}, &ClockList{})
}
