// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ActionNumbersInitParameters struct {

	// (String) activate interface template
	// activate interface template
	ActivateInterfaceTemplate *string `json:"activateInterfaceTemplate,omitempty" tf:"activate_interface_template,omitempty"`

	// (String) policy type control subscriber
	// policy type control subscriber
	ActivatePolicyTypeControlSubscriber *string `json:"activatePolicyTypeControlSubscriber,omitempty" tf:"activate_policy_type_control_subscriber,omitempty"`

	// (String) Named Method List
	// Named Method List
	ActivateServiceTemplateConfigAaaList *string `json:"activateServiceTemplateConfigAaaList,omitempty" tf:"activate_service_template_config_aaa_list,omitempty"`

	// (Number) Template precedence
	// Template precedence
	// - Range: `1`-`254`
	ActivateServiceTemplateConfigPrecedence *float64 `json:"activateServiceTemplateConfigPrecedence,omitempty" tf:"activate_service_template_config_precedence,omitempty"`

	// (Boolean) Replace all existing authorization data and services
	// Replace all existing authorization data and services
	ActivateServiceTemplateConfigReplaceAll *bool `json:"activateServiceTemplateConfigReplaceAll,omitempty" tf:"activate_service_template_config_replace_all,omitempty"`

	// (String) activate service template
	// activate service template
	ActivateServiceTemplateConfigServiceTemplate *string `json:"activateServiceTemplateConfigServiceTemplate,omitempty" tf:"activate_service_template_config_service_template,omitempty"`

	// (String) Specify authentication method list. Use this for versions before 17.18.
	// Specify authentication method list. Use this for versions before `17.18`.
	AuthenticateUsingAaaAuthcListLegacy *string `json:"authenticateUsingAaaAuthcListLegacy,omitempty" tf:"authenticate_using_aaa_authc_list_legacy,omitempty"`

	// (String) Specify authorization method list. Use this for versions before 17.18.
	// Specify authorization method list. Use this for versions before `17.18`.
	AuthenticateUsingAaaAuthzListLegacy *string `json:"authenticateUsingAaaAuthzListLegacy,omitempty" tf:"authenticate_using_aaa_authz_list_legacy,omitempty"`

	// (Boolean) Configure AAA method list. Required when using authenticate_using_authc_list or authenticate_using_authz_list (versions 17.18 and later).
	// Configure AAA method list. Required when using `authenticate_using_authc_list` or `authenticate_using_authz_list` (versions `17.18` and later).
	AuthenticateUsingAaaConfig *bool `json:"authenticateUsingAaaConfig,omitempty" tf:"authenticate_using_aaa_config,omitempty"`

	// (String) Specify authentication method list. Use this for versions 17.18 and later.
	// Specify authentication method list. Use this for versions `17.18` and later.
	AuthenticateUsingAuthcList *string `json:"authenticateUsingAuthcList,omitempty" tf:"authenticate_using_authc_list,omitempty"`

	// (String) Specify authorization method list. Use this for versions 17.18 and later.
	// Specify authorization method list. Use this for versions `17.18` and later.
	AuthenticateUsingAuthzList *string `json:"authenticateUsingAuthzList,omitempty" tf:"authenticate_using_authz_list,omitempty"`

	// (Boolean) Enabling Dot1x Authenticator & Supplicant
	// Enabling Dot1x Authenticator & Supplicant
	AuthenticateUsingBoth *bool `json:"authenticateUsingBoth,omitempty" tf:"authenticate_using_both,omitempty"`

	// (String) method/protocol to be used for authentication
	// method/protocol to be used for authentication
	// - Choices: `dot1x`, `mab`, `webauth`
	AuthenticateUsingMethod *string `json:"authenticateUsingMethod,omitempty" tf:"authenticate_using_method,omitempty"`

	// (String) Specify parameter map name
	// Specify parameter map name
	AuthenticateUsingParameterMap *string `json:"authenticateUsingParameterMap,omitempty" tf:"authenticate_using_parameter_map,omitempty"`

	// (Number) Method priority
	// Method priority
	// - Range: `1`-`254`
	AuthenticateUsingPriority *float64 `json:"authenticateUsingPriority,omitempty" tf:"authenticate_using_priority,omitempty"`

	// (Number) Number of times to retry failed authentications
	// Number of times to retry failed authentications
	// - Range: `1`-`5`
	AuthenticateUsingRetries *float64 `json:"authenticateUsingRetries,omitempty" tf:"authenticate_using_retries,omitempty"`

	// (Number) Time interval between retries
	// Time interval between retries
	// - Range: `0`-`65535`
	AuthenticateUsingRetryTime *float64 `json:"authenticateUsingRetryTime,omitempty" tf:"authenticate_using_retry_time,omitempty"`

	// (Number) restarts the auth sequence after the specified number of sec
	// restarts the auth sequence after the specified number of sec
	// - Range: `1`-`65535`
	AuthenticationRestart *float64 `json:"authenticationRestart,omitempty" tf:"authentication_restart,omitempty"`

	// (Boolean) authorize session
	// authorize session
	Authorize *bool `json:"authorize,omitempty" tf:"authorize,omitempty"`

	// (Boolean) clears authenticated data hosts on the port
	// clears authenticated data hosts on the port
	ClearAuthenticatedDataHostsOnPort *bool `json:"clearAuthenticatedDataHostsOnPort,omitempty" tf:"clear_authenticated_data_hosts_on_port,omitempty"`

	// (Boolean) clears an active session
	// clears an active session
	ClearSession *bool `json:"clearSession,omitempty" tf:"clear_session,omitempty"`

	// (String) activate interface template
	// activate interface template
	DeactivateInterfaceTemplate *string `json:"deactivateInterfaceTemplate,omitempty" tf:"deactivate_interface_template,omitempty"`

	// (String) policy type control subscriber
	// policy type control subscriber
	DeactivatePolicyTypeControlSubscriber *string `json:"deactivatePolicyTypeControlSubscriber,omitempty" tf:"deactivate_policy_type_control_subscriber,omitempty"`

	// (String) activate service template
	// activate service template
	DeactivateServiceTemplate *string `json:"deactivateServiceTemplate,omitempty" tf:"deactivate_service_template,omitempty"`

	// (Boolean) temporarily disable port
	// temporarily disable port
	ErrDisable *bool `json:"errDisable,omitempty" tf:"err_disable,omitempty"`

	// update attribute to a auto-conf templates
	// map identity-update attribute to a auto-conf templates
	MapAttributeToServiceTable *string `json:"mapAttributeToServiceTable,omitempty" tf:"map_attribute_to_service_table,omitempty"`

	// (Boolean) notifies the session attributes
	// notifies the session attributes
	Notify *bool `json:"notify,omitempty" tf:"notify,omitempty"`

	// (Number) class number, 1 for 1st class, 2 for 2nd...
	// action number, 1 for 1st class, 2 for 2nd...
	// - Range: `1`-`254`
	Number *float64 `json:"number,omitempty" tf:"number,omitempty"`

	// (Boolean) pause reauthentication
	// pause reauthentication
	PauseReauthentication *bool `json:"pauseReauthentication,omitempty" tf:"pause_reauthentication,omitempty"`

	// (Boolean) silently drop violating packets
	// silently drop violating packets
	Protect *bool `json:"protect,omitempty" tf:"protect,omitempty"`

	// (Boolean) clear existing session and create session for violating host
	// clear existing session and create session for violating host
	Replace *bool `json:"replace,omitempty" tf:"replace,omitempty"`

	// (Boolean) drop violating packets and generate a syslog
	// drop violating packets and generate a syslog
	Restrict *bool `json:"restrict,omitempty" tf:"restrict,omitempty"`

	// (Boolean) resume reauthentication
	// resume reauthentication
	ResumeReauthentication *bool `json:"resumeReauthentication,omitempty" tf:"resume_reauthentication,omitempty"`

	// (String) set domain
	// set domain
	// - Choices: `data`, `switch`, `voice`
	SetDomain *string `json:"setDomain,omitempty" tf:"set_domain,omitempty"`

	// (String) timer name
	// timer name
	SetTimerName *string `json:"setTimerName,omitempty" tf:"set_timer_name,omitempty"`

	// (Number) Enter a value between 1 and 65535
	// Enter a value between 1 and 65535
	// - Range: `0`-`65535`
	SetTimerValue *float64 `json:"setTimerValue,omitempty" tf:"set_timer_value,omitempty"`

	// (String) terminate auth method
	// terminate auth method
	// - Choices: `dot1x`, `mab`, `webauth`
	TerminateConfig *string `json:"terminateConfig,omitempty" tf:"terminate_config,omitempty"`

	// (Boolean) unauthorize session
	// unauthorize session
	Unauthorize *bool `json:"unauthorize,omitempty" tf:"unauthorize,omitempty"`
}

type ActionNumbersObservation struct {

	// (String) activate interface template
	// activate interface template
	ActivateInterfaceTemplate *string `json:"activateInterfaceTemplate,omitempty" tf:"activate_interface_template,omitempty"`

	// (String) policy type control subscriber
	// policy type control subscriber
	ActivatePolicyTypeControlSubscriber *string `json:"activatePolicyTypeControlSubscriber,omitempty" tf:"activate_policy_type_control_subscriber,omitempty"`

	// (String) Named Method List
	// Named Method List
	ActivateServiceTemplateConfigAaaList *string `json:"activateServiceTemplateConfigAaaList,omitempty" tf:"activate_service_template_config_aaa_list,omitempty"`

	// (Number) Template precedence
	// Template precedence
	// - Range: `1`-`254`
	ActivateServiceTemplateConfigPrecedence *float64 `json:"activateServiceTemplateConfigPrecedence,omitempty" tf:"activate_service_template_config_precedence,omitempty"`

	// (Boolean) Replace all existing authorization data and services
	// Replace all existing authorization data and services
	ActivateServiceTemplateConfigReplaceAll *bool `json:"activateServiceTemplateConfigReplaceAll,omitempty" tf:"activate_service_template_config_replace_all,omitempty"`

	// (String) activate service template
	// activate service template
	ActivateServiceTemplateConfigServiceTemplate *string `json:"activateServiceTemplateConfigServiceTemplate,omitempty" tf:"activate_service_template_config_service_template,omitempty"`

	// (String) Specify authentication method list. Use this for versions before 17.18.
	// Specify authentication method list. Use this for versions before `17.18`.
	AuthenticateUsingAaaAuthcListLegacy *string `json:"authenticateUsingAaaAuthcListLegacy,omitempty" tf:"authenticate_using_aaa_authc_list_legacy,omitempty"`

	// (String) Specify authorization method list. Use this for versions before 17.18.
	// Specify authorization method list. Use this for versions before `17.18`.
	AuthenticateUsingAaaAuthzListLegacy *string `json:"authenticateUsingAaaAuthzListLegacy,omitempty" tf:"authenticate_using_aaa_authz_list_legacy,omitempty"`

	// (Boolean) Configure AAA method list. Required when using authenticate_using_authc_list or authenticate_using_authz_list (versions 17.18 and later).
	// Configure AAA method list. Required when using `authenticate_using_authc_list` or `authenticate_using_authz_list` (versions `17.18` and later).
	AuthenticateUsingAaaConfig *bool `json:"authenticateUsingAaaConfig,omitempty" tf:"authenticate_using_aaa_config,omitempty"`

	// (String) Specify authentication method list. Use this for versions 17.18 and later.
	// Specify authentication method list. Use this for versions `17.18` and later.
	AuthenticateUsingAuthcList *string `json:"authenticateUsingAuthcList,omitempty" tf:"authenticate_using_authc_list,omitempty"`

	// (String) Specify authorization method list. Use this for versions 17.18 and later.
	// Specify authorization method list. Use this for versions `17.18` and later.
	AuthenticateUsingAuthzList *string `json:"authenticateUsingAuthzList,omitempty" tf:"authenticate_using_authz_list,omitempty"`

	// (Boolean) Enabling Dot1x Authenticator & Supplicant
	// Enabling Dot1x Authenticator & Supplicant
	AuthenticateUsingBoth *bool `json:"authenticateUsingBoth,omitempty" tf:"authenticate_using_both,omitempty"`

	// (String) method/protocol to be used for authentication
	// method/protocol to be used for authentication
	// - Choices: `dot1x`, `mab`, `webauth`
	AuthenticateUsingMethod *string `json:"authenticateUsingMethod,omitempty" tf:"authenticate_using_method,omitempty"`

	// (String) Specify parameter map name
	// Specify parameter map name
	AuthenticateUsingParameterMap *string `json:"authenticateUsingParameterMap,omitempty" tf:"authenticate_using_parameter_map,omitempty"`

	// (Number) Method priority
	// Method priority
	// - Range: `1`-`254`
	AuthenticateUsingPriority *float64 `json:"authenticateUsingPriority,omitempty" tf:"authenticate_using_priority,omitempty"`

	// (Number) Number of times to retry failed authentications
	// Number of times to retry failed authentications
	// - Range: `1`-`5`
	AuthenticateUsingRetries *float64 `json:"authenticateUsingRetries,omitempty" tf:"authenticate_using_retries,omitempty"`

	// (Number) Time interval between retries
	// Time interval between retries
	// - Range: `0`-`65535`
	AuthenticateUsingRetryTime *float64 `json:"authenticateUsingRetryTime,omitempty" tf:"authenticate_using_retry_time,omitempty"`

	// (Number) restarts the auth sequence after the specified number of sec
	// restarts the auth sequence after the specified number of sec
	// - Range: `1`-`65535`
	AuthenticationRestart *float64 `json:"authenticationRestart,omitempty" tf:"authentication_restart,omitempty"`

	// (Boolean) authorize session
	// authorize session
	Authorize *bool `json:"authorize,omitempty" tf:"authorize,omitempty"`

	// (Boolean) clears authenticated data hosts on the port
	// clears authenticated data hosts on the port
	ClearAuthenticatedDataHostsOnPort *bool `json:"clearAuthenticatedDataHostsOnPort,omitempty" tf:"clear_authenticated_data_hosts_on_port,omitempty"`

	// (Boolean) clears an active session
	// clears an active session
	ClearSession *bool `json:"clearSession,omitempty" tf:"clear_session,omitempty"`

	// (String) activate interface template
	// activate interface template
	DeactivateInterfaceTemplate *string `json:"deactivateInterfaceTemplate,omitempty" tf:"deactivate_interface_template,omitempty"`

	// (String) policy type control subscriber
	// policy type control subscriber
	DeactivatePolicyTypeControlSubscriber *string `json:"deactivatePolicyTypeControlSubscriber,omitempty" tf:"deactivate_policy_type_control_subscriber,omitempty"`

	// (String) activate service template
	// activate service template
	DeactivateServiceTemplate *string `json:"deactivateServiceTemplate,omitempty" tf:"deactivate_service_template,omitempty"`

	// (Boolean) temporarily disable port
	// temporarily disable port
	ErrDisable *bool `json:"errDisable,omitempty" tf:"err_disable,omitempty"`

	// update attribute to a auto-conf templates
	// map identity-update attribute to a auto-conf templates
	MapAttributeToServiceTable *string `json:"mapAttributeToServiceTable,omitempty" tf:"map_attribute_to_service_table,omitempty"`

	// (Boolean) notifies the session attributes
	// notifies the session attributes
	Notify *bool `json:"notify,omitempty" tf:"notify,omitempty"`

	// (Number) class number, 1 for 1st class, 2 for 2nd...
	// action number, 1 for 1st class, 2 for 2nd...
	// - Range: `1`-`254`
	Number *float64 `json:"number,omitempty" tf:"number,omitempty"`

	// (Boolean) pause reauthentication
	// pause reauthentication
	PauseReauthentication *bool `json:"pauseReauthentication,omitempty" tf:"pause_reauthentication,omitempty"`

	// (Boolean) silently drop violating packets
	// silently drop violating packets
	Protect *bool `json:"protect,omitempty" tf:"protect,omitempty"`

	// (Boolean) clear existing session and create session for violating host
	// clear existing session and create session for violating host
	Replace *bool `json:"replace,omitempty" tf:"replace,omitempty"`

	// (Boolean) drop violating packets and generate a syslog
	// drop violating packets and generate a syslog
	Restrict *bool `json:"restrict,omitempty" tf:"restrict,omitempty"`

	// (Boolean) resume reauthentication
	// resume reauthentication
	ResumeReauthentication *bool `json:"resumeReauthentication,omitempty" tf:"resume_reauthentication,omitempty"`

	// (String) set domain
	// set domain
	// - Choices: `data`, `switch`, `voice`
	SetDomain *string `json:"setDomain,omitempty" tf:"set_domain,omitempty"`

	// (String) timer name
	// timer name
	SetTimerName *string `json:"setTimerName,omitempty" tf:"set_timer_name,omitempty"`

	// (Number) Enter a value between 1 and 65535
	// Enter a value between 1 and 65535
	// - Range: `0`-`65535`
	SetTimerValue *float64 `json:"setTimerValue,omitempty" tf:"set_timer_value,omitempty"`

	// (String) terminate auth method
	// terminate auth method
	// - Choices: `dot1x`, `mab`, `webauth`
	TerminateConfig *string `json:"terminateConfig,omitempty" tf:"terminate_config,omitempty"`

	// (Boolean) unauthorize session
	// unauthorize session
	Unauthorize *bool `json:"unauthorize,omitempty" tf:"unauthorize,omitempty"`
}

type ActionNumbersParameters struct {

	// (String) activate interface template
	// activate interface template
	// +kubebuilder:validation:Optional
	ActivateInterfaceTemplate *string `json:"activateInterfaceTemplate,omitempty" tf:"activate_interface_template,omitempty"`

	// (String) policy type control subscriber
	// policy type control subscriber
	// +kubebuilder:validation:Optional
	ActivatePolicyTypeControlSubscriber *string `json:"activatePolicyTypeControlSubscriber,omitempty" tf:"activate_policy_type_control_subscriber,omitempty"`

	// (String) Named Method List
	// Named Method List
	// +kubebuilder:validation:Optional
	ActivateServiceTemplateConfigAaaList *string `json:"activateServiceTemplateConfigAaaList,omitempty" tf:"activate_service_template_config_aaa_list,omitempty"`

	// (Number) Template precedence
	// Template precedence
	// - Range: `1`-`254`
	// +kubebuilder:validation:Optional
	ActivateServiceTemplateConfigPrecedence *float64 `json:"activateServiceTemplateConfigPrecedence,omitempty" tf:"activate_service_template_config_precedence,omitempty"`

	// (Boolean) Replace all existing authorization data and services
	// Replace all existing authorization data and services
	// +kubebuilder:validation:Optional
	ActivateServiceTemplateConfigReplaceAll *bool `json:"activateServiceTemplateConfigReplaceAll,omitempty" tf:"activate_service_template_config_replace_all,omitempty"`

	// (String) activate service template
	// activate service template
	// +kubebuilder:validation:Optional
	ActivateServiceTemplateConfigServiceTemplate *string `json:"activateServiceTemplateConfigServiceTemplate,omitempty" tf:"activate_service_template_config_service_template,omitempty"`

	// (String) Specify authentication method list. Use this for versions before 17.18.
	// Specify authentication method list. Use this for versions before `17.18`.
	// +kubebuilder:validation:Optional
	AuthenticateUsingAaaAuthcListLegacy *string `json:"authenticateUsingAaaAuthcListLegacy,omitempty" tf:"authenticate_using_aaa_authc_list_legacy,omitempty"`

	// (String) Specify authorization method list. Use this for versions before 17.18.
	// Specify authorization method list. Use this for versions before `17.18`.
	// +kubebuilder:validation:Optional
	AuthenticateUsingAaaAuthzListLegacy *string `json:"authenticateUsingAaaAuthzListLegacy,omitempty" tf:"authenticate_using_aaa_authz_list_legacy,omitempty"`

	// (Boolean) Configure AAA method list. Required when using authenticate_using_authc_list or authenticate_using_authz_list (versions 17.18 and later).
	// Configure AAA method list. Required when using `authenticate_using_authc_list` or `authenticate_using_authz_list` (versions `17.18` and later).
	// +kubebuilder:validation:Optional
	AuthenticateUsingAaaConfig *bool `json:"authenticateUsingAaaConfig,omitempty" tf:"authenticate_using_aaa_config,omitempty"`

	// (String) Specify authentication method list. Use this for versions 17.18 and later.
	// Specify authentication method list. Use this for versions `17.18` and later.
	// +kubebuilder:validation:Optional
	AuthenticateUsingAuthcList *string `json:"authenticateUsingAuthcList,omitempty" tf:"authenticate_using_authc_list,omitempty"`

	// (String) Specify authorization method list. Use this for versions 17.18 and later.
	// Specify authorization method list. Use this for versions `17.18` and later.
	// +kubebuilder:validation:Optional
	AuthenticateUsingAuthzList *string `json:"authenticateUsingAuthzList,omitempty" tf:"authenticate_using_authz_list,omitempty"`

	// (Boolean) Enabling Dot1x Authenticator & Supplicant
	// Enabling Dot1x Authenticator & Supplicant
	// +kubebuilder:validation:Optional
	AuthenticateUsingBoth *bool `json:"authenticateUsingBoth,omitempty" tf:"authenticate_using_both,omitempty"`

	// (String) method/protocol to be used for authentication
	// method/protocol to be used for authentication
	// - Choices: `dot1x`, `mab`, `webauth`
	// +kubebuilder:validation:Optional
	AuthenticateUsingMethod *string `json:"authenticateUsingMethod,omitempty" tf:"authenticate_using_method,omitempty"`

	// (String) Specify parameter map name
	// Specify parameter map name
	// +kubebuilder:validation:Optional
	AuthenticateUsingParameterMap *string `json:"authenticateUsingParameterMap,omitempty" tf:"authenticate_using_parameter_map,omitempty"`

	// (Number) Method priority
	// Method priority
	// - Range: `1`-`254`
	// +kubebuilder:validation:Optional
	AuthenticateUsingPriority *float64 `json:"authenticateUsingPriority,omitempty" tf:"authenticate_using_priority,omitempty"`

	// (Number) Number of times to retry failed authentications
	// Number of times to retry failed authentications
	// - Range: `1`-`5`
	// +kubebuilder:validation:Optional
	AuthenticateUsingRetries *float64 `json:"authenticateUsingRetries,omitempty" tf:"authenticate_using_retries,omitempty"`

	// (Number) Time interval between retries
	// Time interval between retries
	// - Range: `0`-`65535`
	// +kubebuilder:validation:Optional
	AuthenticateUsingRetryTime *float64 `json:"authenticateUsingRetryTime,omitempty" tf:"authenticate_using_retry_time,omitempty"`

	// (Number) restarts the auth sequence after the specified number of sec
	// restarts the auth sequence after the specified number of sec
	// - Range: `1`-`65535`
	// +kubebuilder:validation:Optional
	AuthenticationRestart *float64 `json:"authenticationRestart,omitempty" tf:"authentication_restart,omitempty"`

	// (Boolean) authorize session
	// authorize session
	// +kubebuilder:validation:Optional
	Authorize *bool `json:"authorize,omitempty" tf:"authorize,omitempty"`

	// (Boolean) clears authenticated data hosts on the port
	// clears authenticated data hosts on the port
	// +kubebuilder:validation:Optional
	ClearAuthenticatedDataHostsOnPort *bool `json:"clearAuthenticatedDataHostsOnPort,omitempty" tf:"clear_authenticated_data_hosts_on_port,omitempty"`

	// (Boolean) clears an active session
	// clears an active session
	// +kubebuilder:validation:Optional
	ClearSession *bool `json:"clearSession,omitempty" tf:"clear_session,omitempty"`

	// (String) activate interface template
	// activate interface template
	// +kubebuilder:validation:Optional
	DeactivateInterfaceTemplate *string `json:"deactivateInterfaceTemplate,omitempty" tf:"deactivate_interface_template,omitempty"`

	// (String) policy type control subscriber
	// policy type control subscriber
	// +kubebuilder:validation:Optional
	DeactivatePolicyTypeControlSubscriber *string `json:"deactivatePolicyTypeControlSubscriber,omitempty" tf:"deactivate_policy_type_control_subscriber,omitempty"`

	// (String) activate service template
	// activate service template
	// +kubebuilder:validation:Optional
	DeactivateServiceTemplate *string `json:"deactivateServiceTemplate,omitempty" tf:"deactivate_service_template,omitempty"`

	// (Boolean) temporarily disable port
	// temporarily disable port
	// +kubebuilder:validation:Optional
	ErrDisable *bool `json:"errDisable,omitempty" tf:"err_disable,omitempty"`

	// update attribute to a auto-conf templates
	// map identity-update attribute to a auto-conf templates
	// +kubebuilder:validation:Optional
	MapAttributeToServiceTable *string `json:"mapAttributeToServiceTable,omitempty" tf:"map_attribute_to_service_table,omitempty"`

	// (Boolean) notifies the session attributes
	// notifies the session attributes
	// +kubebuilder:validation:Optional
	Notify *bool `json:"notify,omitempty" tf:"notify,omitempty"`

	// (Number) class number, 1 for 1st class, 2 for 2nd...
	// action number, 1 for 1st class, 2 for 2nd...
	// - Range: `1`-`254`
	// +kubebuilder:validation:Optional
	Number *float64 `json:"number" tf:"number,omitempty"`

	// (Boolean) pause reauthentication
	// pause reauthentication
	// +kubebuilder:validation:Optional
	PauseReauthentication *bool `json:"pauseReauthentication,omitempty" tf:"pause_reauthentication,omitempty"`

	// (Boolean) silently drop violating packets
	// silently drop violating packets
	// +kubebuilder:validation:Optional
	Protect *bool `json:"protect,omitempty" tf:"protect,omitempty"`

	// (Boolean) clear existing session and create session for violating host
	// clear existing session and create session for violating host
	// +kubebuilder:validation:Optional
	Replace *bool `json:"replace,omitempty" tf:"replace,omitempty"`

	// (Boolean) drop violating packets and generate a syslog
	// drop violating packets and generate a syslog
	// +kubebuilder:validation:Optional
	Restrict *bool `json:"restrict,omitempty" tf:"restrict,omitempty"`

	// (Boolean) resume reauthentication
	// resume reauthentication
	// +kubebuilder:validation:Optional
	ResumeReauthentication *bool `json:"resumeReauthentication,omitempty" tf:"resume_reauthentication,omitempty"`

	// (String) set domain
	// set domain
	// - Choices: `data`, `switch`, `voice`
	// +kubebuilder:validation:Optional
	SetDomain *string `json:"setDomain,omitempty" tf:"set_domain,omitempty"`

	// (String) timer name
	// timer name
	// +kubebuilder:validation:Optional
	SetTimerName *string `json:"setTimerName,omitempty" tf:"set_timer_name,omitempty"`

	// (Number) Enter a value between 1 and 65535
	// Enter a value between 1 and 65535
	// - Range: `0`-`65535`
	// +kubebuilder:validation:Optional
	SetTimerValue *float64 `json:"setTimerValue,omitempty" tf:"set_timer_value,omitempty"`

	// (String) terminate auth method
	// terminate auth method
	// - Choices: `dot1x`, `mab`, `webauth`
	// +kubebuilder:validation:Optional
	TerminateConfig *string `json:"terminateConfig,omitempty" tf:"terminate_config,omitempty"`

	// (Boolean) unauthorize session
	// unauthorize session
	// +kubebuilder:validation:Optional
	Unauthorize *bool `json:"unauthorize,omitempty" tf:"unauthorize,omitempty"`
}

type ClassNumbersInitParameters struct {

	// (Attributes List) action number, 1 for 1st class, 2 for 2nd... (see below for nested schema)
	ActionNumbers []ActionNumbersInitParameters `json:"actionNumbers,omitempty" tf:"action_numbers,omitempty"`

	// map triggers upon
	// The class type this control policy-map triggers upon
	Class *string `json:"class,omitempty" tf:"class,omitempty"`

	// (String) Policy execution strategy
	// Policy execution strategy
	// - Choices: `do-all`, `do-until-failure`, `do-until-success`
	ExecutionType *string `json:"executionType,omitempty" tf:"execution_type,omitempty"`

	// (Number) class number, 1 for 1st class, 2 for 2nd...
	// class number, 1 for 1st class, 2 for 2nd...
	// - Range: `1`-`254`
	Number *float64 `json:"number,omitempty" tf:"number,omitempty"`
}

type ClassNumbersObservation struct {

	// (Attributes List) action number, 1 for 1st class, 2 for 2nd... (see below for nested schema)
	ActionNumbers []ActionNumbersObservation `json:"actionNumbers,omitempty" tf:"action_numbers,omitempty"`

	// map triggers upon
	// The class type this control policy-map triggers upon
	Class *string `json:"class,omitempty" tf:"class,omitempty"`

	// (String) Policy execution strategy
	// Policy execution strategy
	// - Choices: `do-all`, `do-until-failure`, `do-until-success`
	ExecutionType *string `json:"executionType,omitempty" tf:"execution_type,omitempty"`

	// (Number) class number, 1 for 1st class, 2 for 2nd...
	// class number, 1 for 1st class, 2 for 2nd...
	// - Range: `1`-`254`
	Number *float64 `json:"number,omitempty" tf:"number,omitempty"`
}

type ClassNumbersParameters struct {

	// (Attributes List) action number, 1 for 1st class, 2 for 2nd... (see below for nested schema)
	// +kubebuilder:validation:Optional
	ActionNumbers []ActionNumbersParameters `json:"actionNumbers,omitempty" tf:"action_numbers,omitempty"`

	// map triggers upon
	// The class type this control policy-map triggers upon
	// +kubebuilder:validation:Optional
	Class *string `json:"class,omitempty" tf:"class,omitempty"`

	// (String) Policy execution strategy
	// Policy execution strategy
	// - Choices: `do-all`, `do-until-failure`, `do-until-success`
	// +kubebuilder:validation:Optional
	ExecutionType *string `json:"executionType,omitempty" tf:"execution_type,omitempty"`

	// (Number) class number, 1 for 1st class, 2 for 2nd...
	// class number, 1 for 1st class, 2 for 2nd...
	// - Range: `1`-`254`
	// +kubebuilder:validation:Optional
	Number *float64 `json:"number" tf:"number,omitempty"`
}

type PolicyMapEventInitParameters struct {

	// (Attributes List) class number, 1 for 1st class, 2 for 2nd... (see below for nested schema)
	ClassNumbers []ClassNumbersInitParameters `json:"classNumbers,omitempty" tf:"class_numbers,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// map triggers upon
	// The event this control class-map triggers upon
	// - Choices: `aaa-available`, `absolute-timeout`, `agent-found`, `authentication-failure`, `authentication-success`, `authorization-failure`, `authorization-success`, `identity-update`, `inactivity-timeout`, `remote-authentication-failure`, `remote-authentication-success`, `remote-update`, `session-disconnected`, `session-started`, `tag-added`, `tag-removed`, `template-activated`, `template-activation-failed`, `template-deactivated`, `template-deactivation-failed`, `timer-expiry`, `violation`
	EventType *string `json:"eventType,omitempty" tf:"event_type,omitempty"`

	// (String) Matching criteria for first or all events.
	// Matching criteria for first or all events.
	// - Choices: `match-all`, `match-first`
	MatchType *string `json:"matchType,omitempty" tf:"match_type,omitempty"`

	// (String) Name of the policy map
	// Name of the policy map
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type PolicyMapEventObservation struct {

	// (Attributes List) class number, 1 for 1st class, 2 for 2nd... (see below for nested schema)
	ClassNumbers []ClassNumbersObservation `json:"classNumbers,omitempty" tf:"class_numbers,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// map triggers upon
	// The event this control class-map triggers upon
	// - Choices: `aaa-available`, `absolute-timeout`, `agent-found`, `authentication-failure`, `authentication-success`, `authorization-failure`, `authorization-success`, `identity-update`, `inactivity-timeout`, `remote-authentication-failure`, `remote-authentication-success`, `remote-update`, `session-disconnected`, `session-started`, `tag-added`, `tag-removed`, `template-activated`, `template-activation-failed`, `template-deactivated`, `template-deactivation-failed`, `timer-expiry`, `violation`
	EventType *string `json:"eventType,omitempty" tf:"event_type,omitempty"`

	// (String) The path of the object.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Matching criteria for first or all events.
	// Matching criteria for first or all events.
	// - Choices: `match-all`, `match-first`
	MatchType *string `json:"matchType,omitempty" tf:"match_type,omitempty"`

	// (String) Name of the policy map
	// Name of the policy map
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type PolicyMapEventParameters struct {

	// (Attributes List) class number, 1 for 1st class, 2 for 2nd... (see below for nested schema)
	// +kubebuilder:validation:Optional
	ClassNumbers []ClassNumbersParameters `json:"classNumbers,omitempty" tf:"class_numbers,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	// +kubebuilder:validation:Optional
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// map triggers upon
	// The event this control class-map triggers upon
	// - Choices: `aaa-available`, `absolute-timeout`, `agent-found`, `authentication-failure`, `authentication-success`, `authorization-failure`, `authorization-success`, `identity-update`, `inactivity-timeout`, `remote-authentication-failure`, `remote-authentication-success`, `remote-update`, `session-disconnected`, `session-started`, `tag-added`, `tag-removed`, `template-activated`, `template-activation-failed`, `template-deactivated`, `template-deactivation-failed`, `timer-expiry`, `violation`
	// +kubebuilder:validation:Optional
	EventType *string `json:"eventType,omitempty" tf:"event_type,omitempty"`

	// (String) Matching criteria for first or all events.
	// Matching criteria for first or all events.
	// - Choices: `match-all`, `match-first`
	// +kubebuilder:validation:Optional
	MatchType *string `json:"matchType,omitempty" tf:"match_type,omitempty"`

	// (String) Name of the policy map
	// Name of the policy map
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// PolicyMapEventSpec defines the desired state of PolicyMapEvent
type PolicyMapEventSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   PolicyMapEventParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PolicyMapEventInitParameters `json:"initProvider,omitempty"`
}

// PolicyMapEventStatus defines the observed state of PolicyMapEvent.
type PolicyMapEventStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               PolicyMapEventObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// PolicyMapEvent is the Schema for the PolicyMapEvents API. This resource can manage the Policy Map Event configuration.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,iosxe}
type PolicyMapEvent struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.eventType) || (has(self.initProvider) && has(self.initProvider.eventType))",message="spec.forProvider.eventType is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   PolicyMapEventSpec   `json:"spec"`
	Status PolicyMapEventStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PolicyMapEventList contains a list of PolicyMapEvents
type PolicyMapEventList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PolicyMapEvent `json:"items"`
}

// Repository type metadata.
var (
	PolicyMapEvent_Kind             = "PolicyMapEvent"
	PolicyMapEvent_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: PolicyMapEvent_Kind}.String()
	PolicyMapEvent_KindAPIVersion   = PolicyMapEvent_Kind + "." + CRDGroupVersion.String()
	PolicyMapEvent_GroupVersionKind = CRDGroupVersion.WithKind(PolicyMapEvent_Kind)
)

func init() {
	SchemeBuilder.Register(&PolicyMapEvent{}, &PolicyMapEventList{})
}
