// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type SwitchProvisionInitParameters struct {

	// is. Default value is all.
	// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is. Default value is `all`.
	// - Choices: `all`, `attributes`
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// Range: 1-16
	//
	// - Range: `1`-`16`
	Number *float64 `json:"number,omitempty" tf:"number,omitempty"`

	// (String) Configure Switch provision / offline config
	// Configure Switch provision / offline config
	// - Choices: `C9200-24PB`, `C9200-48PB`, `c9200-24p`, `c9200-24pxg`, `c9200-24t`, `c9200-48p`, `c9200-48pl`, `c9200-48pxg`, `c9200-48t`, `c9200l-24p-4g`, `c9200l-24p-4x`, `c9200l-24pxg-2y`, `c9200l-24pxg-4x`, `c9200l-24t-4g`, `c9200l-24t-4x`, `c9200l-48p-4g`, `c9200l-48p-4x`, `c9200l-48pl-4g`, `c9200l-48pl-4x`, `c9200l-48pxg-2y`, `c9200l-48pxg-4x`, `c9200l-48t-4g`, `c9200l-48t-4x`, `c9300-24p`, `c9300-24s`, `c9300-24t`, `c9300-24u`, `c9300-24ux`, `c9300-48mt`, `c9300-48p`, `c9300-48s`, `c9300-48t`, `c9300-48u`, `c9300-48un`, `c9300-48uxm`, `c9300l-24p-4g`, `c9300l-24p-4x`, `c9300l-24t-4g`, `c9300l-24t-4x`, `c9300l-24uxg-2q`, `c9300l-24uxg-4x`, `c9300l-48p-4g`, `c9300l-48p-4x`, `c9300l-48t-4g`, `c9300l-48t-4x`, `c9300l-48uxg-2q`, `c9300l-48uxg-4x`, `c9300lm-24u-4y`, `c9300lm-48t-4y`, `c9300lm-48u-4y`, `c9300lm-48ux-4y`, `c9500-12q`, `c9500-16x`, `c9500-24q`, `c9500-40x`, `ws-c2960x-24pd-l`, `ws-c3650-12x48fd`, `ws-c3650-12x48uq`, `ws-c3650-12x48ur`, `ws-c3650-12x48uz`, `ws-c3650-24pd`, `ws-c3650-24pdm`, `ws-c3650-24ps`, `ws-c3650-24td`, `ws-c3650-24ts`, `ws-c3650-48fqm`, `ws-c3650-48pd`, `ws-c3650-48pq`, `ws-c3650-48ps`, `ws-c3650-48td`, `ws-c3650-48tq`, `ws-c3650-48ts`, `ws-c3650-8x24pd`, `ws-c3650-8x24uq`, `ws-c3750x-12s`, `ws-c3750x-24p`, `ws-c3850-12s`, `ws-c3850-12x48au`, `ws-c3850-12x48u`, `ws-c3850-12xs`, `ws-c3850-24p`, `ws-c3850-24s`, `ws-c3850-24t`, `ws-c3850-24u`, `ws-c3850-24ux`, `ws-c3850-24xs`, `ws-c3850-24xu`, `ws-c3850-48f`, `ws-c3850-48p`, `ws-c3850-48t`, `ws-c3850-48u`, `ws-c3850-48xs`
	Provision *string `json:"provision,omitempty" tf:"provision,omitempty"`
}

type SwitchProvisionObservation struct {

	// is. Default value is all.
	// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is. Default value is `all`.
	// - Choices: `all`, `attributes`
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// (String) The path of the object.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Range: 1-16
	//
	// - Range: `1`-`16`
	Number *float64 `json:"number,omitempty" tf:"number,omitempty"`

	// (String) Configure Switch provision / offline config
	// Configure Switch provision / offline config
	// - Choices: `C9200-24PB`, `C9200-48PB`, `c9200-24p`, `c9200-24pxg`, `c9200-24t`, `c9200-48p`, `c9200-48pl`, `c9200-48pxg`, `c9200-48t`, `c9200l-24p-4g`, `c9200l-24p-4x`, `c9200l-24pxg-2y`, `c9200l-24pxg-4x`, `c9200l-24t-4g`, `c9200l-24t-4x`, `c9200l-48p-4g`, `c9200l-48p-4x`, `c9200l-48pl-4g`, `c9200l-48pl-4x`, `c9200l-48pxg-2y`, `c9200l-48pxg-4x`, `c9200l-48t-4g`, `c9200l-48t-4x`, `c9300-24p`, `c9300-24s`, `c9300-24t`, `c9300-24u`, `c9300-24ux`, `c9300-48mt`, `c9300-48p`, `c9300-48s`, `c9300-48t`, `c9300-48u`, `c9300-48un`, `c9300-48uxm`, `c9300l-24p-4g`, `c9300l-24p-4x`, `c9300l-24t-4g`, `c9300l-24t-4x`, `c9300l-24uxg-2q`, `c9300l-24uxg-4x`, `c9300l-48p-4g`, `c9300l-48p-4x`, `c9300l-48t-4g`, `c9300l-48t-4x`, `c9300l-48uxg-2q`, `c9300l-48uxg-4x`, `c9300lm-24u-4y`, `c9300lm-48t-4y`, `c9300lm-48u-4y`, `c9300lm-48ux-4y`, `c9500-12q`, `c9500-16x`, `c9500-24q`, `c9500-40x`, `ws-c2960x-24pd-l`, `ws-c3650-12x48fd`, `ws-c3650-12x48uq`, `ws-c3650-12x48ur`, `ws-c3650-12x48uz`, `ws-c3650-24pd`, `ws-c3650-24pdm`, `ws-c3650-24ps`, `ws-c3650-24td`, `ws-c3650-24ts`, `ws-c3650-48fqm`, `ws-c3650-48pd`, `ws-c3650-48pq`, `ws-c3650-48ps`, `ws-c3650-48td`, `ws-c3650-48tq`, `ws-c3650-48ts`, `ws-c3650-8x24pd`, `ws-c3650-8x24uq`, `ws-c3750x-12s`, `ws-c3750x-24p`, `ws-c3850-12s`, `ws-c3850-12x48au`, `ws-c3850-12x48u`, `ws-c3850-12xs`, `ws-c3850-24p`, `ws-c3850-24s`, `ws-c3850-24t`, `ws-c3850-24u`, `ws-c3850-24ux`, `ws-c3850-24xs`, `ws-c3850-24xu`, `ws-c3850-48f`, `ws-c3850-48p`, `ws-c3850-48t`, `ws-c3850-48u`, `ws-c3850-48xs`
	Provision *string `json:"provision,omitempty" tf:"provision,omitempty"`
}

type SwitchProvisionParameters struct {

	// is. Default value is all.
	// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is. Default value is `all`.
	// - Choices: `all`, `attributes`
	// +kubebuilder:validation:Optional
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	// +kubebuilder:validation:Optional
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// Range: 1-16
	//
	// - Range: `1`-`16`
	// +kubebuilder:validation:Optional
	Number *float64 `json:"number,omitempty" tf:"number,omitempty"`

	// (String) Configure Switch provision / offline config
	// Configure Switch provision / offline config
	// - Choices: `C9200-24PB`, `C9200-48PB`, `c9200-24p`, `c9200-24pxg`, `c9200-24t`, `c9200-48p`, `c9200-48pl`, `c9200-48pxg`, `c9200-48t`, `c9200l-24p-4g`, `c9200l-24p-4x`, `c9200l-24pxg-2y`, `c9200l-24pxg-4x`, `c9200l-24t-4g`, `c9200l-24t-4x`, `c9200l-48p-4g`, `c9200l-48p-4x`, `c9200l-48pl-4g`, `c9200l-48pl-4x`, `c9200l-48pxg-2y`, `c9200l-48pxg-4x`, `c9200l-48t-4g`, `c9200l-48t-4x`, `c9300-24p`, `c9300-24s`, `c9300-24t`, `c9300-24u`, `c9300-24ux`, `c9300-48mt`, `c9300-48p`, `c9300-48s`, `c9300-48t`, `c9300-48u`, `c9300-48un`, `c9300-48uxm`, `c9300l-24p-4g`, `c9300l-24p-4x`, `c9300l-24t-4g`, `c9300l-24t-4x`, `c9300l-24uxg-2q`, `c9300l-24uxg-4x`, `c9300l-48p-4g`, `c9300l-48p-4x`, `c9300l-48t-4g`, `c9300l-48t-4x`, `c9300l-48uxg-2q`, `c9300l-48uxg-4x`, `c9300lm-24u-4y`, `c9300lm-48t-4y`, `c9300lm-48u-4y`, `c9300lm-48ux-4y`, `c9500-12q`, `c9500-16x`, `c9500-24q`, `c9500-40x`, `ws-c2960x-24pd-l`, `ws-c3650-12x48fd`, `ws-c3650-12x48uq`, `ws-c3650-12x48ur`, `ws-c3650-12x48uz`, `ws-c3650-24pd`, `ws-c3650-24pdm`, `ws-c3650-24ps`, `ws-c3650-24td`, `ws-c3650-24ts`, `ws-c3650-48fqm`, `ws-c3650-48pd`, `ws-c3650-48pq`, `ws-c3650-48ps`, `ws-c3650-48td`, `ws-c3650-48tq`, `ws-c3650-48ts`, `ws-c3650-8x24pd`, `ws-c3650-8x24uq`, `ws-c3750x-12s`, `ws-c3750x-24p`, `ws-c3850-12s`, `ws-c3850-12x48au`, `ws-c3850-12x48u`, `ws-c3850-12xs`, `ws-c3850-24p`, `ws-c3850-24s`, `ws-c3850-24t`, `ws-c3850-24u`, `ws-c3850-24ux`, `ws-c3850-24xs`, `ws-c3850-24xu`, `ws-c3850-48f`, `ws-c3850-48p`, `ws-c3850-48t`, `ws-c3850-48u`, `ws-c3850-48xs`
	// +kubebuilder:validation:Optional
	Provision *string `json:"provision,omitempty" tf:"provision,omitempty"`
}

// SwitchProvisionSpec defines the desired state of SwitchProvision
type SwitchProvisionSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   SwitchProvisionParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SwitchProvisionInitParameters `json:"initProvider,omitempty"`
}

// SwitchProvisionStatus defines the observed state of SwitchProvision.
type SwitchProvisionStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               SwitchProvisionObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// SwitchProvision is the Schema for the SwitchProvisions API. This resource can manage the Switch configuration.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,iosxe}
type SwitchProvision struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.number) || (has(self.initProvider) && has(self.initProvider.number))",message="spec.forProvider.number is a required parameter"
	Spec   SwitchProvisionSpec   `json:"spec"`
	Status SwitchProvisionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SwitchProvisionList contains a list of SwitchProvisions
type SwitchProvisionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SwitchProvision `json:"items"`
}

// Repository type metadata.
var (
	SwitchProvision_Kind             = "SwitchProvision"
	SwitchProvision_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SwitchProvision_Kind}.String()
	SwitchProvision_KindAPIVersion   = SwitchProvision_Kind + "." + CRDGroupVersion.String()
	SwitchProvision_GroupVersionKind = CRDGroupVersion.WithKind(SwitchProvision_Kind)
)

func init() {
	SchemeBuilder.Register(&SwitchProvision{}, &SwitchProvisionList{})
}
