// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"

// GetCondition of this ClassMap.
func (mg *ClassMap) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

// GetManagementPolicies of this ClassMap.
func (mg *ClassMap) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this ClassMap.
func (mg *ClassMap) GetProviderConfigReference() *xpv2.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this ClassMap.
func (mg *ClassMap) GetWriteConnectionSecretToReference() *xpv2.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this ClassMap.
func (mg *ClassMap) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

// SetManagementPolicies of this ClassMap.
func (mg *ClassMap) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this ClassMap.
func (mg *ClassMap) SetProviderConfigReference(r *xpv2.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this ClassMap.
func (mg *ClassMap) SetWriteConnectionSecretToReference(r *xpv2.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this PolicyMap.
func (mg *PolicyMap) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

// GetManagementPolicies of this PolicyMap.
func (mg *PolicyMap) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this PolicyMap.
func (mg *PolicyMap) GetProviderConfigReference() *xpv2.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this PolicyMap.
func (mg *PolicyMap) GetWriteConnectionSecretToReference() *xpv2.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this PolicyMap.
func (mg *PolicyMap) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

// SetManagementPolicies of this PolicyMap.
func (mg *PolicyMap) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this PolicyMap.
func (mg *PolicyMap) SetProviderConfigReference(r *xpv2.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this PolicyMap.
func (mg *PolicyMap) SetWriteConnectionSecretToReference(r *xpv2.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this PolicyMapEvent.
func (mg *PolicyMapEvent) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

// GetManagementPolicies of this PolicyMapEvent.
func (mg *PolicyMapEvent) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this PolicyMapEvent.
func (mg *PolicyMapEvent) GetProviderConfigReference() *xpv2.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this PolicyMapEvent.
func (mg *PolicyMapEvent) GetWriteConnectionSecretToReference() *xpv2.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this PolicyMapEvent.
func (mg *PolicyMapEvent) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

// SetManagementPolicies of this PolicyMapEvent.
func (mg *PolicyMapEvent) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this PolicyMapEvent.
func (mg *PolicyMapEvent) SetProviderConfigReference(r *xpv2.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this PolicyMapEvent.
func (mg *PolicyMapEvent) SetWriteConnectionSecretToReference(r *xpv2.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this QOS.
func (mg *QOS) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

// GetManagementPolicies of this QOS.
func (mg *QOS) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this QOS.
func (mg *QOS) GetProviderConfigReference() *xpv2.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this QOS.
func (mg *QOS) GetWriteConnectionSecretToReference() *xpv2.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this QOS.
func (mg *QOS) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

// SetManagementPolicies of this QOS.
func (mg *QOS) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this QOS.
func (mg *QOS) SetProviderConfigReference(r *xpv2.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this QOS.
func (mg *QOS) SetWriteConnectionSecretToReference(r *xpv2.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}
