apiVersion: routing.iosxe.upbound.io/v1alpha1
kind: ARP
metadata:
  annotations:
    meta.upbound.io/example-id: routing/v1alpha1/arp
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    incompleteEntries: 10
    proxyDisable: true
