apiVersion: routing.iosxe.upbound.io/v1alpha1
kind: CommunityListExpanded
metadata:
  annotations:
    meta.upbound.io/example-id: routing/v1alpha1/communitylistexpanded
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    entries:
    - action: permit
      regex: 65000:500
    name: CLE1
