// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type LoopbackIPv6AddressesInitParameters struct {

	// 64 interface identifier
	// Use eui-64 interface identifier
	Eui64 *bool `json:"eui64,omitempty" tf:"eui_64,omitempty"`

	// (String) IPv6 prefix
	// IPv6 prefix
	Prefix *string `json:"prefix,omitempty" tf:"prefix,omitempty"`
}

type LoopbackIPv6AddressesObservation struct {

	// 64 interface identifier
	// Use eui-64 interface identifier
	Eui64 *bool `json:"eui64,omitempty" tf:"eui_64,omitempty"`

	// (String) IPv6 prefix
	// IPv6 prefix
	Prefix *string `json:"prefix,omitempty" tf:"prefix,omitempty"`
}

type LoopbackIPv6AddressesParameters struct {

	// 64 interface identifier
	// Use eui-64 interface identifier
	// +kubebuilder:validation:Optional
	Eui64 *bool `json:"eui64,omitempty" tf:"eui_64,omitempty"`

	// (String) IPv6 prefix
	// IPv6 prefix
	// +kubebuilder:validation:Optional
	Prefix *string `json:"prefix" tf:"prefix,omitempty"`
}

type LoopbackIPv6DHCPRelayDestinationsInitParameters struct {

	// (String) Relay destination IPv6 address
	// Relay destination IPv6 address
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// (List of String) Interface for relay address
	// Interface for relay address
	Interface []*string `json:"interface,omitempty" tf:"interface,omitempty"`
}

type LoopbackIPv6DHCPRelayDestinationsObservation struct {

	// (String) Relay destination IPv6 address
	// Relay destination IPv6 address
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// (List of String) Interface for relay address
	// Interface for relay address
	Interface []*string `json:"interface,omitempty" tf:"interface,omitempty"`
}

type LoopbackIPv6DHCPRelayDestinationsParameters struct {

	// (String) Relay destination IPv6 address
	// Relay destination IPv6 address
	// +kubebuilder:validation:Optional
	Address *string `json:"address" tf:"address,omitempty"`

	// (List of String) Interface for relay address
	// Interface for relay address
	// +kubebuilder:validation:Optional
	Interface []*string `json:"interface,omitempty" tf:"interface,omitempty"`
}

type LoopbackIPv6DHCPServersInitParameters struct {

	// (Boolean) Allow hint from client
	// Allow hint from client
	AllowHint *bool `json:"allowHint,omitempty" tf:"allow_hint,omitempty"`

	// (String) DHCP pool name
	// DHCP pool name
	PoolName *string `json:"poolName,omitempty" tf:"pool_name,omitempty"`

	// (Number) Server preference value
	// Server preference value
	// - Range: `0`-`255`
	Preference *float64 `json:"preference,omitempty" tf:"preference,omitempty"`

	// Commit
	// Enable Rapid-Commit
	RapidCommit *bool `json:"rapidCommit,omitempty" tf:"rapid_commit,omitempty"`
}

type LoopbackIPv6DHCPServersObservation struct {

	// (Boolean) Allow hint from client
	// Allow hint from client
	AllowHint *bool `json:"allowHint,omitempty" tf:"allow_hint,omitempty"`

	// (String) DHCP pool name
	// DHCP pool name
	PoolName *string `json:"poolName,omitempty" tf:"pool_name,omitempty"`

	// (Number) Server preference value
	// Server preference value
	// - Range: `0`-`255`
	Preference *float64 `json:"preference,omitempty" tf:"preference,omitempty"`

	// Commit
	// Enable Rapid-Commit
	RapidCommit *bool `json:"rapidCommit,omitempty" tf:"rapid_commit,omitempty"`
}

type LoopbackIPv6DHCPServersParameters struct {

	// (Boolean) Allow hint from client
	// Allow hint from client
	// +kubebuilder:validation:Optional
	AllowHint *bool `json:"allowHint,omitempty" tf:"allow_hint,omitempty"`

	// (String) DHCP pool name
	// DHCP pool name
	// +kubebuilder:validation:Optional
	PoolName *string `json:"poolName" tf:"pool_name,omitempty"`

	// (Number) Server preference value
	// Server preference value
	// - Range: `0`-`255`
	// +kubebuilder:validation:Optional
	Preference *float64 `json:"preference,omitempty" tf:"preference,omitempty"`

	// Commit
	// Enable Rapid-Commit
	// +kubebuilder:validation:Optional
	RapidCommit *bool `json:"rapidCommit,omitempty" tf:"rapid_commit,omitempty"`
}

type LoopbackIPv6LinkLocalAddressesInitParameters struct {

	// (String) Relay destination IPv6 address
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// local address
	// Use link-local address
	LinkLocal *bool `json:"linkLocal,omitempty" tf:"link_local,omitempty"`
}

type LoopbackIPv6LinkLocalAddressesObservation struct {

	// (String) Relay destination IPv6 address
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// local address
	// Use link-local address
	LinkLocal *bool `json:"linkLocal,omitempty" tf:"link_local,omitempty"`
}

type LoopbackIPv6LinkLocalAddressesParameters struct {

	// (String) Relay destination IPv6 address
	// +kubebuilder:validation:Optional
	Address *string `json:"address" tf:"address,omitempty"`

	// local address
	// Use link-local address
	// +kubebuilder:validation:Optional
	LinkLocal *bool `json:"linkLocal,omitempty" tf:"link_local,omitempty"`
}

type LoopbackInitParameters struct {

	// (Number) Set ARP cache timeout
	// Set ARP cache timeout
	// - Range: `0`-`2147483`
	ArpTimeout *float64 `json:"arpTimeout,omitempty" tf:"arp_timeout,omitempty"`

	// is. Default value is all.
	// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is. Default value is `all`.
	// - Choices: `all`, `attributes`
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// (String) Interface specific description
	// Interface specific description
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// (String)
	IPAccessGroupIn *string `json:"ipAccessGroupIn,omitempty" tf:"ip_access_group_in,omitempty"`

	// (Boolean) inbound packets
	// inbound packets
	IPAccessGroupInEnable *bool `json:"ipAccessGroupInEnable,omitempty" tf:"ip_access_group_in_enable,omitempty"`

	// (String)
	IPAccessGroupOut *string `json:"ipAccessGroupOut,omitempty" tf:"ip_access_group_out,omitempty"`

	// (Boolean) outbound packets
	// outbound packets
	IPAccessGroupOutEnable *bool `json:"ipAccessGroupOutEnable,omitempty" tf:"ip_access_group_out_enable,omitempty"`

	// (Number) IGMP version
	// IGMP version
	// - Range: `1`-`3`
	IPIgmpVersion *float64 `json:"ipIgmpVersion,omitempty" tf:"ip_igmp_version,omitempty"`

	// (Number) Set IP Maximum Transmission Unit
	// Set IP Maximum Transmission Unit
	// - Range: `68`-`18000`
	IPMtu *float64 `json:"ipMtu,omitempty" tf:"ip_mtu,omitempty"`

	// (Boolean) Inside interface for address translation
	// Inside interface for address translation
	IPNATInside *bool `json:"ipNatInside,omitempty" tf:"ip_nat_inside,omitempty"`

	// (Boolean) Outside interface for address translation
	// Outside interface for address translation
	IPNATOutside *bool `json:"ipNatOutside,omitempty" tf:"ip_nat_outside,omitempty"`

	// (Boolean) Enable proxy ARP
	// Enable proxy ARP
	IPProxyArp *bool `json:"ipProxyArp,omitempty" tf:"ip_proxy_arp,omitempty"`

	// (Boolean) Enable sending ICMP Redirect messages
	// Enable sending ICMP Redirect messages
	IPRedirects *bool `json:"ipRedirects,omitempty" tf:"ip_redirects,omitempty"`

	// (String)
	IPRouterIsis *string `json:"ipRouterIsis,omitempty" tf:"ip_router_isis,omitempty"`

	// (Boolean) Enable sending ICMP Unreachable messages
	// Enable sending ICMP Unreachable messages
	IPUnreachables *bool `json:"ipUnreachables,omitempty" tf:"ip_unreachables,omitempty"`

	// (Boolean) Allow default route to match when checking source address
	// Allow default route to match when checking source address
	IPVerifyUnicastSourceAllowDefault *bool `json:"ipVerifyUnicastSourceAllowDefault,omitempty" tf:"ip_verify_unicast_source_allow_default,omitempty"`

	// (Boolean) Allow router to ping itself (opens vulnerability in verification)
	// Allow router to ping itself (opens vulnerability in verification)
	IPVerifyUnicastSourceAllowSelfPing *bool `json:"ipVerifyUnicastSourceAllowSelfPing,omitempty" tf:"ip_verify_unicast_source_allow_self_ping,omitempty"`

	// (String) Specify reachability check to apply to the source address
	// Specify reachability check to apply to the source address
	// - Choices: `any`, `rx`
	IPVerifyUnicastSourceReachableVia *string `json:"ipVerifyUnicastSourceReachableVia,omitempty" tf:"ip_verify_unicast_source_reachable_via,omitempty"`

	// (String) Ip address
	// Ip address
	IPv4Address *string `json:"ipv4Address,omitempty" tf:"ipv4_address,omitempty"`

	// (Boolean) IP Address negotiated via DHCP
	// IP Address negotiated via DHCP
	IPv4AddressDHCP *bool `json:"ipv4AddressDhcp,omitempty" tf:"ipv4_address_dhcp,omitempty"`

	// (String) Ip subnet mask
	// Ip subnet mask
	IPv4AddressMask *string `json:"ipv4AddressMask,omitempty" tf:"ipv4_address_mask,omitempty"`

	// (Boolean) Insert default route
	// Insert default route
	IPv6AddressAutoconfigDefault *bool `json:"ipv6AddressAutoconfigDefault,omitempty" tf:"ipv6_address_autoconfig_default,omitempty"`

	// (Boolean) Obtain IPv6 address from DHCP server
	// Obtain IPv6 address from DHCP server
	IPv6AddressDHCP *bool `json:"ipv6AddressDhcp,omitempty" tf:"ipv6_address_dhcp,omitempty"`

	// (Attributes List) (see below for nested schema)
	IPv6Addresses []LoopbackIPv6AddressesInitParameters `json:"ipv6Addresses,omitempty" tf:"ipv6_addresses,omitempty"`

	// delegation name
	// IPv6 DHCP client prefix-delegation name
	IPv6DHCPClientPd *string `json:"ipv6DhcpClientPd,omitempty" tf:"ipv6_dhcp_client_pd,omitempty"`

	// Commit for prefix-delegation
	// Enable Rapid-Commit for prefix-delegation
	IPv6DHCPClientPdRapidCommit *bool `json:"ipv6DhcpClientPdRapidCommit,omitempty" tf:"ipv6_dhcp_client_pd_rapid_commit,omitempty"`

	// (Attributes List) (see below for nested schema)
	IPv6DHCPRelayDestinations []LoopbackIPv6DHCPRelayDestinationsInitParameters `json:"ipv6DhcpRelayDestinations,omitempty" tf:"ipv6_dhcp_relay_destinations,omitempty"`

	// Forward Messages
	// Insert VSS option in Relay-Forward Messages
	IPv6DHCPRelayOptionVPN *bool `json:"ipv6DhcpRelayOptionVpn,omitempty" tf:"ipv6_dhcp_relay_option_vpn,omitempty"`

	// replies
	// Interface is trusted to process relay-replies
	IPv6DHCPRelayTrust *bool `json:"ipv6DhcpRelayTrust,omitempty" tf:"ipv6_dhcp_relay_trust,omitempty"`

	// (Attributes List) Act as an IPv6 DHCP server (see below for nested schema)
	IPv6DHCPServers []LoopbackIPv6DHCPServersInitParameters `json:"ipv6DhcpServers,omitempty" tf:"ipv6_dhcp_servers,omitempty"`

	// (Boolean) Enable IPv6 on interface
	// Enable IPv6 on interface
	IPv6Enable *bool `json:"ipv6Enable,omitempty" tf:"ipv6_enable,omitempty"`

	// (Attributes List) (see below for nested schema)
	IPv6LinkLocalAddresses []LoopbackIPv6LinkLocalAddressesInitParameters `json:"ipv6LinkLocalAddresses,omitempty" tf:"ipv6_link_local_addresses,omitempty"`

	// (Number) Set IPv6 Maximum Transmission Unit
	// Set IPv6 Maximum Transmission Unit
	// - Range: `1280`-`9976`
	IPv6Mtu *float64 `json:"ipv6Mtu,omitempty" tf:"ipv6_mtu,omitempty"`

	// (Boolean) Suppress all IPv6 RA
	// Suppress all IPv6 RA
	IPv6NdRaSuppressAll *bool `json:"ipv6NdRaSuppressAll,omitempty" tf:"ipv6_nd_ra_suppress_all,omitempty"`

	// Range: 0-2147483647
	//
	// - Range: `0`-`2147483647`
	Name *float64 `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) Shutdown the selected interface
	// Shutdown the selected interface
	Shutdown *bool `json:"shutdown,omitempty" tf:"shutdown,omitempty"`

	// (String) Configure forwarding table
	// Configure forwarding table
	// +crossplane:generate:reference:type=github.com/upbound/provider-upjet-iosxe/apis/cluster/routing/v1alpha1.VRF
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name",false)
	VrfForwarding *string `json:"vrfForwarding,omitempty" tf:"vrf_forwarding,omitempty"`

	// Reference to a VRF in routing to populate vrfForwarding.
	// +kubebuilder:validation:Optional
	VrfForwardingRef *v2.Reference `json:"vrfForwardingRef,omitempty" tf:"-"`

	// Selector for a VRF in routing to populate vrfForwarding.
	// +kubebuilder:validation:Optional
	VrfForwardingSelector *v2.Selector `json:"vrfForwardingSelector,omitempty" tf:"-"`

	// (String) Security zone
	// Security zone
	ZoneMemberSecurity *string `json:"zoneMemberSecurity,omitempty" tf:"zone_member_security,omitempty"`
}

type LoopbackObservation struct {

	// (Number) Set ARP cache timeout
	// Set ARP cache timeout
	// - Range: `0`-`2147483`
	ArpTimeout *float64 `json:"arpTimeout,omitempty" tf:"arp_timeout,omitempty"`

	// is. Default value is all.
	// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is. Default value is `all`.
	// - Choices: `all`, `attributes`
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// (String) Interface specific description
	// Interface specific description
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// (String) The path of the object.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String)
	IPAccessGroupIn *string `json:"ipAccessGroupIn,omitempty" tf:"ip_access_group_in,omitempty"`

	// (Boolean) inbound packets
	// inbound packets
	IPAccessGroupInEnable *bool `json:"ipAccessGroupInEnable,omitempty" tf:"ip_access_group_in_enable,omitempty"`

	// (String)
	IPAccessGroupOut *string `json:"ipAccessGroupOut,omitempty" tf:"ip_access_group_out,omitempty"`

	// (Boolean) outbound packets
	// outbound packets
	IPAccessGroupOutEnable *bool `json:"ipAccessGroupOutEnable,omitempty" tf:"ip_access_group_out_enable,omitempty"`

	// (Number) IGMP version
	// IGMP version
	// - Range: `1`-`3`
	IPIgmpVersion *float64 `json:"ipIgmpVersion,omitempty" tf:"ip_igmp_version,omitempty"`

	// (Number) Set IP Maximum Transmission Unit
	// Set IP Maximum Transmission Unit
	// - Range: `68`-`18000`
	IPMtu *float64 `json:"ipMtu,omitempty" tf:"ip_mtu,omitempty"`

	// (Boolean) Inside interface for address translation
	// Inside interface for address translation
	IPNATInside *bool `json:"ipNatInside,omitempty" tf:"ip_nat_inside,omitempty"`

	// (Boolean) Outside interface for address translation
	// Outside interface for address translation
	IPNATOutside *bool `json:"ipNatOutside,omitempty" tf:"ip_nat_outside,omitempty"`

	// (Boolean) Enable proxy ARP
	// Enable proxy ARP
	IPProxyArp *bool `json:"ipProxyArp,omitempty" tf:"ip_proxy_arp,omitempty"`

	// (Boolean) Enable sending ICMP Redirect messages
	// Enable sending ICMP Redirect messages
	IPRedirects *bool `json:"ipRedirects,omitempty" tf:"ip_redirects,omitempty"`

	// (String)
	IPRouterIsis *string `json:"ipRouterIsis,omitempty" tf:"ip_router_isis,omitempty"`

	// (Boolean) Enable sending ICMP Unreachable messages
	// Enable sending ICMP Unreachable messages
	IPUnreachables *bool `json:"ipUnreachables,omitempty" tf:"ip_unreachables,omitempty"`

	// (Boolean) Allow default route to match when checking source address
	// Allow default route to match when checking source address
	IPVerifyUnicastSourceAllowDefault *bool `json:"ipVerifyUnicastSourceAllowDefault,omitempty" tf:"ip_verify_unicast_source_allow_default,omitempty"`

	// (Boolean) Allow router to ping itself (opens vulnerability in verification)
	// Allow router to ping itself (opens vulnerability in verification)
	IPVerifyUnicastSourceAllowSelfPing *bool `json:"ipVerifyUnicastSourceAllowSelfPing,omitempty" tf:"ip_verify_unicast_source_allow_self_ping,omitempty"`

	// (String) Specify reachability check to apply to the source address
	// Specify reachability check to apply to the source address
	// - Choices: `any`, `rx`
	IPVerifyUnicastSourceReachableVia *string `json:"ipVerifyUnicastSourceReachableVia,omitempty" tf:"ip_verify_unicast_source_reachable_via,omitempty"`

	// (String) Ip address
	// Ip address
	IPv4Address *string `json:"ipv4Address,omitempty" tf:"ipv4_address,omitempty"`

	// (Boolean) IP Address negotiated via DHCP
	// IP Address negotiated via DHCP
	IPv4AddressDHCP *bool `json:"ipv4AddressDhcp,omitempty" tf:"ipv4_address_dhcp,omitempty"`

	// (String) Ip subnet mask
	// Ip subnet mask
	IPv4AddressMask *string `json:"ipv4AddressMask,omitempty" tf:"ipv4_address_mask,omitempty"`

	// (Boolean) Insert default route
	// Insert default route
	IPv6AddressAutoconfigDefault *bool `json:"ipv6AddressAutoconfigDefault,omitempty" tf:"ipv6_address_autoconfig_default,omitempty"`

	// (Boolean) Obtain IPv6 address from DHCP server
	// Obtain IPv6 address from DHCP server
	IPv6AddressDHCP *bool `json:"ipv6AddressDhcp,omitempty" tf:"ipv6_address_dhcp,omitempty"`

	// (Attributes List) (see below for nested schema)
	IPv6Addresses []LoopbackIPv6AddressesObservation `json:"ipv6Addresses,omitempty" tf:"ipv6_addresses,omitempty"`

	// delegation name
	// IPv6 DHCP client prefix-delegation name
	IPv6DHCPClientPd *string `json:"ipv6DhcpClientPd,omitempty" tf:"ipv6_dhcp_client_pd,omitempty"`

	// Commit for prefix-delegation
	// Enable Rapid-Commit for prefix-delegation
	IPv6DHCPClientPdRapidCommit *bool `json:"ipv6DhcpClientPdRapidCommit,omitempty" tf:"ipv6_dhcp_client_pd_rapid_commit,omitempty"`

	// (Attributes List) (see below for nested schema)
	IPv6DHCPRelayDestinations []LoopbackIPv6DHCPRelayDestinationsObservation `json:"ipv6DhcpRelayDestinations,omitempty" tf:"ipv6_dhcp_relay_destinations,omitempty"`

	// Forward Messages
	// Insert VSS option in Relay-Forward Messages
	IPv6DHCPRelayOptionVPN *bool `json:"ipv6DhcpRelayOptionVpn,omitempty" tf:"ipv6_dhcp_relay_option_vpn,omitempty"`

	// replies
	// Interface is trusted to process relay-replies
	IPv6DHCPRelayTrust *bool `json:"ipv6DhcpRelayTrust,omitempty" tf:"ipv6_dhcp_relay_trust,omitempty"`

	// (Attributes List) Act as an IPv6 DHCP server (see below for nested schema)
	IPv6DHCPServers []LoopbackIPv6DHCPServersObservation `json:"ipv6DhcpServers,omitempty" tf:"ipv6_dhcp_servers,omitempty"`

	// (Boolean) Enable IPv6 on interface
	// Enable IPv6 on interface
	IPv6Enable *bool `json:"ipv6Enable,omitempty" tf:"ipv6_enable,omitempty"`

	// (Attributes List) (see below for nested schema)
	IPv6LinkLocalAddresses []LoopbackIPv6LinkLocalAddressesObservation `json:"ipv6LinkLocalAddresses,omitempty" tf:"ipv6_link_local_addresses,omitempty"`

	// (Number) Set IPv6 Maximum Transmission Unit
	// Set IPv6 Maximum Transmission Unit
	// - Range: `1280`-`9976`
	IPv6Mtu *float64 `json:"ipv6Mtu,omitempty" tf:"ipv6_mtu,omitempty"`

	// (Boolean) Suppress all IPv6 RA
	// Suppress all IPv6 RA
	IPv6NdRaSuppressAll *bool `json:"ipv6NdRaSuppressAll,omitempty" tf:"ipv6_nd_ra_suppress_all,omitempty"`

	// Range: 0-2147483647
	//
	// - Range: `0`-`2147483647`
	Name *float64 `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) Shutdown the selected interface
	// Shutdown the selected interface
	Shutdown *bool `json:"shutdown,omitempty" tf:"shutdown,omitempty"`

	// (String) Configure forwarding table
	// Configure forwarding table
	VrfForwarding *string `json:"vrfForwarding,omitempty" tf:"vrf_forwarding,omitempty"`

	// (String) Security zone
	// Security zone
	ZoneMemberSecurity *string `json:"zoneMemberSecurity,omitempty" tf:"zone_member_security,omitempty"`
}

type LoopbackParameters struct {

	// (Number) Set ARP cache timeout
	// Set ARP cache timeout
	// - Range: `0`-`2147483`
	// +kubebuilder:validation:Optional
	ArpTimeout *float64 `json:"arpTimeout,omitempty" tf:"arp_timeout,omitempty"`

	// is. Default value is all.
	// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is. Default value is `all`.
	// - Choices: `all`, `attributes`
	// +kubebuilder:validation:Optional
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// (String) Interface specific description
	// Interface specific description
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	// +kubebuilder:validation:Optional
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	IPAccessGroupIn *string `json:"ipAccessGroupIn,omitempty" tf:"ip_access_group_in,omitempty"`

	// (Boolean) inbound packets
	// inbound packets
	// +kubebuilder:validation:Optional
	IPAccessGroupInEnable *bool `json:"ipAccessGroupInEnable,omitempty" tf:"ip_access_group_in_enable,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	IPAccessGroupOut *string `json:"ipAccessGroupOut,omitempty" tf:"ip_access_group_out,omitempty"`

	// (Boolean) outbound packets
	// outbound packets
	// +kubebuilder:validation:Optional
	IPAccessGroupOutEnable *bool `json:"ipAccessGroupOutEnable,omitempty" tf:"ip_access_group_out_enable,omitempty"`

	// (Number) IGMP version
	// IGMP version
	// - Range: `1`-`3`
	// +kubebuilder:validation:Optional
	IPIgmpVersion *float64 `json:"ipIgmpVersion,omitempty" tf:"ip_igmp_version,omitempty"`

	// (Number) Set IP Maximum Transmission Unit
	// Set IP Maximum Transmission Unit
	// - Range: `68`-`18000`
	// +kubebuilder:validation:Optional
	IPMtu *float64 `json:"ipMtu,omitempty" tf:"ip_mtu,omitempty"`

	// (Boolean) Inside interface for address translation
	// Inside interface for address translation
	// +kubebuilder:validation:Optional
	IPNATInside *bool `json:"ipNatInside,omitempty" tf:"ip_nat_inside,omitempty"`

	// (Boolean) Outside interface for address translation
	// Outside interface for address translation
	// +kubebuilder:validation:Optional
	IPNATOutside *bool `json:"ipNatOutside,omitempty" tf:"ip_nat_outside,omitempty"`

	// (Boolean) Enable proxy ARP
	// Enable proxy ARP
	// +kubebuilder:validation:Optional
	IPProxyArp *bool `json:"ipProxyArp,omitempty" tf:"ip_proxy_arp,omitempty"`

	// (Boolean) Enable sending ICMP Redirect messages
	// Enable sending ICMP Redirect messages
	// +kubebuilder:validation:Optional
	IPRedirects *bool `json:"ipRedirects,omitempty" tf:"ip_redirects,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	IPRouterIsis *string `json:"ipRouterIsis,omitempty" tf:"ip_router_isis,omitempty"`

	// (Boolean) Enable sending ICMP Unreachable messages
	// Enable sending ICMP Unreachable messages
	// +kubebuilder:validation:Optional
	IPUnreachables *bool `json:"ipUnreachables,omitempty" tf:"ip_unreachables,omitempty"`

	// (Boolean) Allow default route to match when checking source address
	// Allow default route to match when checking source address
	// +kubebuilder:validation:Optional
	IPVerifyUnicastSourceAllowDefault *bool `json:"ipVerifyUnicastSourceAllowDefault,omitempty" tf:"ip_verify_unicast_source_allow_default,omitempty"`

	// (Boolean) Allow router to ping itself (opens vulnerability in verification)
	// Allow router to ping itself (opens vulnerability in verification)
	// +kubebuilder:validation:Optional
	IPVerifyUnicastSourceAllowSelfPing *bool `json:"ipVerifyUnicastSourceAllowSelfPing,omitempty" tf:"ip_verify_unicast_source_allow_self_ping,omitempty"`

	// (String) Specify reachability check to apply to the source address
	// Specify reachability check to apply to the source address
	// - Choices: `any`, `rx`
	// +kubebuilder:validation:Optional
	IPVerifyUnicastSourceReachableVia *string `json:"ipVerifyUnicastSourceReachableVia,omitempty" tf:"ip_verify_unicast_source_reachable_via,omitempty"`

	// (String) Ip address
	// Ip address
	// +kubebuilder:validation:Optional
	IPv4Address *string `json:"ipv4Address,omitempty" tf:"ipv4_address,omitempty"`

	// (Boolean) IP Address negotiated via DHCP
	// IP Address negotiated via DHCP
	// +kubebuilder:validation:Optional
	IPv4AddressDHCP *bool `json:"ipv4AddressDhcp,omitempty" tf:"ipv4_address_dhcp,omitempty"`

	// (String) Ip subnet mask
	// Ip subnet mask
	// +kubebuilder:validation:Optional
	IPv4AddressMask *string `json:"ipv4AddressMask,omitempty" tf:"ipv4_address_mask,omitempty"`

	// (Boolean) Insert default route
	// Insert default route
	// +kubebuilder:validation:Optional
	IPv6AddressAutoconfigDefault *bool `json:"ipv6AddressAutoconfigDefault,omitempty" tf:"ipv6_address_autoconfig_default,omitempty"`

	// (Boolean) Obtain IPv6 address from DHCP server
	// Obtain IPv6 address from DHCP server
	// +kubebuilder:validation:Optional
	IPv6AddressDHCP *bool `json:"ipv6AddressDhcp,omitempty" tf:"ipv6_address_dhcp,omitempty"`

	// (Attributes List) (see below for nested schema)
	// +kubebuilder:validation:Optional
	IPv6Addresses []LoopbackIPv6AddressesParameters `json:"ipv6Addresses,omitempty" tf:"ipv6_addresses,omitempty"`

	// delegation name
	// IPv6 DHCP client prefix-delegation name
	// +kubebuilder:validation:Optional
	IPv6DHCPClientPd *string `json:"ipv6DhcpClientPd,omitempty" tf:"ipv6_dhcp_client_pd,omitempty"`

	// Commit for prefix-delegation
	// Enable Rapid-Commit for prefix-delegation
	// +kubebuilder:validation:Optional
	IPv6DHCPClientPdRapidCommit *bool `json:"ipv6DhcpClientPdRapidCommit,omitempty" tf:"ipv6_dhcp_client_pd_rapid_commit,omitempty"`

	// (Attributes List) (see below for nested schema)
	// +kubebuilder:validation:Optional
	IPv6DHCPRelayDestinations []LoopbackIPv6DHCPRelayDestinationsParameters `json:"ipv6DhcpRelayDestinations,omitempty" tf:"ipv6_dhcp_relay_destinations,omitempty"`

	// Forward Messages
	// Insert VSS option in Relay-Forward Messages
	// +kubebuilder:validation:Optional
	IPv6DHCPRelayOptionVPN *bool `json:"ipv6DhcpRelayOptionVpn,omitempty" tf:"ipv6_dhcp_relay_option_vpn,omitempty"`

	// replies
	// Interface is trusted to process relay-replies
	// +kubebuilder:validation:Optional
	IPv6DHCPRelayTrust *bool `json:"ipv6DhcpRelayTrust,omitempty" tf:"ipv6_dhcp_relay_trust,omitempty"`

	// (Attributes List) Act as an IPv6 DHCP server (see below for nested schema)
	// +kubebuilder:validation:Optional
	IPv6DHCPServers []LoopbackIPv6DHCPServersParameters `json:"ipv6DhcpServers,omitempty" tf:"ipv6_dhcp_servers,omitempty"`

	// (Boolean) Enable IPv6 on interface
	// Enable IPv6 on interface
	// +kubebuilder:validation:Optional
	IPv6Enable *bool `json:"ipv6Enable,omitempty" tf:"ipv6_enable,omitempty"`

	// (Attributes List) (see below for nested schema)
	// +kubebuilder:validation:Optional
	IPv6LinkLocalAddresses []LoopbackIPv6LinkLocalAddressesParameters `json:"ipv6LinkLocalAddresses,omitempty" tf:"ipv6_link_local_addresses,omitempty"`

	// (Number) Set IPv6 Maximum Transmission Unit
	// Set IPv6 Maximum Transmission Unit
	// - Range: `1280`-`9976`
	// +kubebuilder:validation:Optional
	IPv6Mtu *float64 `json:"ipv6Mtu,omitempty" tf:"ipv6_mtu,omitempty"`

	// (Boolean) Suppress all IPv6 RA
	// Suppress all IPv6 RA
	// +kubebuilder:validation:Optional
	IPv6NdRaSuppressAll *bool `json:"ipv6NdRaSuppressAll,omitempty" tf:"ipv6_nd_ra_suppress_all,omitempty"`

	// Range: 0-2147483647
	//
	// - Range: `0`-`2147483647`
	// +kubebuilder:validation:Optional
	Name *float64 `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) Shutdown the selected interface
	// Shutdown the selected interface
	// +kubebuilder:validation:Optional
	Shutdown *bool `json:"shutdown,omitempty" tf:"shutdown,omitempty"`

	// (String) Configure forwarding table
	// Configure forwarding table
	// +crossplane:generate:reference:type=github.com/upbound/provider-upjet-iosxe/apis/cluster/routing/v1alpha1.VRF
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name",false)
	// +kubebuilder:validation:Optional
	VrfForwarding *string `json:"vrfForwarding,omitempty" tf:"vrf_forwarding,omitempty"`

	// Reference to a VRF in routing to populate vrfForwarding.
	// +kubebuilder:validation:Optional
	VrfForwardingRef *v2.Reference `json:"vrfForwardingRef,omitempty" tf:"-"`

	// Selector for a VRF in routing to populate vrfForwarding.
	// +kubebuilder:validation:Optional
	VrfForwardingSelector *v2.Selector `json:"vrfForwardingSelector,omitempty" tf:"-"`

	// (String) Security zone
	// Security zone
	// +kubebuilder:validation:Optional
	ZoneMemberSecurity *string `json:"zoneMemberSecurity,omitempty" tf:"zone_member_security,omitempty"`
}

// LoopbackSpec defines the desired state of Loopback
type LoopbackSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   LoopbackParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider LoopbackInitParameters `json:"initProvider,omitempty"`
}

// LoopbackStatus defines the observed state of Loopback.
type LoopbackStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               LoopbackObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Loopback is the Schema for the Loopbacks API. This resource can manage the Interface Loopback configuration.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,iosxe}
type Loopback struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   LoopbackSpec   `json:"spec"`
	Status LoopbackStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// LoopbackList contains a list of Loopbacks
type LoopbackList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Loopback `json:"items"`
}

// Repository type metadata.
var (
	Loopback_Kind             = "Loopback"
	Loopback_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Loopback_Kind}.String()
	Loopback_KindAPIVersion   = Loopback_Kind + "." + CRDGroupVersion.String()
	Loopback_GroupVersionKind = CRDGroupVersion.WithKind(Loopback_Kind)
)

func init() {
	SchemeBuilder.Register(&Loopback{}, &LoopbackList{})
}
