// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type EvpnEthernetSegmentsLegacyInitParameters struct {

	// (Number) Ethernet segment local discriminator value
	// Ethernet segment local discriminator value, DEPRECATED
	// - Range: `1`-`65535`
	EsValue *float64 `json:"esValue,omitempty" tf:"es_value,omitempty"`
}

type EvpnEthernetSegmentsLegacyObservation struct {

	// (Number) Ethernet segment local discriminator value
	// Ethernet segment local discriminator value, DEPRECATED
	// - Range: `1`-`65535`
	EsValue *float64 `json:"esValue,omitempty" tf:"es_value,omitempty"`
}

type EvpnEthernetSegmentsLegacyParameters struct {

	// (Number) Ethernet segment local discriminator value
	// Ethernet segment local discriminator value, DEPRECATED
	// - Range: `1`-`65535`
	// +kubebuilder:validation:Optional
	EsValue *float64 `json:"esValue" tf:"es_value,omitempty"`
}

type PortChannelDeviceTrackingAttachedPoliciesInitParameters struct {

	// Range: 1-512
	// Apply a policy for feature device-tracking
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type PortChannelDeviceTrackingAttachedPoliciesObservation struct {

	// Range: 1-512
	// Apply a policy for feature device-tracking
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type PortChannelDeviceTrackingAttachedPoliciesParameters struct {

	// Range: 1-512
	// Apply a policy for feature device-tracking
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`
}

type PortChannelEvpnEthernetSegmentsInitParameters struct {

	// (Number) Ethernet segment local discriminator value
	// Ethernet segment local discriminator value
	// - Range: `1`-`65535`
	EsValue *float64 `json:"esValue,omitempty" tf:"es_value,omitempty"`
}

type PortChannelEvpnEthernetSegmentsObservation struct {

	// (Number) Ethernet segment local discriminator value
	// Ethernet segment local discriminator value
	// - Range: `1`-`65535`
	EsValue *float64 `json:"esValue,omitempty" tf:"es_value,omitempty"`
}

type PortChannelEvpnEthernetSegmentsParameters struct {

	// (Number) Ethernet segment local discriminator value
	// Ethernet segment local discriminator value
	// - Range: `1`-`65535`
	// +kubebuilder:validation:Optional
	EsValue *float64 `json:"esValue" tf:"es_value,omitempty"`
}

type PortChannelHelperAddressesInitParameters struct {

	// (String) IP destination address
	// IP destination address
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// address is global
	// Helper-address is global
	Global *bool `json:"global,omitempty" tf:"global,omitempty"`

	// address (if different from interface VRF)
	// VRF name for helper-address (if different from interface VRF)
	Vrf *string `json:"vrf,omitempty" tf:"vrf,omitempty"`
}

type PortChannelHelperAddressesObservation struct {

	// (String) IP destination address
	// IP destination address
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// address is global
	// Helper-address is global
	Global *bool `json:"global,omitempty" tf:"global,omitempty"`

	// address (if different from interface VRF)
	// VRF name for helper-address (if different from interface VRF)
	Vrf *string `json:"vrf,omitempty" tf:"vrf,omitempty"`
}

type PortChannelHelperAddressesParameters struct {

	// (String) IP destination address
	// IP destination address
	// +kubebuilder:validation:Optional
	Address *string `json:"address" tf:"address,omitempty"`

	// address is global
	// Helper-address is global
	// +kubebuilder:validation:Optional
	Global *bool `json:"global,omitempty" tf:"global,omitempty"`

	// address (if different from interface VRF)
	// VRF name for helper-address (if different from interface VRF)
	// +kubebuilder:validation:Optional
	Vrf *string `json:"vrf,omitempty" tf:"vrf,omitempty"`
}

type PortChannelIPFlowMonitorsInitParameters struct {

	// Choices: input, output
	//
	// - Choices: `input`, `output`
	Direction *string `json:"direction,omitempty" tf:"direction,omitempty"`

	// Range: 1-512
	// User defined
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type PortChannelIPFlowMonitorsObservation struct {

	// Choices: input, output
	//
	// - Choices: `input`, `output`
	Direction *string `json:"direction,omitempty" tf:"direction,omitempty"`

	// Range: 1-512
	// User defined
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type PortChannelIPFlowMonitorsParameters struct {

	// Choices: input, output
	//
	// - Choices: `input`, `output`
	// +kubebuilder:validation:Optional
	Direction *string `json:"direction" tf:"direction,omitempty"`

	// Range: 1-512
	// User defined
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`
}

type PortChannelIPv6AddressesInitParameters struct {

	// 64 interface identifier
	// Use eui-64 interface identifier
	Eui64 *bool `json:"eui64,omitempty" tf:"eui_64,omitempty"`

	// (String) IPv6 prefix
	// IPv6 prefix
	Prefix *string `json:"prefix,omitempty" tf:"prefix,omitempty"`
}

type PortChannelIPv6AddressesObservation struct {

	// 64 interface identifier
	// Use eui-64 interface identifier
	Eui64 *bool `json:"eui64,omitempty" tf:"eui_64,omitempty"`

	// (String) IPv6 prefix
	// IPv6 prefix
	Prefix *string `json:"prefix,omitempty" tf:"prefix,omitempty"`
}

type PortChannelIPv6AddressesParameters struct {

	// 64 interface identifier
	// Use eui-64 interface identifier
	// +kubebuilder:validation:Optional
	Eui64 *bool `json:"eui64,omitempty" tf:"eui_64,omitempty"`

	// (String) IPv6 prefix
	// IPv6 prefix
	// +kubebuilder:validation:Optional
	Prefix *string `json:"prefix" tf:"prefix,omitempty"`
}

type PortChannelIPv6DHCPRelayDestinationsInitParameters struct {

	// (String) IP destination address
	// Relay destination IPv6 address
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// (List of String) Interface for relay address
	// Interface for relay address
	Interface []*string `json:"interface,omitempty" tf:"interface,omitempty"`
}

type PortChannelIPv6DHCPRelayDestinationsObservation struct {

	// (String) IP destination address
	// Relay destination IPv6 address
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// (List of String) Interface for relay address
	// Interface for relay address
	Interface []*string `json:"interface,omitempty" tf:"interface,omitempty"`
}

type PortChannelIPv6DHCPRelayDestinationsParameters struct {

	// (String) IP destination address
	// Relay destination IPv6 address
	// +kubebuilder:validation:Optional
	Address *string `json:"address" tf:"address,omitempty"`

	// (List of String) Interface for relay address
	// Interface for relay address
	// +kubebuilder:validation:Optional
	Interface []*string `json:"interface,omitempty" tf:"interface,omitempty"`
}

type PortChannelIPv6DHCPServersInitParameters struct {

	// (Boolean) Allow hint from client
	// Allow hint from client
	AllowHint *bool `json:"allowHint,omitempty" tf:"allow_hint,omitempty"`

	// (String) DHCP pool name
	// DHCP pool name
	PoolName *string `json:"poolName,omitempty" tf:"pool_name,omitempty"`

	// (Number) Server preference value
	// Server preference value
	// - Range: `0`-`255`
	Preference *float64 `json:"preference,omitempty" tf:"preference,omitempty"`

	// Commit
	// Enable Rapid-Commit
	RapidCommit *bool `json:"rapidCommit,omitempty" tf:"rapid_commit,omitempty"`
}

type PortChannelIPv6DHCPServersObservation struct {

	// (Boolean) Allow hint from client
	// Allow hint from client
	AllowHint *bool `json:"allowHint,omitempty" tf:"allow_hint,omitempty"`

	// (String) DHCP pool name
	// DHCP pool name
	PoolName *string `json:"poolName,omitempty" tf:"pool_name,omitempty"`

	// (Number) Server preference value
	// Server preference value
	// - Range: `0`-`255`
	Preference *float64 `json:"preference,omitempty" tf:"preference,omitempty"`

	// Commit
	// Enable Rapid-Commit
	RapidCommit *bool `json:"rapidCommit,omitempty" tf:"rapid_commit,omitempty"`
}

type PortChannelIPv6DHCPServersParameters struct {

	// (Boolean) Allow hint from client
	// Allow hint from client
	// +kubebuilder:validation:Optional
	AllowHint *bool `json:"allowHint,omitempty" tf:"allow_hint,omitempty"`

	// (String) DHCP pool name
	// DHCP pool name
	// +kubebuilder:validation:Optional
	PoolName *string `json:"poolName" tf:"pool_name,omitempty"`

	// (Number) Server preference value
	// Server preference value
	// - Range: `0`-`255`
	// +kubebuilder:validation:Optional
	Preference *float64 `json:"preference,omitempty" tf:"preference,omitempty"`

	// Commit
	// Enable Rapid-Commit
	// +kubebuilder:validation:Optional
	RapidCommit *bool `json:"rapidCommit,omitempty" tf:"rapid_commit,omitempty"`
}

type PortChannelIPv6FlowMonitorsInitParameters struct {

	// Choices: input, output
	//
	// - Choices: `input`, `output`
	Direction *string `json:"direction,omitempty" tf:"direction,omitempty"`

	// Range: 1-512
	// User defined
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type PortChannelIPv6FlowMonitorsObservation struct {

	// Choices: input, output
	//
	// - Choices: `input`, `output`
	Direction *string `json:"direction,omitempty" tf:"direction,omitempty"`

	// Range: 1-512
	// User defined
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type PortChannelIPv6FlowMonitorsParameters struct {

	// Choices: input, output
	//
	// - Choices: `input`, `output`
	// +kubebuilder:validation:Optional
	Direction *string `json:"direction" tf:"direction,omitempty"`

	// Range: 1-512
	// User defined
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`
}

type PortChannelIPv6LinkLocalAddressesInitParameters struct {

	// (String) IP destination address
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// local address
	// Use link-local address
	LinkLocal *bool `json:"linkLocal,omitempty" tf:"link_local,omitempty"`
}

type PortChannelIPv6LinkLocalAddressesObservation struct {

	// (String) IP destination address
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// local address
	// Use link-local address
	LinkLocal *bool `json:"linkLocal,omitempty" tf:"link_local,omitempty"`
}

type PortChannelIPv6LinkLocalAddressesParameters struct {

	// (String) IP destination address
	// +kubebuilder:validation:Optional
	Address *string `json:"address" tf:"address,omitempty"`

	// local address
	// Use link-local address
	// +kubebuilder:validation:Optional
	LinkLocal *bool `json:"linkLocal,omitempty" tf:"link_local,omitempty"`
}

type PortChannelInitParameters struct {

	// (Number) Set ARP cache timeout
	// Set ARP cache timeout
	// - Range: `0`-`2147483`
	ArpTimeout *float64 `json:"arpTimeout,omitempty" tf:"arp_timeout,omitempty"`

	// (Boolean) Configure classification for untrusted devices
	// Configure classification for untrusted devices
	AutoQosClassify *bool `json:"autoQosClassify,omitempty" tf:"auto_qos_classify,omitempty"`

	// (Boolean) Configure QoS policing for untrusted devices
	// Configure QoS policing for untrusted devices
	AutoQosClassifyPolice *bool `json:"autoQosClassifyPolice,omitempty" tf:"auto_qos_classify_police,omitempty"`

	// (Boolean) Trust the DSCP/CoS marking
	// Trust the DSCP/CoS marking
	AutoQosTrust *bool `json:"autoQosTrust,omitempty" tf:"auto_qos_trust,omitempty"`

	// (Boolean) Trust the CoS marking
	// Trust the CoS marking
	AutoQosTrustCos *bool `json:"autoQosTrustCos,omitempty" tf:"auto_qos_trust_cos,omitempty"`

	// (Boolean) Trust the DSCP marking
	// Trust the DSCP marking
	AutoQosTrustDscp *bool `json:"autoQosTrustDscp,omitempty" tf:"auto_qos_trust_dscp,omitempty"`

	// (Boolean) Trust the QoS marking of the Cisco Telepresence System
	// Trust the QoS marking of the Cisco Telepresence System
	AutoQosVideoCts *bool `json:"autoQosVideoCts,omitempty" tf:"auto_qos_video_cts,omitempty"`

	// (Boolean) Trust the QoS marking of the Ip Video Surveillance camera
	// Trust the QoS marking of the Ip Video Surveillance camera
	AutoQosVideoIPCamera *bool `json:"autoQosVideoIpCamera,omitempty" tf:"auto_qos_video_ip_camera,omitempty"`

	// (Boolean) Trust the Qos marking of the Cisco Media Player
	// Trust the Qos marking of the Cisco Media Player
	AutoQosVideoMediaPlayer *bool `json:"autoQosVideoMediaPlayer,omitempty" tf:"auto_qos_video_media_player,omitempty"`

	// (Boolean) Trust the QoS marking of Cisco IP Phone
	// Trust the QoS marking of Cisco IP Phone
	AutoQosVoIPCiscoPhone *bool `json:"autoQosVoipCiscoPhone,omitempty" tf:"auto_qos_voip_cisco_phone,omitempty"`

	// (Boolean) Trust the QoS marking of Cisco IP SoftPhone
	// Trust the QoS marking of Cisco IP SoftPhone
	AutoQosVoIPCiscoSoftphone *bool `json:"autoQosVoipCiscoSoftphone,omitempty" tf:"auto_qos_voip_cisco_softphone,omitempty"`

	// (Boolean) Trust the DSCP/CoS marking
	// Trust the DSCP/CoS marking
	AutoQosVoIPTrust *bool `json:"autoQosVoipTrust,omitempty" tf:"auto_qos_voip_trust,omitempty"`

	// (Boolean) Use echo adjunct as bfd detection mechanism
	// Use echo adjunct as bfd detection mechanism
	BfdEcho *bool `json:"bfdEcho,omitempty" tf:"bfd_echo,omitempty"`

	// (Boolean) Enable BFD under the interface
	// Enable BFD under the interface
	BfdEnable *bool `json:"bfdEnable,omitempty" tf:"bfd_enable,omitempty"`

	// Range: 50-9999
	//
	// - Range: `50`-`9999`
	BfdInterval *float64 `json:"bfdInterval,omitempty" tf:"bfd_interval,omitempty"`

	// (Number) Minimum receive interval capability
	// Minimum receive interval capability
	// - Range: `50`-`9999`
	BfdIntervalMinRx *float64 `json:"bfdIntervalMinRx,omitempty" tf:"bfd_interval_min_rx,omitempty"`

	// (Number) Multiplier value used to compute holddown
	// Multiplier value used to compute holddown
	// - Range: `3`-`50`
	BfdIntervalMultiplier *float64 `json:"bfdIntervalMultiplier,omitempty" tf:"bfd_interval_multiplier,omitempty"`

	// (String) The Source IP address to be used for BFD sessions over this interface.
	// The Source IP address to be used for BFD sessions over this interface.
	BfdLocalAddress *string `json:"bfdLocalAddress,omitempty" tf:"bfd_local_address,omitempty"`

	// (String) BFD template
	// BFD template
	BfdTemplate *string `json:"bfdTemplate,omitempty" tf:"bfd_template,omitempty"`

	// (Boolean) Disable BPDU guard for this interface
	// Disable BPDU guard for this interface
	BpduguardDisable *bool `json:"bpduguardDisable,omitempty" tf:"bpduguard_disable,omitempty"`

	// (Boolean) Enable BPDU guard for this interface
	// Enable BPDU guard for this interface
	BpduguardEnable *bool `json:"bpduguardEnable,omitempty" tf:"bpduguard_enable,omitempty"`

	// is. Default value is all.
	// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is. Default value is `all`.
	// - Choices: `all`, `attributes`
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// (String) Interface specific description
	// Interface specific description
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// tracking on the interface
	// Configure device-tracking on the interface
	DeviceTracking *bool `json:"deviceTracking,omitempty" tf:"device_tracking,omitempty"`

	// (Attributes List) (see below for nested schema)
	DeviceTrackingAttachedPolicies []PortChannelDeviceTrackingAttachedPoliciesInitParameters `json:"deviceTrackingAttachedPolicies,omitempty" tf:"device_tracking_attached_policies,omitempty"`

	// (Attributes List) Ethernet segment local discriminator value (see below for nested schema)
	EvpnEthernetSegments []PortChannelEvpnEthernetSegmentsInitParameters `json:"evpnEthernetSegments,omitempty" tf:"evpn_ethernet_segments,omitempty"`

	// (Attributes List) Ethernet segment local discriminator value, DEPRECATED (see below for nested schema)
	EvpnEthernetSegmentsLegacy []EvpnEthernetSegmentsLegacyInitParameters `json:"evpnEthernetSegmentsLegacy,omitempty" tf:"evpn_ethernet_segments_legacy,omitempty"`

	// (Attributes List) Specify a destination address for UDP broadcasts (see below for nested schema)
	HelperAddresses []PortChannelHelperAddressesInitParameters `json:"helperAddresses,omitempty" tf:"helper_addresses,omitempty"`

	// (String)
	IPAccessGroupIn *string `json:"ipAccessGroupIn,omitempty" tf:"ip_access_group_in,omitempty"`

	// (Boolean) inbound packets
	// inbound packets
	IPAccessGroupInEnable *bool `json:"ipAccessGroupInEnable,omitempty" tf:"ip_access_group_in_enable,omitempty"`

	// (String)
	IPAccessGroupOut *string `json:"ipAccessGroupOut,omitempty" tf:"ip_access_group_out,omitempty"`

	// (Boolean) outbound packets
	// outbound packets
	IPAccessGroupOutEnable *bool `json:"ipAccessGroupOutEnable,omitempty" tf:"ip_access_group_out_enable,omitempty"`

	// (Number) Rate Limit
	// Rate Limit
	// - Range: `0`-`4294967295`
	IPArpInspectionLimitRate *float64 `json:"ipArpInspectionLimitRate,omitempty" tf:"ip_arp_inspection_limit_rate,omitempty"`

	// (Boolean) Configure Trust state
	// Configure Trust state
	IPArpInspectionTrust *bool `json:"ipArpInspectionTrust,omitempty" tf:"ip_arp_inspection_trust,omitempty"`

	// (String) Set source interface for relayed messages
	// Set source interface for relayed messages
	IPDHCPRelaySourceInterface *string `json:"ipDhcpRelaySourceInterface,omitempty" tf:"ip_dhcp_relay_source_interface,omitempty"`

	// (Boolean) DHCP Snooping trust config
	// DHCP Snooping trust config
	IPDHCPSnoopingTrust *bool `json:"ipDhcpSnoopingTrust,omitempty" tf:"ip_dhcp_snooping_trust,omitempty"`

	// (Attributes List) Apply a Flow Monitor (see below for nested schema)
	IPFlowMonitors []PortChannelIPFlowMonitorsInitParameters `json:"ipFlowMonitors,omitempty" tf:"ip_flow_monitors,omitempty"`

	// (Number) IGMP version
	// IGMP version
	// - Range: `1`-`3`
	IPIgmpVersion *float64 `json:"ipIgmpVersion,omitempty" tf:"ip_igmp_version,omitempty"`

	// (Boolean) Inside interface for address translation
	// Inside interface for address translation
	IPNATInside *bool `json:"ipNatInside,omitempty" tf:"ip_nat_inside,omitempty"`

	// (Boolean) Outside interface for address translation
	// Outside interface for address translation
	IPNATOutside *bool `json:"ipNatOutside,omitempty" tf:"ip_nat_outside,omitempty"`

	// (Boolean) Enable proxy ARP
	// Enable proxy ARP
	IPProxyArp *bool `json:"ipProxyArp,omitempty" tf:"ip_proxy_arp,omitempty"`

	// (Boolean) Enable sending ICMP Redirect messages
	// Enable sending ICMP Redirect messages
	IPRedirects *bool `json:"ipRedirects,omitempty" tf:"ip_redirects,omitempty"`

	// (String)
	IPRouterIsis *string `json:"ipRouterIsis,omitempty" tf:"ip_router_isis,omitempty"`

	// (Boolean) Enable sending ICMP Unreachable messages
	// Enable sending ICMP Unreachable messages
	IPUnreachables *bool `json:"ipUnreachables,omitempty" tf:"ip_unreachables,omitempty"`

	// (Boolean) Allow default route to match when checking source address
	// Allow default route to match when checking source address
	IPVerifyUnicastSourceAllowDefault *bool `json:"ipVerifyUnicastSourceAllowDefault,omitempty" tf:"ip_verify_unicast_source_allow_default,omitempty"`

	// (Boolean) Allow router to ping itself (opens vulnerability in verification)
	// Allow router to ping itself (opens vulnerability in verification)
	IPVerifyUnicastSourceAllowSelfPing *bool `json:"ipVerifyUnicastSourceAllowSelfPing,omitempty" tf:"ip_verify_unicast_source_allow_self_ping,omitempty"`

	// (String) Specify reachability check to apply to the source address
	// Specify reachability check to apply to the source address
	// - Choices: `any`, `rx`
	IPVerifyUnicastSourceReachableVia *string `json:"ipVerifyUnicastSourceReachableVia,omitempty" tf:"ip_verify_unicast_source_reachable_via,omitempty"`

	// (String) Ip address
	// Ip address
	IPv4Address *string `json:"ipv4Address,omitempty" tf:"ipv4_address,omitempty"`

	// (Boolean) IP Address negotiated via DHCP
	// IP Address negotiated via DHCP
	IPv4AddressDHCP *bool `json:"ipv4AddressDhcp,omitempty" tf:"ipv4_address_dhcp,omitempty"`

	// (String) Ip subnet mask
	// Ip subnet mask
	IPv4AddressMask *string `json:"ipv4AddressMask,omitempty" tf:"ipv4_address_mask,omitempty"`

	// (Boolean) Insert default route
	// Insert default route
	IPv6AddressAutoconfigDefault *bool `json:"ipv6AddressAutoconfigDefault,omitempty" tf:"ipv6_address_autoconfig_default,omitempty"`

	// (Boolean) Obtain IPv6 address from DHCP server
	// Obtain IPv6 address from DHCP server
	IPv6AddressDHCP *bool `json:"ipv6AddressDhcp,omitempty" tf:"ipv6_address_dhcp,omitempty"`

	// (Attributes List) (see below for nested schema)
	IPv6Addresses []PortChannelIPv6AddressesInitParameters `json:"ipv6Addresses,omitempty" tf:"ipv6_addresses,omitempty"`

	// delegation name
	// IPv6 DHCP client prefix-delegation name
	IPv6DHCPClientPd *string `json:"ipv6DhcpClientPd,omitempty" tf:"ipv6_dhcp_client_pd,omitempty"`

	// Commit for prefix-delegation
	// Enable Rapid-Commit for prefix-delegation
	IPv6DHCPClientPdRapidCommit *bool `json:"ipv6DhcpClientPdRapidCommit,omitempty" tf:"ipv6_dhcp_client_pd_rapid_commit,omitempty"`

	// (Attributes List) (see below for nested schema)
	IPv6DHCPRelayDestinations []PortChannelIPv6DHCPRelayDestinationsInitParameters `json:"ipv6DhcpRelayDestinations,omitempty" tf:"ipv6_dhcp_relay_destinations,omitempty"`

	// Forward Messages
	// Insert VSS option in Relay-Forward Messages
	IPv6DHCPRelayOptionVPN *bool `json:"ipv6DhcpRelayOptionVpn,omitempty" tf:"ipv6_dhcp_relay_option_vpn,omitempty"`

	// replies
	// Interface is trusted to process relay-replies
	IPv6DHCPRelayTrust *bool `json:"ipv6DhcpRelayTrust,omitempty" tf:"ipv6_dhcp_relay_trust,omitempty"`

	// (Attributes List) Act as an IPv6 DHCP server (see below for nested schema)
	IPv6DHCPServers []PortChannelIPv6DHCPServersInitParameters `json:"ipv6DhcpServers,omitempty" tf:"ipv6_dhcp_servers,omitempty"`

	// (Boolean) Enable IPv6 on interface
	// Enable IPv6 on interface
	IPv6Enable *bool `json:"ipv6Enable,omitempty" tf:"ipv6_enable,omitempty"`

	// (Attributes List) Apply a Flow Monitor (see below for nested schema)
	IPv6FlowMonitors []PortChannelIPv6FlowMonitorsInitParameters `json:"ipv6FlowMonitors,omitempty" tf:"ipv6_flow_monitors,omitempty"`

	// (Attributes List) (see below for nested schema)
	IPv6LinkLocalAddresses []PortChannelIPv6LinkLocalAddressesInitParameters `json:"ipv6LinkLocalAddresses,omitempty" tf:"ipv6_link_local_addresses,omitempty"`

	// (Number) Set IPv6 Maximum Transmission Unit
	// Set IPv6 Maximum Transmission Unit
	// - Range: `1280`-`9976`
	IPv6Mtu *float64 `json:"ipv6Mtu,omitempty" tf:"ipv6_mtu,omitempty"`

	// (Boolean) Suppress all IPv6 RA
	// Suppress all IPv6 RA
	IPv6NdRaSuppressAll *bool `json:"ipv6NdRaSuppressAll,omitempty" tf:"ipv6_nd_ra_suppress_all,omitempty"`

	// (Number) Specify interval for load calculation for an interface
	// Specify interval for load calculation for an interface
	// - Range: `30`-`600`
	LoadInterval *float64 `json:"loadInterval,omitempty" tf:"load_interval,omitempty"`

	// (Boolean) UPDOWN and CHANGE messages
	// UPDOWN and CHANGE messages
	LoggingEventLinkStatusEnable *bool `json:"loggingEventLinkStatusEnable,omitempty" tf:"logging_event_link_status_enable,omitempty"`

	// (Number) Set the interface Maximum Transmission Unit (MTU)
	// Set the interface Maximum Transmission Unit (MTU)
	// - Range: `64`-`18000`
	Mtu *float64 `json:"mtu,omitempty" tf:"mtu,omitempty"`

	// Range: 1-512
	//
	// - Range: `1`-`512`
	Name *float64 `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) Enable link autonegotiation
	// Enable link autonegotiation
	NegotiationAuto *bool `json:"negotiationAuto,omitempty" tf:"negotiation_auto,omitempty"`

	// (Boolean) Shutdown the selected interface
	// Shutdown the selected interface
	Shutdown *bool `json:"shutdown,omitempty" tf:"shutdown,omitempty"`

	// (Boolean) Allow SNMP LINKUP and LINKDOWN traps
	// Allow SNMP LINKUP and LINKDOWN traps
	SnmpTrapLinkStatus *bool `json:"snmpTrapLinkStatus,omitempty" tf:"snmp_trap_link_status,omitempty"`

	// (String) Change an interface's spanning tree guard mode
	// Change an interface's spanning tree guard mode
	// - Choices: `loop`, `none`, `root`
	SpanningTreeGuard *string `json:"spanningTreeGuard,omitempty" tf:"spanning_tree_guard,omitempty"`

	// (String) Specify a link type for spanning tree tree protocol use
	// Specify a link type for spanning tree tree protocol use
	// - Choices: `point-to-point`, `shared`
	SpanningTreeLinkType *string `json:"spanningTreeLinkType,omitempty" tf:"spanning_tree_link_type,omitempty"`

	// (Boolean) (DEPRECATED) Spanning tree portfast options
	// (DEPRECATED) Spanning tree portfast options
	SpanningTreePortfast *bool `json:"spanningTreePortfast,omitempty" tf:"spanning_tree_portfast,omitempty"`

	// (Boolean) (DEPRECATED) Disable portfast for this interface
	// (DEPRECATED) Disable portfast for this interface
	SpanningTreePortfastDisable *bool `json:"spanningTreePortfastDisable,omitempty" tf:"spanning_tree_portfast_disable,omitempty"`

	// (Boolean) (DEPRECATED) Enable portfast edge on the interface
	// (DEPRECATED) Enable portfast edge on the interface
	SpanningTreePortfastEdge *bool `json:"spanningTreePortfastEdge,omitempty" tf:"spanning_tree_portfast_edge,omitempty"`

	// (Boolean) (DEPRECATED) Enable portfast on the interface even in trunk mode
	// (DEPRECATED) Enable portfast on the interface even in trunk mode
	SpanningTreePortfastTrunk *bool `json:"spanningTreePortfastTrunk,omitempty" tf:"spanning_tree_portfast_trunk,omitempty"`

	// (Boolean)
	Switchport *bool `json:"switchport,omitempty" tf:"switchport,omitempty"`

	// (String) trusted device class
	// trusted device class
	// - Choices: `cisco-phone`, `cts`, `ip-camera`, `media-player`
	TrustDevice *string `json:"trustDevice,omitempty" tf:"trust_device,omitempty"`

	// (String) Configure forwarding table
	// Configure forwarding table
	// +crossplane:generate:reference:type=github.com/upbound/provider-upjet-iosxe/apis/cluster/routing/v1alpha1.VRF
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name",false)
	VrfForwarding *string `json:"vrfForwarding,omitempty" tf:"vrf_forwarding,omitempty"`

	// Reference to a VRF in routing to populate vrfForwarding.
	// +kubebuilder:validation:Optional
	VrfForwardingRef *v2.Reference `json:"vrfForwardingRef,omitempty" tf:"-"`

	// Selector for a VRF in routing to populate vrfForwarding.
	// +kubebuilder:validation:Optional
	VrfForwardingSelector *v2.Selector `json:"vrfForwardingSelector,omitempty" tf:"-"`

	// (String) Security zone
	// Security zone
	ZoneMemberSecurity *string `json:"zoneMemberSecurity,omitempty" tf:"zone_member_security,omitempty"`
}

type PortChannelObservation struct {

	// (Number) Set ARP cache timeout
	// Set ARP cache timeout
	// - Range: `0`-`2147483`
	ArpTimeout *float64 `json:"arpTimeout,omitempty" tf:"arp_timeout,omitempty"`

	// (Boolean) Configure classification for untrusted devices
	// Configure classification for untrusted devices
	AutoQosClassify *bool `json:"autoQosClassify,omitempty" tf:"auto_qos_classify,omitempty"`

	// (Boolean) Configure QoS policing for untrusted devices
	// Configure QoS policing for untrusted devices
	AutoQosClassifyPolice *bool `json:"autoQosClassifyPolice,omitempty" tf:"auto_qos_classify_police,omitempty"`

	// (Boolean) Trust the DSCP/CoS marking
	// Trust the DSCP/CoS marking
	AutoQosTrust *bool `json:"autoQosTrust,omitempty" tf:"auto_qos_trust,omitempty"`

	// (Boolean) Trust the CoS marking
	// Trust the CoS marking
	AutoQosTrustCos *bool `json:"autoQosTrustCos,omitempty" tf:"auto_qos_trust_cos,omitempty"`

	// (Boolean) Trust the DSCP marking
	// Trust the DSCP marking
	AutoQosTrustDscp *bool `json:"autoQosTrustDscp,omitempty" tf:"auto_qos_trust_dscp,omitempty"`

	// (Boolean) Trust the QoS marking of the Cisco Telepresence System
	// Trust the QoS marking of the Cisco Telepresence System
	AutoQosVideoCts *bool `json:"autoQosVideoCts,omitempty" tf:"auto_qos_video_cts,omitempty"`

	// (Boolean) Trust the QoS marking of the Ip Video Surveillance camera
	// Trust the QoS marking of the Ip Video Surveillance camera
	AutoQosVideoIPCamera *bool `json:"autoQosVideoIpCamera,omitempty" tf:"auto_qos_video_ip_camera,omitempty"`

	// (Boolean) Trust the Qos marking of the Cisco Media Player
	// Trust the Qos marking of the Cisco Media Player
	AutoQosVideoMediaPlayer *bool `json:"autoQosVideoMediaPlayer,omitempty" tf:"auto_qos_video_media_player,omitempty"`

	// (Boolean) Trust the QoS marking of Cisco IP Phone
	// Trust the QoS marking of Cisco IP Phone
	AutoQosVoIPCiscoPhone *bool `json:"autoQosVoipCiscoPhone,omitempty" tf:"auto_qos_voip_cisco_phone,omitempty"`

	// (Boolean) Trust the QoS marking of Cisco IP SoftPhone
	// Trust the QoS marking of Cisco IP SoftPhone
	AutoQosVoIPCiscoSoftphone *bool `json:"autoQosVoipCiscoSoftphone,omitempty" tf:"auto_qos_voip_cisco_softphone,omitempty"`

	// (Boolean) Trust the DSCP/CoS marking
	// Trust the DSCP/CoS marking
	AutoQosVoIPTrust *bool `json:"autoQosVoipTrust,omitempty" tf:"auto_qos_voip_trust,omitempty"`

	// (Boolean) Use echo adjunct as bfd detection mechanism
	// Use echo adjunct as bfd detection mechanism
	BfdEcho *bool `json:"bfdEcho,omitempty" tf:"bfd_echo,omitempty"`

	// (Boolean) Enable BFD under the interface
	// Enable BFD under the interface
	BfdEnable *bool `json:"bfdEnable,omitempty" tf:"bfd_enable,omitempty"`

	// Range: 50-9999
	//
	// - Range: `50`-`9999`
	BfdInterval *float64 `json:"bfdInterval,omitempty" tf:"bfd_interval,omitempty"`

	// (Number) Minimum receive interval capability
	// Minimum receive interval capability
	// - Range: `50`-`9999`
	BfdIntervalMinRx *float64 `json:"bfdIntervalMinRx,omitempty" tf:"bfd_interval_min_rx,omitempty"`

	// (Number) Multiplier value used to compute holddown
	// Multiplier value used to compute holddown
	// - Range: `3`-`50`
	BfdIntervalMultiplier *float64 `json:"bfdIntervalMultiplier,omitempty" tf:"bfd_interval_multiplier,omitempty"`

	// (String) The Source IP address to be used for BFD sessions over this interface.
	// The Source IP address to be used for BFD sessions over this interface.
	BfdLocalAddress *string `json:"bfdLocalAddress,omitempty" tf:"bfd_local_address,omitempty"`

	// (String) BFD template
	// BFD template
	BfdTemplate *string `json:"bfdTemplate,omitempty" tf:"bfd_template,omitempty"`

	// (Boolean) Disable BPDU guard for this interface
	// Disable BPDU guard for this interface
	BpduguardDisable *bool `json:"bpduguardDisable,omitempty" tf:"bpduguard_disable,omitempty"`

	// (Boolean) Enable BPDU guard for this interface
	// Enable BPDU guard for this interface
	BpduguardEnable *bool `json:"bpduguardEnable,omitempty" tf:"bpduguard_enable,omitempty"`

	// is. Default value is all.
	// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is. Default value is `all`.
	// - Choices: `all`, `attributes`
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// (String) Interface specific description
	// Interface specific description
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// tracking on the interface
	// Configure device-tracking on the interface
	DeviceTracking *bool `json:"deviceTracking,omitempty" tf:"device_tracking,omitempty"`

	// (Attributes List) (see below for nested schema)
	DeviceTrackingAttachedPolicies []PortChannelDeviceTrackingAttachedPoliciesObservation `json:"deviceTrackingAttachedPolicies,omitempty" tf:"device_tracking_attached_policies,omitempty"`

	// (Attributes List) Ethernet segment local discriminator value (see below for nested schema)
	EvpnEthernetSegments []PortChannelEvpnEthernetSegmentsObservation `json:"evpnEthernetSegments,omitempty" tf:"evpn_ethernet_segments,omitempty"`

	// (Attributes List) Ethernet segment local discriminator value, DEPRECATED (see below for nested schema)
	EvpnEthernetSegmentsLegacy []EvpnEthernetSegmentsLegacyObservation `json:"evpnEthernetSegmentsLegacy,omitempty" tf:"evpn_ethernet_segments_legacy,omitempty"`

	// (Attributes List) Specify a destination address for UDP broadcasts (see below for nested schema)
	HelperAddresses []PortChannelHelperAddressesObservation `json:"helperAddresses,omitempty" tf:"helper_addresses,omitempty"`

	// (String) The path of the object.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String)
	IPAccessGroupIn *string `json:"ipAccessGroupIn,omitempty" tf:"ip_access_group_in,omitempty"`

	// (Boolean) inbound packets
	// inbound packets
	IPAccessGroupInEnable *bool `json:"ipAccessGroupInEnable,omitempty" tf:"ip_access_group_in_enable,omitempty"`

	// (String)
	IPAccessGroupOut *string `json:"ipAccessGroupOut,omitempty" tf:"ip_access_group_out,omitempty"`

	// (Boolean) outbound packets
	// outbound packets
	IPAccessGroupOutEnable *bool `json:"ipAccessGroupOutEnable,omitempty" tf:"ip_access_group_out_enable,omitempty"`

	// (Number) Rate Limit
	// Rate Limit
	// - Range: `0`-`4294967295`
	IPArpInspectionLimitRate *float64 `json:"ipArpInspectionLimitRate,omitempty" tf:"ip_arp_inspection_limit_rate,omitempty"`

	// (Boolean) Configure Trust state
	// Configure Trust state
	IPArpInspectionTrust *bool `json:"ipArpInspectionTrust,omitempty" tf:"ip_arp_inspection_trust,omitempty"`

	// (String) Set source interface for relayed messages
	// Set source interface for relayed messages
	IPDHCPRelaySourceInterface *string `json:"ipDhcpRelaySourceInterface,omitempty" tf:"ip_dhcp_relay_source_interface,omitempty"`

	// (Boolean) DHCP Snooping trust config
	// DHCP Snooping trust config
	IPDHCPSnoopingTrust *bool `json:"ipDhcpSnoopingTrust,omitempty" tf:"ip_dhcp_snooping_trust,omitempty"`

	// (Attributes List) Apply a Flow Monitor (see below for nested schema)
	IPFlowMonitors []PortChannelIPFlowMonitorsObservation `json:"ipFlowMonitors,omitempty" tf:"ip_flow_monitors,omitempty"`

	// (Number) IGMP version
	// IGMP version
	// - Range: `1`-`3`
	IPIgmpVersion *float64 `json:"ipIgmpVersion,omitempty" tf:"ip_igmp_version,omitempty"`

	// (Boolean) Inside interface for address translation
	// Inside interface for address translation
	IPNATInside *bool `json:"ipNatInside,omitempty" tf:"ip_nat_inside,omitempty"`

	// (Boolean) Outside interface for address translation
	// Outside interface for address translation
	IPNATOutside *bool `json:"ipNatOutside,omitempty" tf:"ip_nat_outside,omitempty"`

	// (Boolean) Enable proxy ARP
	// Enable proxy ARP
	IPProxyArp *bool `json:"ipProxyArp,omitempty" tf:"ip_proxy_arp,omitempty"`

	// (Boolean) Enable sending ICMP Redirect messages
	// Enable sending ICMP Redirect messages
	IPRedirects *bool `json:"ipRedirects,omitempty" tf:"ip_redirects,omitempty"`

	// (String)
	IPRouterIsis *string `json:"ipRouterIsis,omitempty" tf:"ip_router_isis,omitempty"`

	// (Boolean) Enable sending ICMP Unreachable messages
	// Enable sending ICMP Unreachable messages
	IPUnreachables *bool `json:"ipUnreachables,omitempty" tf:"ip_unreachables,omitempty"`

	// (Boolean) Allow default route to match when checking source address
	// Allow default route to match when checking source address
	IPVerifyUnicastSourceAllowDefault *bool `json:"ipVerifyUnicastSourceAllowDefault,omitempty" tf:"ip_verify_unicast_source_allow_default,omitempty"`

	// (Boolean) Allow router to ping itself (opens vulnerability in verification)
	// Allow router to ping itself (opens vulnerability in verification)
	IPVerifyUnicastSourceAllowSelfPing *bool `json:"ipVerifyUnicastSourceAllowSelfPing,omitempty" tf:"ip_verify_unicast_source_allow_self_ping,omitempty"`

	// (String) Specify reachability check to apply to the source address
	// Specify reachability check to apply to the source address
	// - Choices: `any`, `rx`
	IPVerifyUnicastSourceReachableVia *string `json:"ipVerifyUnicastSourceReachableVia,omitempty" tf:"ip_verify_unicast_source_reachable_via,omitempty"`

	// (String) Ip address
	// Ip address
	IPv4Address *string `json:"ipv4Address,omitempty" tf:"ipv4_address,omitempty"`

	// (Boolean) IP Address negotiated via DHCP
	// IP Address negotiated via DHCP
	IPv4AddressDHCP *bool `json:"ipv4AddressDhcp,omitempty" tf:"ipv4_address_dhcp,omitempty"`

	// (String) Ip subnet mask
	// Ip subnet mask
	IPv4AddressMask *string `json:"ipv4AddressMask,omitempty" tf:"ipv4_address_mask,omitempty"`

	// (Boolean) Insert default route
	// Insert default route
	IPv6AddressAutoconfigDefault *bool `json:"ipv6AddressAutoconfigDefault,omitempty" tf:"ipv6_address_autoconfig_default,omitempty"`

	// (Boolean) Obtain IPv6 address from DHCP server
	// Obtain IPv6 address from DHCP server
	IPv6AddressDHCP *bool `json:"ipv6AddressDhcp,omitempty" tf:"ipv6_address_dhcp,omitempty"`

	// (Attributes List) (see below for nested schema)
	IPv6Addresses []PortChannelIPv6AddressesObservation `json:"ipv6Addresses,omitempty" tf:"ipv6_addresses,omitempty"`

	// delegation name
	// IPv6 DHCP client prefix-delegation name
	IPv6DHCPClientPd *string `json:"ipv6DhcpClientPd,omitempty" tf:"ipv6_dhcp_client_pd,omitempty"`

	// Commit for prefix-delegation
	// Enable Rapid-Commit for prefix-delegation
	IPv6DHCPClientPdRapidCommit *bool `json:"ipv6DhcpClientPdRapidCommit,omitempty" tf:"ipv6_dhcp_client_pd_rapid_commit,omitempty"`

	// (Attributes List) (see below for nested schema)
	IPv6DHCPRelayDestinations []PortChannelIPv6DHCPRelayDestinationsObservation `json:"ipv6DhcpRelayDestinations,omitempty" tf:"ipv6_dhcp_relay_destinations,omitempty"`

	// Forward Messages
	// Insert VSS option in Relay-Forward Messages
	IPv6DHCPRelayOptionVPN *bool `json:"ipv6DhcpRelayOptionVpn,omitempty" tf:"ipv6_dhcp_relay_option_vpn,omitempty"`

	// replies
	// Interface is trusted to process relay-replies
	IPv6DHCPRelayTrust *bool `json:"ipv6DhcpRelayTrust,omitempty" tf:"ipv6_dhcp_relay_trust,omitempty"`

	// (Attributes List) Act as an IPv6 DHCP server (see below for nested schema)
	IPv6DHCPServers []PortChannelIPv6DHCPServersObservation `json:"ipv6DhcpServers,omitempty" tf:"ipv6_dhcp_servers,omitempty"`

	// (Boolean) Enable IPv6 on interface
	// Enable IPv6 on interface
	IPv6Enable *bool `json:"ipv6Enable,omitempty" tf:"ipv6_enable,omitempty"`

	// (Attributes List) Apply a Flow Monitor (see below for nested schema)
	IPv6FlowMonitors []PortChannelIPv6FlowMonitorsObservation `json:"ipv6FlowMonitors,omitempty" tf:"ipv6_flow_monitors,omitempty"`

	// (Attributes List) (see below for nested schema)
	IPv6LinkLocalAddresses []PortChannelIPv6LinkLocalAddressesObservation `json:"ipv6LinkLocalAddresses,omitempty" tf:"ipv6_link_local_addresses,omitempty"`

	// (Number) Set IPv6 Maximum Transmission Unit
	// Set IPv6 Maximum Transmission Unit
	// - Range: `1280`-`9976`
	IPv6Mtu *float64 `json:"ipv6Mtu,omitempty" tf:"ipv6_mtu,omitempty"`

	// (Boolean) Suppress all IPv6 RA
	// Suppress all IPv6 RA
	IPv6NdRaSuppressAll *bool `json:"ipv6NdRaSuppressAll,omitempty" tf:"ipv6_nd_ra_suppress_all,omitempty"`

	// (Number) Specify interval for load calculation for an interface
	// Specify interval for load calculation for an interface
	// - Range: `30`-`600`
	LoadInterval *float64 `json:"loadInterval,omitempty" tf:"load_interval,omitempty"`

	// (Boolean) UPDOWN and CHANGE messages
	// UPDOWN and CHANGE messages
	LoggingEventLinkStatusEnable *bool `json:"loggingEventLinkStatusEnable,omitempty" tf:"logging_event_link_status_enable,omitempty"`

	// (Number) Set the interface Maximum Transmission Unit (MTU)
	// Set the interface Maximum Transmission Unit (MTU)
	// - Range: `64`-`18000`
	Mtu *float64 `json:"mtu,omitempty" tf:"mtu,omitempty"`

	// Range: 1-512
	//
	// - Range: `1`-`512`
	Name *float64 `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) Enable link autonegotiation
	// Enable link autonegotiation
	NegotiationAuto *bool `json:"negotiationAuto,omitempty" tf:"negotiation_auto,omitempty"`

	// (Boolean) Shutdown the selected interface
	// Shutdown the selected interface
	Shutdown *bool `json:"shutdown,omitempty" tf:"shutdown,omitempty"`

	// (Boolean) Allow SNMP LINKUP and LINKDOWN traps
	// Allow SNMP LINKUP and LINKDOWN traps
	SnmpTrapLinkStatus *bool `json:"snmpTrapLinkStatus,omitempty" tf:"snmp_trap_link_status,omitempty"`

	// (String) Change an interface's spanning tree guard mode
	// Change an interface's spanning tree guard mode
	// - Choices: `loop`, `none`, `root`
	SpanningTreeGuard *string `json:"spanningTreeGuard,omitempty" tf:"spanning_tree_guard,omitempty"`

	// (String) Specify a link type for spanning tree tree protocol use
	// Specify a link type for spanning tree tree protocol use
	// - Choices: `point-to-point`, `shared`
	SpanningTreeLinkType *string `json:"spanningTreeLinkType,omitempty" tf:"spanning_tree_link_type,omitempty"`

	// (Boolean) (DEPRECATED) Spanning tree portfast options
	// (DEPRECATED) Spanning tree portfast options
	SpanningTreePortfast *bool `json:"spanningTreePortfast,omitempty" tf:"spanning_tree_portfast,omitempty"`

	// (Boolean) (DEPRECATED) Disable portfast for this interface
	// (DEPRECATED) Disable portfast for this interface
	SpanningTreePortfastDisable *bool `json:"spanningTreePortfastDisable,omitempty" tf:"spanning_tree_portfast_disable,omitempty"`

	// (Boolean) (DEPRECATED) Enable portfast edge on the interface
	// (DEPRECATED) Enable portfast edge on the interface
	SpanningTreePortfastEdge *bool `json:"spanningTreePortfastEdge,omitempty" tf:"spanning_tree_portfast_edge,omitempty"`

	// (Boolean) (DEPRECATED) Enable portfast on the interface even in trunk mode
	// (DEPRECATED) Enable portfast on the interface even in trunk mode
	SpanningTreePortfastTrunk *bool `json:"spanningTreePortfastTrunk,omitempty" tf:"spanning_tree_portfast_trunk,omitempty"`

	// (Boolean)
	Switchport *bool `json:"switchport,omitempty" tf:"switchport,omitempty"`

	// (String) trusted device class
	// trusted device class
	// - Choices: `cisco-phone`, `cts`, `ip-camera`, `media-player`
	TrustDevice *string `json:"trustDevice,omitempty" tf:"trust_device,omitempty"`

	// (String) Configure forwarding table
	// Configure forwarding table
	VrfForwarding *string `json:"vrfForwarding,omitempty" tf:"vrf_forwarding,omitempty"`

	// (String) Security zone
	// Security zone
	ZoneMemberSecurity *string `json:"zoneMemberSecurity,omitempty" tf:"zone_member_security,omitempty"`
}

type PortChannelParameters struct {

	// (Number) Set ARP cache timeout
	// Set ARP cache timeout
	// - Range: `0`-`2147483`
	// +kubebuilder:validation:Optional
	ArpTimeout *float64 `json:"arpTimeout,omitempty" tf:"arp_timeout,omitempty"`

	// (Boolean) Configure classification for untrusted devices
	// Configure classification for untrusted devices
	// +kubebuilder:validation:Optional
	AutoQosClassify *bool `json:"autoQosClassify,omitempty" tf:"auto_qos_classify,omitempty"`

	// (Boolean) Configure QoS policing for untrusted devices
	// Configure QoS policing for untrusted devices
	// +kubebuilder:validation:Optional
	AutoQosClassifyPolice *bool `json:"autoQosClassifyPolice,omitempty" tf:"auto_qos_classify_police,omitempty"`

	// (Boolean) Trust the DSCP/CoS marking
	// Trust the DSCP/CoS marking
	// +kubebuilder:validation:Optional
	AutoQosTrust *bool `json:"autoQosTrust,omitempty" tf:"auto_qos_trust,omitempty"`

	// (Boolean) Trust the CoS marking
	// Trust the CoS marking
	// +kubebuilder:validation:Optional
	AutoQosTrustCos *bool `json:"autoQosTrustCos,omitempty" tf:"auto_qos_trust_cos,omitempty"`

	// (Boolean) Trust the DSCP marking
	// Trust the DSCP marking
	// +kubebuilder:validation:Optional
	AutoQosTrustDscp *bool `json:"autoQosTrustDscp,omitempty" tf:"auto_qos_trust_dscp,omitempty"`

	// (Boolean) Trust the QoS marking of the Cisco Telepresence System
	// Trust the QoS marking of the Cisco Telepresence System
	// +kubebuilder:validation:Optional
	AutoQosVideoCts *bool `json:"autoQosVideoCts,omitempty" tf:"auto_qos_video_cts,omitempty"`

	// (Boolean) Trust the QoS marking of the Ip Video Surveillance camera
	// Trust the QoS marking of the Ip Video Surveillance camera
	// +kubebuilder:validation:Optional
	AutoQosVideoIPCamera *bool `json:"autoQosVideoIpCamera,omitempty" tf:"auto_qos_video_ip_camera,omitempty"`

	// (Boolean) Trust the Qos marking of the Cisco Media Player
	// Trust the Qos marking of the Cisco Media Player
	// +kubebuilder:validation:Optional
	AutoQosVideoMediaPlayer *bool `json:"autoQosVideoMediaPlayer,omitempty" tf:"auto_qos_video_media_player,omitempty"`

	// (Boolean) Trust the QoS marking of Cisco IP Phone
	// Trust the QoS marking of Cisco IP Phone
	// +kubebuilder:validation:Optional
	AutoQosVoIPCiscoPhone *bool `json:"autoQosVoipCiscoPhone,omitempty" tf:"auto_qos_voip_cisco_phone,omitempty"`

	// (Boolean) Trust the QoS marking of Cisco IP SoftPhone
	// Trust the QoS marking of Cisco IP SoftPhone
	// +kubebuilder:validation:Optional
	AutoQosVoIPCiscoSoftphone *bool `json:"autoQosVoipCiscoSoftphone,omitempty" tf:"auto_qos_voip_cisco_softphone,omitempty"`

	// (Boolean) Trust the DSCP/CoS marking
	// Trust the DSCP/CoS marking
	// +kubebuilder:validation:Optional
	AutoQosVoIPTrust *bool `json:"autoQosVoipTrust,omitempty" tf:"auto_qos_voip_trust,omitempty"`

	// (Boolean) Use echo adjunct as bfd detection mechanism
	// Use echo adjunct as bfd detection mechanism
	// +kubebuilder:validation:Optional
	BfdEcho *bool `json:"bfdEcho,omitempty" tf:"bfd_echo,omitempty"`

	// (Boolean) Enable BFD under the interface
	// Enable BFD under the interface
	// +kubebuilder:validation:Optional
	BfdEnable *bool `json:"bfdEnable,omitempty" tf:"bfd_enable,omitempty"`

	// Range: 50-9999
	//
	// - Range: `50`-`9999`
	// +kubebuilder:validation:Optional
	BfdInterval *float64 `json:"bfdInterval,omitempty" tf:"bfd_interval,omitempty"`

	// (Number) Minimum receive interval capability
	// Minimum receive interval capability
	// - Range: `50`-`9999`
	// +kubebuilder:validation:Optional
	BfdIntervalMinRx *float64 `json:"bfdIntervalMinRx,omitempty" tf:"bfd_interval_min_rx,omitempty"`

	// (Number) Multiplier value used to compute holddown
	// Multiplier value used to compute holddown
	// - Range: `3`-`50`
	// +kubebuilder:validation:Optional
	BfdIntervalMultiplier *float64 `json:"bfdIntervalMultiplier,omitempty" tf:"bfd_interval_multiplier,omitempty"`

	// (String) The Source IP address to be used for BFD sessions over this interface.
	// The Source IP address to be used for BFD sessions over this interface.
	// +kubebuilder:validation:Optional
	BfdLocalAddress *string `json:"bfdLocalAddress,omitempty" tf:"bfd_local_address,omitempty"`

	// (String) BFD template
	// BFD template
	// +kubebuilder:validation:Optional
	BfdTemplate *string `json:"bfdTemplate,omitempty" tf:"bfd_template,omitempty"`

	// (Boolean) Disable BPDU guard for this interface
	// Disable BPDU guard for this interface
	// +kubebuilder:validation:Optional
	BpduguardDisable *bool `json:"bpduguardDisable,omitempty" tf:"bpduguard_disable,omitempty"`

	// (Boolean) Enable BPDU guard for this interface
	// Enable BPDU guard for this interface
	// +kubebuilder:validation:Optional
	BpduguardEnable *bool `json:"bpduguardEnable,omitempty" tf:"bpduguard_enable,omitempty"`

	// is. Default value is all.
	// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is. Default value is `all`.
	// - Choices: `all`, `attributes`
	// +kubebuilder:validation:Optional
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// (String) Interface specific description
	// Interface specific description
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	// +kubebuilder:validation:Optional
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// tracking on the interface
	// Configure device-tracking on the interface
	// +kubebuilder:validation:Optional
	DeviceTracking *bool `json:"deviceTracking,omitempty" tf:"device_tracking,omitempty"`

	// (Attributes List) (see below for nested schema)
	// +kubebuilder:validation:Optional
	DeviceTrackingAttachedPolicies []PortChannelDeviceTrackingAttachedPoliciesParameters `json:"deviceTrackingAttachedPolicies,omitempty" tf:"device_tracking_attached_policies,omitempty"`

	// (Attributes List) Ethernet segment local discriminator value (see below for nested schema)
	// +kubebuilder:validation:Optional
	EvpnEthernetSegments []PortChannelEvpnEthernetSegmentsParameters `json:"evpnEthernetSegments,omitempty" tf:"evpn_ethernet_segments,omitempty"`

	// (Attributes List) Ethernet segment local discriminator value, DEPRECATED (see below for nested schema)
	// +kubebuilder:validation:Optional
	EvpnEthernetSegmentsLegacy []EvpnEthernetSegmentsLegacyParameters `json:"evpnEthernetSegmentsLegacy,omitempty" tf:"evpn_ethernet_segments_legacy,omitempty"`

	// (Attributes List) Specify a destination address for UDP broadcasts (see below for nested schema)
	// +kubebuilder:validation:Optional
	HelperAddresses []PortChannelHelperAddressesParameters `json:"helperAddresses,omitempty" tf:"helper_addresses,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	IPAccessGroupIn *string `json:"ipAccessGroupIn,omitempty" tf:"ip_access_group_in,omitempty"`

	// (Boolean) inbound packets
	// inbound packets
	// +kubebuilder:validation:Optional
	IPAccessGroupInEnable *bool `json:"ipAccessGroupInEnable,omitempty" tf:"ip_access_group_in_enable,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	IPAccessGroupOut *string `json:"ipAccessGroupOut,omitempty" tf:"ip_access_group_out,omitempty"`

	// (Boolean) outbound packets
	// outbound packets
	// +kubebuilder:validation:Optional
	IPAccessGroupOutEnable *bool `json:"ipAccessGroupOutEnable,omitempty" tf:"ip_access_group_out_enable,omitempty"`

	// (Number) Rate Limit
	// Rate Limit
	// - Range: `0`-`4294967295`
	// +kubebuilder:validation:Optional
	IPArpInspectionLimitRate *float64 `json:"ipArpInspectionLimitRate,omitempty" tf:"ip_arp_inspection_limit_rate,omitempty"`

	// (Boolean) Configure Trust state
	// Configure Trust state
	// +kubebuilder:validation:Optional
	IPArpInspectionTrust *bool `json:"ipArpInspectionTrust,omitempty" tf:"ip_arp_inspection_trust,omitempty"`

	// (String) Set source interface for relayed messages
	// Set source interface for relayed messages
	// +kubebuilder:validation:Optional
	IPDHCPRelaySourceInterface *string `json:"ipDhcpRelaySourceInterface,omitempty" tf:"ip_dhcp_relay_source_interface,omitempty"`

	// (Boolean) DHCP Snooping trust config
	// DHCP Snooping trust config
	// +kubebuilder:validation:Optional
	IPDHCPSnoopingTrust *bool `json:"ipDhcpSnoopingTrust,omitempty" tf:"ip_dhcp_snooping_trust,omitempty"`

	// (Attributes List) Apply a Flow Monitor (see below for nested schema)
	// +kubebuilder:validation:Optional
	IPFlowMonitors []PortChannelIPFlowMonitorsParameters `json:"ipFlowMonitors,omitempty" tf:"ip_flow_monitors,omitempty"`

	// (Number) IGMP version
	// IGMP version
	// - Range: `1`-`3`
	// +kubebuilder:validation:Optional
	IPIgmpVersion *float64 `json:"ipIgmpVersion,omitempty" tf:"ip_igmp_version,omitempty"`

	// (Boolean) Inside interface for address translation
	// Inside interface for address translation
	// +kubebuilder:validation:Optional
	IPNATInside *bool `json:"ipNatInside,omitempty" tf:"ip_nat_inside,omitempty"`

	// (Boolean) Outside interface for address translation
	// Outside interface for address translation
	// +kubebuilder:validation:Optional
	IPNATOutside *bool `json:"ipNatOutside,omitempty" tf:"ip_nat_outside,omitempty"`

	// (Boolean) Enable proxy ARP
	// Enable proxy ARP
	// +kubebuilder:validation:Optional
	IPProxyArp *bool `json:"ipProxyArp,omitempty" tf:"ip_proxy_arp,omitempty"`

	// (Boolean) Enable sending ICMP Redirect messages
	// Enable sending ICMP Redirect messages
	// +kubebuilder:validation:Optional
	IPRedirects *bool `json:"ipRedirects,omitempty" tf:"ip_redirects,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	IPRouterIsis *string `json:"ipRouterIsis,omitempty" tf:"ip_router_isis,omitempty"`

	// (Boolean) Enable sending ICMP Unreachable messages
	// Enable sending ICMP Unreachable messages
	// +kubebuilder:validation:Optional
	IPUnreachables *bool `json:"ipUnreachables,omitempty" tf:"ip_unreachables,omitempty"`

	// (Boolean) Allow default route to match when checking source address
	// Allow default route to match when checking source address
	// +kubebuilder:validation:Optional
	IPVerifyUnicastSourceAllowDefault *bool `json:"ipVerifyUnicastSourceAllowDefault,omitempty" tf:"ip_verify_unicast_source_allow_default,omitempty"`

	// (Boolean) Allow router to ping itself (opens vulnerability in verification)
	// Allow router to ping itself (opens vulnerability in verification)
	// +kubebuilder:validation:Optional
	IPVerifyUnicastSourceAllowSelfPing *bool `json:"ipVerifyUnicastSourceAllowSelfPing,omitempty" tf:"ip_verify_unicast_source_allow_self_ping,omitempty"`

	// (String) Specify reachability check to apply to the source address
	// Specify reachability check to apply to the source address
	// - Choices: `any`, `rx`
	// +kubebuilder:validation:Optional
	IPVerifyUnicastSourceReachableVia *string `json:"ipVerifyUnicastSourceReachableVia,omitempty" tf:"ip_verify_unicast_source_reachable_via,omitempty"`

	// (String) Ip address
	// Ip address
	// +kubebuilder:validation:Optional
	IPv4Address *string `json:"ipv4Address,omitempty" tf:"ipv4_address,omitempty"`

	// (Boolean) IP Address negotiated via DHCP
	// IP Address negotiated via DHCP
	// +kubebuilder:validation:Optional
	IPv4AddressDHCP *bool `json:"ipv4AddressDhcp,omitempty" tf:"ipv4_address_dhcp,omitempty"`

	// (String) Ip subnet mask
	// Ip subnet mask
	// +kubebuilder:validation:Optional
	IPv4AddressMask *string `json:"ipv4AddressMask,omitempty" tf:"ipv4_address_mask,omitempty"`

	// (Boolean) Insert default route
	// Insert default route
	// +kubebuilder:validation:Optional
	IPv6AddressAutoconfigDefault *bool `json:"ipv6AddressAutoconfigDefault,omitempty" tf:"ipv6_address_autoconfig_default,omitempty"`

	// (Boolean) Obtain IPv6 address from DHCP server
	// Obtain IPv6 address from DHCP server
	// +kubebuilder:validation:Optional
	IPv6AddressDHCP *bool `json:"ipv6AddressDhcp,omitempty" tf:"ipv6_address_dhcp,omitempty"`

	// (Attributes List) (see below for nested schema)
	// +kubebuilder:validation:Optional
	IPv6Addresses []PortChannelIPv6AddressesParameters `json:"ipv6Addresses,omitempty" tf:"ipv6_addresses,omitempty"`

	// delegation name
	// IPv6 DHCP client prefix-delegation name
	// +kubebuilder:validation:Optional
	IPv6DHCPClientPd *string `json:"ipv6DhcpClientPd,omitempty" tf:"ipv6_dhcp_client_pd,omitempty"`

	// Commit for prefix-delegation
	// Enable Rapid-Commit for prefix-delegation
	// +kubebuilder:validation:Optional
	IPv6DHCPClientPdRapidCommit *bool `json:"ipv6DhcpClientPdRapidCommit,omitempty" tf:"ipv6_dhcp_client_pd_rapid_commit,omitempty"`

	// (Attributes List) (see below for nested schema)
	// +kubebuilder:validation:Optional
	IPv6DHCPRelayDestinations []PortChannelIPv6DHCPRelayDestinationsParameters `json:"ipv6DhcpRelayDestinations,omitempty" tf:"ipv6_dhcp_relay_destinations,omitempty"`

	// Forward Messages
	// Insert VSS option in Relay-Forward Messages
	// +kubebuilder:validation:Optional
	IPv6DHCPRelayOptionVPN *bool `json:"ipv6DhcpRelayOptionVpn,omitempty" tf:"ipv6_dhcp_relay_option_vpn,omitempty"`

	// replies
	// Interface is trusted to process relay-replies
	// +kubebuilder:validation:Optional
	IPv6DHCPRelayTrust *bool `json:"ipv6DhcpRelayTrust,omitempty" tf:"ipv6_dhcp_relay_trust,omitempty"`

	// (Attributes List) Act as an IPv6 DHCP server (see below for nested schema)
	// +kubebuilder:validation:Optional
	IPv6DHCPServers []PortChannelIPv6DHCPServersParameters `json:"ipv6DhcpServers,omitempty" tf:"ipv6_dhcp_servers,omitempty"`

	// (Boolean) Enable IPv6 on interface
	// Enable IPv6 on interface
	// +kubebuilder:validation:Optional
	IPv6Enable *bool `json:"ipv6Enable,omitempty" tf:"ipv6_enable,omitempty"`

	// (Attributes List) Apply a Flow Monitor (see below for nested schema)
	// +kubebuilder:validation:Optional
	IPv6FlowMonitors []PortChannelIPv6FlowMonitorsParameters `json:"ipv6FlowMonitors,omitempty" tf:"ipv6_flow_monitors,omitempty"`

	// (Attributes List) (see below for nested schema)
	// +kubebuilder:validation:Optional
	IPv6LinkLocalAddresses []PortChannelIPv6LinkLocalAddressesParameters `json:"ipv6LinkLocalAddresses,omitempty" tf:"ipv6_link_local_addresses,omitempty"`

	// (Number) Set IPv6 Maximum Transmission Unit
	// Set IPv6 Maximum Transmission Unit
	// - Range: `1280`-`9976`
	// +kubebuilder:validation:Optional
	IPv6Mtu *float64 `json:"ipv6Mtu,omitempty" tf:"ipv6_mtu,omitempty"`

	// (Boolean) Suppress all IPv6 RA
	// Suppress all IPv6 RA
	// +kubebuilder:validation:Optional
	IPv6NdRaSuppressAll *bool `json:"ipv6NdRaSuppressAll,omitempty" tf:"ipv6_nd_ra_suppress_all,omitempty"`

	// (Number) Specify interval for load calculation for an interface
	// Specify interval for load calculation for an interface
	// - Range: `30`-`600`
	// +kubebuilder:validation:Optional
	LoadInterval *float64 `json:"loadInterval,omitempty" tf:"load_interval,omitempty"`

	// (Boolean) UPDOWN and CHANGE messages
	// UPDOWN and CHANGE messages
	// +kubebuilder:validation:Optional
	LoggingEventLinkStatusEnable *bool `json:"loggingEventLinkStatusEnable,omitempty" tf:"logging_event_link_status_enable,omitempty"`

	// (Number) Set the interface Maximum Transmission Unit (MTU)
	// Set the interface Maximum Transmission Unit (MTU)
	// - Range: `64`-`18000`
	// +kubebuilder:validation:Optional
	Mtu *float64 `json:"mtu,omitempty" tf:"mtu,omitempty"`

	// Range: 1-512
	//
	// - Range: `1`-`512`
	// +kubebuilder:validation:Optional
	Name *float64 `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) Enable link autonegotiation
	// Enable link autonegotiation
	// +kubebuilder:validation:Optional
	NegotiationAuto *bool `json:"negotiationAuto,omitempty" tf:"negotiation_auto,omitempty"`

	// (Boolean) Shutdown the selected interface
	// Shutdown the selected interface
	// +kubebuilder:validation:Optional
	Shutdown *bool `json:"shutdown,omitempty" tf:"shutdown,omitempty"`

	// (Boolean) Allow SNMP LINKUP and LINKDOWN traps
	// Allow SNMP LINKUP and LINKDOWN traps
	// +kubebuilder:validation:Optional
	SnmpTrapLinkStatus *bool `json:"snmpTrapLinkStatus,omitempty" tf:"snmp_trap_link_status,omitempty"`

	// (String) Change an interface's spanning tree guard mode
	// Change an interface's spanning tree guard mode
	// - Choices: `loop`, `none`, `root`
	// +kubebuilder:validation:Optional
	SpanningTreeGuard *string `json:"spanningTreeGuard,omitempty" tf:"spanning_tree_guard,omitempty"`

	// (String) Specify a link type for spanning tree tree protocol use
	// Specify a link type for spanning tree tree protocol use
	// - Choices: `point-to-point`, `shared`
	// +kubebuilder:validation:Optional
	SpanningTreeLinkType *string `json:"spanningTreeLinkType,omitempty" tf:"spanning_tree_link_type,omitempty"`

	// (Boolean) (DEPRECATED) Spanning tree portfast options
	// (DEPRECATED) Spanning tree portfast options
	// +kubebuilder:validation:Optional
	SpanningTreePortfast *bool `json:"spanningTreePortfast,omitempty" tf:"spanning_tree_portfast,omitempty"`

	// (Boolean) (DEPRECATED) Disable portfast for this interface
	// (DEPRECATED) Disable portfast for this interface
	// +kubebuilder:validation:Optional
	SpanningTreePortfastDisable *bool `json:"spanningTreePortfastDisable,omitempty" tf:"spanning_tree_portfast_disable,omitempty"`

	// (Boolean) (DEPRECATED) Enable portfast edge on the interface
	// (DEPRECATED) Enable portfast edge on the interface
	// +kubebuilder:validation:Optional
	SpanningTreePortfastEdge *bool `json:"spanningTreePortfastEdge,omitempty" tf:"spanning_tree_portfast_edge,omitempty"`

	// (Boolean) (DEPRECATED) Enable portfast on the interface even in trunk mode
	// (DEPRECATED) Enable portfast on the interface even in trunk mode
	// +kubebuilder:validation:Optional
	SpanningTreePortfastTrunk *bool `json:"spanningTreePortfastTrunk,omitempty" tf:"spanning_tree_portfast_trunk,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	Switchport *bool `json:"switchport,omitempty" tf:"switchport,omitempty"`

	// (String) trusted device class
	// trusted device class
	// - Choices: `cisco-phone`, `cts`, `ip-camera`, `media-player`
	// +kubebuilder:validation:Optional
	TrustDevice *string `json:"trustDevice,omitempty" tf:"trust_device,omitempty"`

	// (String) Configure forwarding table
	// Configure forwarding table
	// +crossplane:generate:reference:type=github.com/upbound/provider-upjet-iosxe/apis/cluster/routing/v1alpha1.VRF
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("name",false)
	// +kubebuilder:validation:Optional
	VrfForwarding *string `json:"vrfForwarding,omitempty" tf:"vrf_forwarding,omitempty"`

	// Reference to a VRF in routing to populate vrfForwarding.
	// +kubebuilder:validation:Optional
	VrfForwardingRef *v2.Reference `json:"vrfForwardingRef,omitempty" tf:"-"`

	// Selector for a VRF in routing to populate vrfForwarding.
	// +kubebuilder:validation:Optional
	VrfForwardingSelector *v2.Selector `json:"vrfForwardingSelector,omitempty" tf:"-"`

	// (String) Security zone
	// Security zone
	// +kubebuilder:validation:Optional
	ZoneMemberSecurity *string `json:"zoneMemberSecurity,omitempty" tf:"zone_member_security,omitempty"`
}

// PortChannelSpec defines the desired state of PortChannel
type PortChannelSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   PortChannelParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PortChannelInitParameters `json:"initProvider,omitempty"`
}

// PortChannelStatus defines the observed state of PortChannel.
type PortChannelStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               PortChannelObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// PortChannel is the Schema for the PortChannels API. This resource can manage the Interface Port Channel configuration.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,iosxe}
type PortChannel struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   PortChannelSpec   `json:"spec"`
	Status PortChannelStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PortChannelList contains a list of PortChannels
type PortChannelList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PortChannel `json:"items"`
}

// Repository type metadata.
var (
	PortChannel_Kind             = "PortChannel"
	PortChannel_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: PortChannel_Kind}.String()
	PortChannel_KindAPIVersion   = PortChannel_Kind + "." + CRDGroupVersion.String()
	PortChannel_GroupVersionKind = CRDGroupVersion.WithKind(PortChannel_Kind)
)

func init() {
	SchemeBuilder.Register(&PortChannel{}, &PortChannelList{})
}
