apiVersion: multicast.iosxe.upbound.io/v1alpha1
kind: MSDP
metadata:
  annotations:
    meta.upbound.io/example-id: multicast/v1alpha1/msdp
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    originatorId: Loopback100
    passwords:
    - addr: 10.1.1.1
      encryption: 0
      passwordSecretRef:
        key: example-key
        name: example-secret
        namespace: upbound-system
    peers:
    - addr: 10.1.1.1
      connectSourceLoopback: 100
      remoteAs: 65000
    vrfs:
    - originatorId: Loopback200
      passwords:
      - addr: 10.1.1.1
        encryption: 0
        passwordSecretRef:
          key: example-key
          name: example-secret
          namespace: upbound-system
      peers:
      - addr: 10.1.1.1
        connectSourceLoopback: 200
        remoteAs: 65000
      vrf: VRF1
