// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type InsideSourceInterfacesInitParameters struct {

	// (String) The path of the object.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Attributes List) Specify interface for global address (see below for nested schema)
	Interfaces []InterfacesInitParameters `json:"interfaces,omitempty" tf:"interfaces,omitempty"`
}

type InsideSourceInterfacesObservation struct {

	// (String) The path of the object.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Attributes List) Specify interface for global address (see below for nested schema)
	Interfaces []InterfacesObservation `json:"interfaces,omitempty" tf:"interfaces,omitempty"`
}

type InsideSourceInterfacesParameters struct {

	// (String) The path of the object.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`

	// (Attributes List) Specify interface for global address (see below for nested schema)
	// +kubebuilder:validation:Optional
	Interfaces []InterfacesParameters `json:"interfaces,omitempty" tf:"interfaces,omitempty"`
}

type InsideSourceStaticEntriesInitParameters struct {

	// (String) Loopback interface
	// Loopback interface
	EgressInterfaceLoopback *string `json:"egressInterfaceLoopback,omitempty" tf:"egress_interface_loopback,omitempty"`

	// (Boolean) Extend this translation when used
	// Extend this translation when used
	Extendable *bool `json:"extendable,omitempty" tf:"extendable,omitempty"`

	// (Boolean) Delete this entry and its children, even if in use
	// Delete this entry and its children, even if in use
	Forced *bool `json:"forced,omitempty" tf:"forced,omitempty"`

	// (String)
	GlobalIP *string `json:"globalIp,omitempty" tf:"global_ip,omitempty"`

	// (Boolean) Overload an address translation
	// Overload an address translation
	InsideStaticOverload *bool `json:"insideStaticOverload,omitempty" tf:"inside_static_overload,omitempty"`

	// (String) Name pool of local addresses
	// Name pool of local addresses
	InsideStaticPool *string `json:"insideStaticPool,omitempty" tf:"inside_static_pool,omitempty"`

	// (String)
	LocalIP *string `json:"localIp,omitempty" tf:"local_ip,omitempty"`

	// (Number) Associate a mapping id to this mapping
	// Associate a mapping id to this mapping
	// - Range: `1`-`2147483647`
	MappingID *float64 `json:"mappingId,omitempty" tf:"mapping_id,omitempty"`

	// (String)
	Mask *string `json:"mask,omitempty" tf:"mask,omitempty"`

	// (String) Subnet translation
	// Subnet translation
	// - Choices: `network`
	Network *string `json:"network,omitempty" tf:"network,omitempty"`

	// (Boolean) Do not create an alias for the global address
	// Do not create an alias for the global address
	NoAlias *bool `json:"noAlias,omitempty" tf:"no_alias,omitempty"`

	// (Boolean) No translation of embedded address/port in the payload
	// No translation of embedded address/port in the payload
	NoPayload *bool `json:"noPayload,omitempty" tf:"no_payload,omitempty"`

	// (String) NAT redundancy operation
	// NAT redundancy operation
	Redundancy *string `json:"redundancy,omitempty" tf:"redundancy,omitempty"`

	// (Boolean)
	Reversible *bool `json:"reversible,omitempty" tf:"reversible,omitempty"`

	// map
	// Specify route-map
	RouteMap *string `json:"routeMap,omitempty" tf:"route_map,omitempty"`

	// (Boolean) No flow entries (session) for mapping
	// No flow entries (session) for mapping
	Stateless *bool `json:"stateless,omitempty" tf:"stateless,omitempty"`
}

type InsideSourceStaticEntriesObservation struct {

	// (String) Loopback interface
	// Loopback interface
	EgressInterfaceLoopback *string `json:"egressInterfaceLoopback,omitempty" tf:"egress_interface_loopback,omitempty"`

	// (Boolean) Extend this translation when used
	// Extend this translation when used
	Extendable *bool `json:"extendable,omitempty" tf:"extendable,omitempty"`

	// (Boolean) Delete this entry and its children, even if in use
	// Delete this entry and its children, even if in use
	Forced *bool `json:"forced,omitempty" tf:"forced,omitempty"`

	// (String)
	GlobalIP *string `json:"globalIp,omitempty" tf:"global_ip,omitempty"`

	// (Boolean) Overload an address translation
	// Overload an address translation
	InsideStaticOverload *bool `json:"insideStaticOverload,omitempty" tf:"inside_static_overload,omitempty"`

	// (String) Name pool of local addresses
	// Name pool of local addresses
	InsideStaticPool *string `json:"insideStaticPool,omitempty" tf:"inside_static_pool,omitempty"`

	// (String)
	LocalIP *string `json:"localIp,omitempty" tf:"local_ip,omitempty"`

	// (Number) Associate a mapping id to this mapping
	// Associate a mapping id to this mapping
	// - Range: `1`-`2147483647`
	MappingID *float64 `json:"mappingId,omitempty" tf:"mapping_id,omitempty"`

	// (String)
	Mask *string `json:"mask,omitempty" tf:"mask,omitempty"`

	// (String) Subnet translation
	// Subnet translation
	// - Choices: `network`
	Network *string `json:"network,omitempty" tf:"network,omitempty"`

	// (Boolean) Do not create an alias for the global address
	// Do not create an alias for the global address
	NoAlias *bool `json:"noAlias,omitempty" tf:"no_alias,omitempty"`

	// (Boolean) No translation of embedded address/port in the payload
	// No translation of embedded address/port in the payload
	NoPayload *bool `json:"noPayload,omitempty" tf:"no_payload,omitempty"`

	// (String) NAT redundancy operation
	// NAT redundancy operation
	Redundancy *string `json:"redundancy,omitempty" tf:"redundancy,omitempty"`

	// (Boolean)
	Reversible *bool `json:"reversible,omitempty" tf:"reversible,omitempty"`

	// map
	// Specify route-map
	RouteMap *string `json:"routeMap,omitempty" tf:"route_map,omitempty"`

	// (Boolean) No flow entries (session) for mapping
	// No flow entries (session) for mapping
	Stateless *bool `json:"stateless,omitempty" tf:"stateless,omitempty"`
}

type InsideSourceStaticEntriesParameters struct {

	// (String) Loopback interface
	// Loopback interface
	// +kubebuilder:validation:Optional
	EgressInterfaceLoopback *string `json:"egressInterfaceLoopback,omitempty" tf:"egress_interface_loopback,omitempty"`

	// (Boolean) Extend this translation when used
	// Extend this translation when used
	// +kubebuilder:validation:Optional
	Extendable *bool `json:"extendable,omitempty" tf:"extendable,omitempty"`

	// (Boolean) Delete this entry and its children, even if in use
	// Delete this entry and its children, even if in use
	// +kubebuilder:validation:Optional
	Forced *bool `json:"forced,omitempty" tf:"forced,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	GlobalIP *string `json:"globalIp" tf:"global_ip,omitempty"`

	// (Boolean) Overload an address translation
	// Overload an address translation
	// +kubebuilder:validation:Optional
	InsideStaticOverload *bool `json:"insideStaticOverload,omitempty" tf:"inside_static_overload,omitempty"`

	// (String) Name pool of local addresses
	// Name pool of local addresses
	// +kubebuilder:validation:Optional
	InsideStaticPool *string `json:"insideStaticPool,omitempty" tf:"inside_static_pool,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	LocalIP *string `json:"localIp" tf:"local_ip,omitempty"`

	// (Number) Associate a mapping id to this mapping
	// Associate a mapping id to this mapping
	// - Range: `1`-`2147483647`
	// +kubebuilder:validation:Optional
	MappingID *float64 `json:"mappingId,omitempty" tf:"mapping_id,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Mask *string `json:"mask,omitempty" tf:"mask,omitempty"`

	// (String) Subnet translation
	// Subnet translation
	// - Choices: `network`
	// +kubebuilder:validation:Optional
	Network *string `json:"network,omitempty" tf:"network,omitempty"`

	// (Boolean) Do not create an alias for the global address
	// Do not create an alias for the global address
	// +kubebuilder:validation:Optional
	NoAlias *bool `json:"noAlias,omitempty" tf:"no_alias,omitempty"`

	// (Boolean) No translation of embedded address/port in the payload
	// No translation of embedded address/port in the payload
	// +kubebuilder:validation:Optional
	NoPayload *bool `json:"noPayload,omitempty" tf:"no_payload,omitempty"`

	// (String) NAT redundancy operation
	// NAT redundancy operation
	// +kubebuilder:validation:Optional
	Redundancy *string `json:"redundancy,omitempty" tf:"redundancy,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	Reversible *bool `json:"reversible,omitempty" tf:"reversible,omitempty"`

	// map
	// Specify route-map
	// +kubebuilder:validation:Optional
	RouteMap *string `json:"routeMap,omitempty" tf:"route_map,omitempty"`

	// (Boolean) No flow entries (session) for mapping
	// No flow entries (session) for mapping
	// +kubebuilder:validation:Optional
	Stateless *bool `json:"stateless,omitempty" tf:"stateless,omitempty"`
}

type InterfacesInitParameters struct {

	// (String)
	Interface *string `json:"interface,omitempty" tf:"interface,omitempty"`

	// (Boolean) Overload an address translation
	// Overload an address translation
	Overload *bool `json:"overload,omitempty" tf:"overload,omitempty"`
}

type InterfacesObservation struct {

	// (String)
	Interface *string `json:"interface,omitempty" tf:"interface,omitempty"`

	// (Boolean) Overload an address translation
	// Overload an address translation
	Overload *bool `json:"overload,omitempty" tf:"overload,omitempty"`
}

type InterfacesParameters struct {

	// (String)
	// +kubebuilder:validation:Optional
	Interface *string `json:"interface" tf:"interface,omitempty"`

	// (Boolean) Overload an address translation
	// Overload an address translation
	// +kubebuilder:validation:Optional
	Overload *bool `json:"overload,omitempty" tf:"overload,omitempty"`
}

type NATInitParameters struct {

	// is. Default value is all.
	// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is. Default value is `all`.
	// - Choices: `all`, `attributes`
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// (Attributes List) Specify access list describing local addresses (see below for nested schema)
	InsideSourceInterfaces []InsideSourceInterfacesInitParameters `json:"insideSourceInterfaces,omitempty" tf:"inside_source_interfaces,omitempty"`

	// (Attributes List) (see below for nested schema)
	InsideSourceStaticEntries []InsideSourceStaticEntriesInitParameters `json:"insideSourceStaticEntries,omitempty" tf:"inside_source_static_entries,omitempty"`

	// (Attributes List) (see below for nested schema)
	OutsideSourceStaticEntries []OutsideSourceStaticEntriesInitParameters `json:"outsideSourceStaticEntries,omitempty" tf:"outside_source_static_entries,omitempty"`
}

type NATObservation struct {

	// is. Default value is all.
	// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is. Default value is `all`.
	// - Choices: `all`, `attributes`
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// (String) The path of the object.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Attributes List) Specify access list describing local addresses (see below for nested schema)
	InsideSourceInterfaces []InsideSourceInterfacesObservation `json:"insideSourceInterfaces,omitempty" tf:"inside_source_interfaces,omitempty"`

	// (Attributes List) (see below for nested schema)
	InsideSourceStaticEntries []InsideSourceStaticEntriesObservation `json:"insideSourceStaticEntries,omitempty" tf:"inside_source_static_entries,omitempty"`

	// (Attributes List) (see below for nested schema)
	OutsideSourceStaticEntries []OutsideSourceStaticEntriesObservation `json:"outsideSourceStaticEntries,omitempty" tf:"outside_source_static_entries,omitempty"`
}

type NATParameters struct {

	// is. Default value is all.
	// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is. Default value is `all`.
	// - Choices: `all`, `attributes`
	// +kubebuilder:validation:Optional
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	// +kubebuilder:validation:Optional
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// (Attributes List) Specify access list describing local addresses (see below for nested schema)
	// +kubebuilder:validation:Optional
	InsideSourceInterfaces []InsideSourceInterfacesParameters `json:"insideSourceInterfaces,omitempty" tf:"inside_source_interfaces,omitempty"`

	// (Attributes List) (see below for nested schema)
	// +kubebuilder:validation:Optional
	InsideSourceStaticEntries []InsideSourceStaticEntriesParameters `json:"insideSourceStaticEntries,omitempty" tf:"inside_source_static_entries,omitempty"`

	// (Attributes List) (see below for nested schema)
	// +kubebuilder:validation:Optional
	OutsideSourceStaticEntries []OutsideSourceStaticEntriesParameters `json:"outsideSourceStaticEntries,omitempty" tf:"outside_source_static_entries,omitempty"`
}

type OutsideSourceStaticEntriesInitParameters struct {

	// (Boolean) Extend this translation when used
	// Extend this translation when used
	Extendable *bool `json:"extendable,omitempty" tf:"extendable,omitempty"`

	// (String)
	GlobalIP *string `json:"globalIp,omitempty" tf:"global_ip,omitempty"`

	// (String)
	LocalIP *string `json:"localIp,omitempty" tf:"local_ip,omitempty"`

	// (String)
	Mask *string `json:"mask,omitempty" tf:"mask,omitempty"`

	// (Boolean) Match incoming vrf
	// Match incoming vrf
	MatchInVrf *bool `json:"matchInVrf,omitempty" tf:"match_in_vrf,omitempty"`

	// (String) Subnet translation
	// Subnet translation
	// - Choices: `network`
	Network *string `json:"network,omitempty" tf:"network,omitempty"`

	// (Boolean) No translation of embedded address/port in the payload
	// No translation of embedded address/port in the payload
	NoPayload *bool `json:"noPayload,omitempty" tf:"no_payload,omitempty"`

	// (String) Name pool of local addresses
	// Name pool of local addresses
	OutsideStaticPool *string `json:"outsideStaticPool,omitempty" tf:"outside_static_pool,omitempty"`

	// (String) NAT redundancy operation
	// NAT redundancy operation
	Redundancy *string `json:"redundancy,omitempty" tf:"redundancy,omitempty"`
}

type OutsideSourceStaticEntriesObservation struct {

	// (Boolean) Extend this translation when used
	// Extend this translation when used
	Extendable *bool `json:"extendable,omitempty" tf:"extendable,omitempty"`

	// (String)
	GlobalIP *string `json:"globalIp,omitempty" tf:"global_ip,omitempty"`

	// (String)
	LocalIP *string `json:"localIp,omitempty" tf:"local_ip,omitempty"`

	// (String)
	Mask *string `json:"mask,omitempty" tf:"mask,omitempty"`

	// (Boolean) Match incoming vrf
	// Match incoming vrf
	MatchInVrf *bool `json:"matchInVrf,omitempty" tf:"match_in_vrf,omitempty"`

	// (String) Subnet translation
	// Subnet translation
	// - Choices: `network`
	Network *string `json:"network,omitempty" tf:"network,omitempty"`

	// (Boolean) No translation of embedded address/port in the payload
	// No translation of embedded address/port in the payload
	NoPayload *bool `json:"noPayload,omitempty" tf:"no_payload,omitempty"`

	// (String) Name pool of local addresses
	// Name pool of local addresses
	OutsideStaticPool *string `json:"outsideStaticPool,omitempty" tf:"outside_static_pool,omitempty"`

	// (String) NAT redundancy operation
	// NAT redundancy operation
	Redundancy *string `json:"redundancy,omitempty" tf:"redundancy,omitempty"`
}

type OutsideSourceStaticEntriesParameters struct {

	// (Boolean) Extend this translation when used
	// Extend this translation when used
	// +kubebuilder:validation:Optional
	Extendable *bool `json:"extendable,omitempty" tf:"extendable,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	GlobalIP *string `json:"globalIp" tf:"global_ip,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	LocalIP *string `json:"localIp" tf:"local_ip,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Mask *string `json:"mask,omitempty" tf:"mask,omitempty"`

	// (Boolean) Match incoming vrf
	// Match incoming vrf
	// +kubebuilder:validation:Optional
	MatchInVrf *bool `json:"matchInVrf,omitempty" tf:"match_in_vrf,omitempty"`

	// (String) Subnet translation
	// Subnet translation
	// - Choices: `network`
	// +kubebuilder:validation:Optional
	Network *string `json:"network,omitempty" tf:"network,omitempty"`

	// (Boolean) No translation of embedded address/port in the payload
	// No translation of embedded address/port in the payload
	// +kubebuilder:validation:Optional
	NoPayload *bool `json:"noPayload,omitempty" tf:"no_payload,omitempty"`

	// (String) Name pool of local addresses
	// Name pool of local addresses
	// +kubebuilder:validation:Optional
	OutsideStaticPool *string `json:"outsideStaticPool,omitempty" tf:"outside_static_pool,omitempty"`

	// (String) NAT redundancy operation
	// NAT redundancy operation
	// +kubebuilder:validation:Optional
	Redundancy *string `json:"redundancy,omitempty" tf:"redundancy,omitempty"`
}

// NATSpec defines the desired state of NAT
type NATSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            NATParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider NATInitParameters `json:"initProvider,omitempty"`
}

// NATStatus defines the observed state of NAT.
type NATStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               NATObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// NAT is the Schema for the NATs API. This resource can manage the NAT configuration.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,iosxe}
type NAT struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              NATSpec   `json:"spec"`
	Status            NATStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NATList contains a list of NATs
type NATList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NAT `json:"items"`
}

// Repository type metadata.
var (
	NAT_Kind             = "NAT"
	NAT_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: NAT_Kind}.String()
	NAT_KindAPIVersion   = NAT_Kind + "." + CRDGroupVersion.String()
	NAT_GroupVersionKind = CRDGroupVersion.WithKind(NAT_Kind)
)

func init() {
	SchemeBuilder.Register(&NAT{}, &NATList{})
}
