// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type PIMIPv6InitParameters struct {

	// is. Default value is all.
	// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is. Default value is `all`.
	// - Choices: `all`, `attributes`
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// (String)
	RpAddress *string `json:"rpAddress,omitempty" tf:"rp_address,omitempty"`

	// (String)
	RpAddressAccessList *string `json:"rpAddressAccessList,omitempty" tf:"rp_address_access_list,omitempty"`

	// (Boolean) Specify keyword bidir to configure a bidir RP
	// Specify keyword bidir to configure a bidir RP
	RpAddressBidir *bool `json:"rpAddressBidir,omitempty" tf:"rp_address_bidir,omitempty"`

	// (Attributes List) Select VPN Routing/Forwarding instance (see below for nested schema)
	Vrfs []PIMIPv6VrfsInitParameters `json:"vrfs,omitempty" tf:"vrfs,omitempty"`
}

type PIMIPv6Observation struct {

	// is. Default value is all.
	// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is. Default value is `all`.
	// - Choices: `all`, `attributes`
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// (String) The path of the object.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String)
	RpAddress *string `json:"rpAddress,omitempty" tf:"rp_address,omitempty"`

	// (String)
	RpAddressAccessList *string `json:"rpAddressAccessList,omitempty" tf:"rp_address_access_list,omitempty"`

	// (Boolean) Specify keyword bidir to configure a bidir RP
	// Specify keyword bidir to configure a bidir RP
	RpAddressBidir *bool `json:"rpAddressBidir,omitempty" tf:"rp_address_bidir,omitempty"`

	// (Attributes List) Select VPN Routing/Forwarding instance (see below for nested schema)
	Vrfs []PIMIPv6VrfsObservation `json:"vrfs,omitempty" tf:"vrfs,omitempty"`
}

type PIMIPv6Parameters struct {

	// is. Default value is all.
	// Configure behavior when deleting/destroying the resource. Either delete the entire object (YANG container) being managed, or only delete the individual resource attributes configured explicitly and leave everything else as-is. Default value is `all`.
	// - Choices: `all`, `attributes`
	// +kubebuilder:validation:Optional
	DeleteMode *string `json:"deleteMode,omitempty" tf:"delete_mode,omitempty"`

	// (String) A device name from the provider configuration.
	// A device name from the provider configuration.
	// +kubebuilder:validation:Optional
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	RpAddress *string `json:"rpAddress,omitempty" tf:"rp_address,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	RpAddressAccessList *string `json:"rpAddressAccessList,omitempty" tf:"rp_address_access_list,omitempty"`

	// (Boolean) Specify keyword bidir to configure a bidir RP
	// Specify keyword bidir to configure a bidir RP
	// +kubebuilder:validation:Optional
	RpAddressBidir *bool `json:"rpAddressBidir,omitempty" tf:"rp_address_bidir,omitempty"`

	// (Attributes List) Select VPN Routing/Forwarding instance (see below for nested schema)
	// +kubebuilder:validation:Optional
	Vrfs []PIMIPv6VrfsParameters `json:"vrfs,omitempty" tf:"vrfs,omitempty"`
}

type PIMIPv6VrfsInitParameters struct {

	// (String)
	RpAddress *string `json:"rpAddress,omitempty" tf:"rp_address,omitempty"`

	// (String)
	RpAddressAccessList *string `json:"rpAddressAccessList,omitempty" tf:"rp_address_access_list,omitempty"`

	// (Boolean) Specify keyword bidir to configure a bidir RP
	// Specify keyword bidir to configure a bidir RP
	RpAddressBidir *bool `json:"rpAddressBidir,omitempty" tf:"rp_address_bidir,omitempty"`

	// (String)
	Vrf *string `json:"vrf,omitempty" tf:"vrf,omitempty"`
}

type PIMIPv6VrfsObservation struct {

	// (String)
	RpAddress *string `json:"rpAddress,omitempty" tf:"rp_address,omitempty"`

	// (String)
	RpAddressAccessList *string `json:"rpAddressAccessList,omitempty" tf:"rp_address_access_list,omitempty"`

	// (Boolean) Specify keyword bidir to configure a bidir RP
	// Specify keyword bidir to configure a bidir RP
	RpAddressBidir *bool `json:"rpAddressBidir,omitempty" tf:"rp_address_bidir,omitempty"`

	// (String)
	Vrf *string `json:"vrf,omitempty" tf:"vrf,omitempty"`
}

type PIMIPv6VrfsParameters struct {

	// (String)
	// +kubebuilder:validation:Optional
	RpAddress *string `json:"rpAddress,omitempty" tf:"rp_address,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	RpAddressAccessList *string `json:"rpAddressAccessList,omitempty" tf:"rp_address_access_list,omitempty"`

	// (Boolean) Specify keyword bidir to configure a bidir RP
	// Specify keyword bidir to configure a bidir RP
	// +kubebuilder:validation:Optional
	RpAddressBidir *bool `json:"rpAddressBidir,omitempty" tf:"rp_address_bidir,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Vrf *string `json:"vrf" tf:"vrf,omitempty"`
}

// PIMIPv6Spec defines the desired state of PIMIPv6
type PIMIPv6Spec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   PIMIPv6Parameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PIMIPv6InitParameters `json:"initProvider,omitempty"`
}

// PIMIPv6Status defines the observed state of PIMIPv6.
type PIMIPv6Status struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               PIMIPv6Observation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// PIMIPv6 is the Schema for the PIMIPv6s API. This resource can manage the PIM IPv6 configuration.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,iosxe}
type PIMIPv6 struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              PIMIPv6Spec   `json:"spec"`
	Status            PIMIPv6Status `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PIMIPv6List contains a list of PIMIPv6s
type PIMIPv6List struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PIMIPv6 `json:"items"`
}

// Repository type metadata.
var (
	PIMIPv6_Kind             = "PIMIPv6"
	PIMIPv6_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: PIMIPv6_Kind}.String()
	PIMIPv6_KindAPIVersion   = PIMIPv6_Kind + "." + CRDGroupVersion.String()
	PIMIPv6_GroupVersionKind = CRDGroupVersion.WithKind(PIMIPv6_Kind)
)

func init() {
	SchemeBuilder.Register(&PIMIPv6{}, &PIMIPv6List{})
}
